### ISSUE TITLE
Installing lens on centos 7 using snap, is not working

### ISSUE THREAD

**Issue by israelKusayev** [lensapp/lens#1038]
**Describe the bug**
install lens on centos 7 using snap, not working!

**To Reproduce**
1. Run: `sudo snap install kontena-lens --classic`
2. Run:  `kontena-lens`

**Screenshots**

![image](https://user-images.githubusercontent.com/42112796/95293888-fb4c9880-087c-11eb-8d51-afc3cdf4f088.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.6
- OS: centos 7
- Installation method (e.g. snap or AppImage in Linux):  snap
 
**Logs:**

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/index.js
- /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.1BJ2Yx)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

(kontena-lens:116281): GdkPixbuf-WARNING **: 06:05:23.535: Cannot open pixbuf loader module file '/home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

```

**Comment by k-nuhdim** [comment]
**+ 1**    

at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/125/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/snapd/snap/kontena-lens/125/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/var/lib/snapd/snap/kontena-lens/125/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/var/lib/snapd/snap/kontena-lens/125/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.VsQltu)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/125/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
Segmentation fault

**Comment by vishwanathj** [comment]
I am trying to install on CentOS 8 and when I execute `kontena-lens`, I see the below:

<pre>[username@nuc10fnh ~]$ kontena-lens 
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:activate&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:set-frame-id&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:refresh&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:disconnect&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:install-feature&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:uninstall-feature&quot;
<font color="#4E9A06">info</font>: [IPC]: setup channel &quot;cluster:upgrade-feature&quot;

(kontena-lens:4606): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">13:06:30.262</font>: cannot open display: :0
</pre>

How do I get this resolved?

**Comment by vishwanathj** [comment]
> I am trying to install on CentOS 8 and when I execute `kontena-lens`, I see the below:
> 
> [username@nuc10fnh ~]$ kontena-lens 
> info: [IPC]: setup channel "cluster:activate"
> info: [IPC]: setup channel "cluster:set-frame-id"
> info: [IPC]: setup channel "cluster:refresh"
> info: [IPC]: setup channel "cluster:disconnect"
> info: [IPC]: setup channel "cluster:install-feature"
> info: [IPC]: setup channel "cluster:uninstall-feature"
> info: [IPC]: setup channel "cluster:upgrade-feature"
> 
> (kontena-lens:4606): Gtk-WARNING **: 13:06:30.262: cannot open display: :0
> 
> How do I get this resolved?

Mine got resolved per workaround at https://github.com/lensapp/lens/issues/196

**Comment by arfatbk** [comment]
> **Describe the bug**
> install lens on centos 7 using snap, not working!
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Run: `sudo snap install kontena-lens --classic`
> 
>     2. Run:  `kontena-lens`
> 
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/42112796/95293888-fb4c9880-087c-11eb-8d51-afc3cdf4f088.png)
> 
> **Environment (please complete the following information):**
> 
>     * Lens Version: 3.6.6
> 
>     * OS: centos 7
> 
>     * Installation method (e.g. snap or AppImage in Linux):  snap
> 
> 
> **Logs:**
> 
> ```
> innerError Error: Cannot find module '../build/Debug/pty.node'
> Require stack:
> - /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
> - /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/index.js
> - /var/lib/snapd/snap/kontena-lens/124/resources/app.asar/static/build/main.js
> - 
>     at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
>     at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
>     at Module._load (internal/modules/cjs/loader.js:690:27)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
>     at Module._compile (internal/modules/cjs/loader.js:967:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
>     '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/index.js',
>     '/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/static/build/main.js',
>     undefined
>   ]
> }
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.1BJ2Yx)
>     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
>     at Object.func [as .node] (electron/js2c/asar.js:149:18)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/124/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
>     at Module._compile (internal/modules/cjs/loader.js:967:30)
> 
> (kontena-lens:116281): GdkPixbuf-WARNING **: 06:05:23.535: Cannot open pixbuf loader module file '/home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory
> 
> This likely means that your installation is broken.
> Try running the command
>   gdk-pixbuf-query-loaders > /home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache
> to make things work again for the time being.
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> ```

I'm also facing similar issue. Tried AppImage as well on CentOS 7

**Comment by israelKusayev** [comment]
I wonder if anyone from the team have seen this issue,  our whole company uses centos 7 and we would be really happy to see lens working on centos

@jakolehm @nevalla @Nokel81 @aleksfront 
Please help

**Comment by Nokel81** [comment]
@israelKusayev I have reproduced basically the same issue, except that I see the following error instead:

```
/snap/kontena-lens/146/kontena-lens: error while loading shared libraries libXss.so.1: cannot open shared object file: No such file or directory.
```

**Comment by Nokel81** [comment]
@israelKusayev After running `sudo yum install libXScrnSaver` on my centos7 install I was easily able to run my locally built version of Lens.

Namely the following works:

1. Make sure that NodeJs@12 is installed (latest (or 12.20.X) is best)
2. Make sure that `yarn` is installed
3. Run `make build -B` in the root of a cloned Lens repo (would recommend checking out a release tagged branch such as the one for 4.0.4 instead of master)
4. Run the application `./dist/linux-unpacked/kontena-lens` there is also a snap install file in `./dist` which can be used as well.

**Comment by israelKusayev** [comment]
I don't see 4.0.4

**Comment by Nokel81** [comment]
Sorry I meant 4.0.3 which was just released https://github.com/lensapp/lens/tree/v4.0.3

**Comment by israelKusayev** [comment]
Yeah we don't see it because it 404 😏

**Comment by savioteles** [comment]
@Nokel81, I can't found the path `./dist/linux-unpacked/kontena-lens` after build the project.

**Comment by Nokel81** [comment]
@savioteles What is the tree of `./dist/`?

**Comment by ramuece09** [comment]
I still see the same issue with latest version 5.3.4 in centos7. Is it resolved for anyone?

**Comment by biot2** [comment]
Same issue on Centos 7.9

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/index.js
- /var/lib/snapd/snap/kontena-lens/182/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/var/lib/snapd/snap/kontena-lens/182/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.JOLjBB)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/182/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

(kontena-lens:18533): GdkPixbuf-WARNING **: 15:33:40.724: Cannot open pixbuf loader module file '/home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/dev/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
GLib-GIO-Message: 15:33:40.799: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

```
