### ISSUE TITLE
No startup or screen at startup after upgrade

### ISSUE THREAD

**Issue by mcgarrah** [lensapp/lens#1226]
**Describe the bug**
When I upgraded to 3.6.7 for Windows, the app does not load. I have three processes but no foreground window or loading screen.

**To Reproduce**
Start up Lens. Watch the three lens.exe in Task Manager. This is from a working install that has been used for awhile.
Tried to uninstall and reinstall. No difference in behavior.
Do not know where to look for logs to check any further.
Below logs from CMD.exe startup attempt with errors

**Expected behavior**
Screen loads to pick one of my clusters.

**Screenshots**
NA

**Environment (please complete the following information):**
- Lens Version: Lens-Setup-3.6.7.exe
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Both from downloaded EXE and via a chocolatey install
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
C:\Users\user\AppData\Local\Programs\kontena-lens>lens

C:\Users\user\AppData\Local\Programs\kontena-lens>
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: ≡ƒÜÇ Starting Lens from "C:\Users\user\AppData\Roaming\Lens"
info: Checking for update
info: [STORE]: LOADED from C:\Users\user\AppData\Roaming\Lens\config.json
info: [STORE]: LOADED from C:\Users\user\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\user\AppData\Roaming\Lens\lens-workspace-store.json
(node:22828) UnhandledPromiseRejectionWarning: Error: clusters[0].cluster.server is missing
    at C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\@kubernetes\client-node\dist\config_types.js:30:19
    at Function.map (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\@kubernetes\client-node\node_modules\underscore\underscore.js:207:24)
    at Object.newClusters (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\@kubernetes\client-node\dist\config_types.js:6:14)
    at KubeConfig.loadFromString (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\@kubernetes\client-node\dist\config.js:105:40)
    at KubeConfig.loadFromFile (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\@kubernetes\client-node\dist\config.js:75:14)
    at m (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:40319)
    at V.getKubeconfig (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:17172)
    at new V (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:14639)
    at de.fromStore (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:30143)
    at executeAction (C:\Users\user\AppData\Local\Programs\kontena-lens\resources\app.asar\node_modules\mobx\lib\mobx.js:927:19)
(node:22828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: Update for version 3.6.7 is not available (latest version: 3.6.7, downgrade is disallowed).
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://ASDFASDF.sk1.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:123412341234:cluster/eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:123412341234:cluster/eks
    user: arn:aws:eks:us-east-1:123412341234:cluster/eks
  name: arn:aws:eks:us-east-1:123412341234:cluster/eks
current-context: arn:aws:eks:us-east-1:123412341234:cluster/eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:123412341234:cluster/eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - eks
      command: aws
      env:
      - name: AWS_PROFILE
        value: disco
```

**Additional context**

**Comment by drawlerr** [comment]
Ran into the same problem this morning.  Quick fix: rename `lens-cluster-store.json` (path listed in debug output) to lens-cluster-store.json.backup or just delete this file, and Lens should start up fine next time.

**Comment by kasunsjc** [comment]
The same issue comes to the Mac as well. rename the file fix the problem

**Comment by mcgarrah** [comment]
That fixed the issue. Thanks.

**Comment by kyleli666** [comment]
Can't believe that “delete lens-cluster-store.json” saved my day again, even with the latest closed-source Lens today~ Thanks a lot~
This action can also solve the problem of the "Warnings" column strangely being fixed at the rightmost side and not being able to be pulled to recover.
