### ISSUE TITLE
Flaky integration test: workspaces › adds cluster in test-workspace

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#1517]
Seeing this quite often:

```
● Lens integration tests › workspaces › adds cluster in test-workspace

    An element could not be located on the page using the given search parameters.

      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
      at Object.<anonymous> (node_modules/webdriverio/build/lib/commands/click.js:17:19)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:190:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:539:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at node_modules/q/q.js:883:30
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)

```

**Comment by jakolehm** [comment]
Also:

```
● Lens integration tests › workspaces › checks if default workspace has active cluster

    An element could not be located on the page using the given search parameters.

      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
      at Object.<anonymous> (node_modules/webdriverio/build/lib/commands/click.js:17:19)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:190:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:539:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at node_modules/q/q.js:883:30
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
```

**Comment by nevalla** [comment]
> Lens integration tests › workspaces › adds cluster in test-workspace

There is a slight delay before created workspace appears into workspaces list on status bar. Don't know is the CICD machine so slow that sometimes timeout (5s) is hit.
