### ISSUE TITLE
Error in context will prevent Lens from opening

### ISSUE THREAD

**Issue by gabrielbcn** [lensapp/lens#1561]
**Describe the bug**
When there's an incomplete context in .kube/config file, Lens won't start up (no splash screen)

**To Reproduce**
Create a new context with kubectl, do not specify the whole info

example: kubectl config set-context aksdemo

Then open Lens

**Expected behavior**
To provide a message to the user or to ignore the error, but not to freeze without any output, any user may go crazy

**Screenshots**
No screen shot but this is what happens when you open in debug mode

~ $ bash
bash-5.0$ DEBUG=true
bash-5.0$ /Applications/Lens.app/Contents/MacOS/Lens
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/Users/gabriel/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/lens-workspace-store.json
(node:6931) UnhandledPromiseRejectionWarning: Error: contexts[3].context.cluster is missing
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:111:19
    at Function.map (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/node_modules/underscore/underscore.js:207:24)
    at Object.newContexts (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:92:14)
    at KubeConfig.loadFromString (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:106:40)
    at KubeConfig.loadFromFile (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:75:14)
    at m (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:40656)
    at V.getKubeconfig (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:17503)
    at new V (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:14732)
    at de.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:30480)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
(node:6931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: contexts[3].context.cluster is missing
info: Update for version 3.6.9 is not available (latest version: 3.6.9, downgrade is disallowed).
^Cbash-5.0$

Only after control C you regain control, no window is open.

**Environment (please complete the following information):**
- Lens Version: 3.6.9
- OS: [e.g. OSX] OSX Big Sur 11.0.1
- Installation method (e.g. snap or AppImage in Linux): brew install lens --cask
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
~ $ bash
bash-5.0$ DEBUG=true
bash-5.0$ /Applications/Lens.app/Contents/MacOS/Lens
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/Users/gabriel/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/gabriel/Library/Application Support/Lens/lens-workspace-store.json
(node:6931) UnhandledPromiseRejectionWarning: Error: contexts[3].context.cluster is missing
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:111:19
    at Function.map (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/node_modules/underscore/underscore.js:207:24)
    at Object.newContexts (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:92:14)
    at KubeConfig.loadFromString (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:106:40)
    at KubeConfig.loadFromFile (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:75:14)
    at m (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:40656)
    at V.getKubeconfig (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:17503)
    at new V (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:14732)
    at de.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:30480)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
(node:6931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: contexts[3].context.cluster is missing
info: Update for version 3.6.9 is not available (latest version: 3.6.9, downgrade is disallowed).
^Cbash-5.0$
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
a context exists in kubeconfig, but its context.cluster is missing
```
That was the problem, context existing with no details. Don't expect Lens to freeze without of that, just output an error.

**Additional context**

**Comment by nevalla** [comment]
Will be fixed in #1453
