### ISSUE TITLE
Additional Printer Columns in CRDs produce a crash in display

### ISSUE THREAD

**Issue by bsctl** [lensapp/lens#1732]
**Describe the bug**
We have kubernetes CRDs like this

```
$ kubectl get tnt
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER NAME   OWNER KIND   NODE SELECTOR    AGE
oil    9                 0                 alice        User         {"pool":"cmp"}   7

```

The Additional Printer Columns `{"pool":"cmp"}` creates a crash in CRDs display

**To Reproduce**
1. Add a new cluster to Lens having CRDs as above
2. Go to CRDs panel
3. Select an item of such CRD
4. See the error

**Expected behavior**
CRDs items should be correctly displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/2222461/101748044-55134e00-3acc-11eb-9ff0-670b026ebd4c.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.0 (Lens 3.6 was working fine)
- OS: OSX

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bpool%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wa (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4462026)
    at d (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4463664)
    at f (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4464773)
    at http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4466856
    at ko (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4476327)
    at gs (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4516713)
    at uc (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4507254)
    at sc (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4507179)
    at $s (http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4504209)
    at http://7022d9ad-4972-4bb1-ae26-768cfb94089e.localhost:62824/build/Lens.js:2:4455851
```

**Comment by bsctl** [comment]
fixed with current lens version
