### ISSUE TITLE
Lens 4.0.1 bugs

### ISSUE THREAD

**Issue by guliaka** [lensapp/lens#1740]
Click on node or pod does not bring properties window.

Also Lens crashing with following error:

Component stack:

    in r
    in aside
    in div
    in r
    in r
    in t
    in Unknown
    in r

Error stack:

 
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:3776509)
    at http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:8681843
    at Array.map (<anonymous>)
    at http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:8681811
    at Array.map (<anonymous>)
    at r.value (http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:8681755)
    at r.value (http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:8687103)
    at ve (http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:18448)
    at http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:70625
    at ce (http://01bda9bd-3e2f-439c-a088-663e88439190.localhost:2545/build/Lens.js:2:16554)

----------------------------------------------------------------

After downgrading kubernetes cluster to 1.19.4 everything back to normal. So above errors are for kubernetes 1.20.0. My local kubectl is 1.19.4 what may also add to problem.

**Comment by J3m5** [comment]
Same as #1711

**Comment by fzalila** [comment]
same issue here.

**Comment by nevalla** [comment]
Duplicate of #1711. Let's monitor the issue there.

**Comment by srinat999** [comment]
Can confirm. Lens 4.0.3. Kubernetes 1.20.0 installed via kubeadm. Debian 10

**Comment by colabltd** [comment]
same issue here.
Can confirm. Lens 4.0.3. Kubernetes 1.20.0 installed via kubeadm. centos-7

**Comment by J3m5** [comment]
The 4.0.4 version has a fix, try to upgrade.
