### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by christophsteinl** [lensapp/lens#1758]
I'm getting an error in 4.0.0 when connecting to a brand new kubernetes v1.20.0 cluster via a plink ssh tunnel:

http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/nodes
Error stack:

 
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:3776353)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:8681353
    at Array.map (<anonymous>)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:8681321
    at Array.map (<anonymous>)
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:8681265)
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:8686613)
    at ve (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:18448)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:70625
    at ce (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:62368/build/Lens.js:2:16554)

same in 4.0.2
 
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:3775674)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:8681250
    at Array.map (<anonymous>)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:8681218
    at Array.map (<anonymous>)
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:8681162)
    at r.value (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:8686510)
    at ve (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:18448)
    at http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:70625
    at ce (http://b1bda89f-2c27-487c-949d-6eab18ec1721.localhost:63933/build/Lens.js:2:16554)

**Comment by n-able-consulting** [comment]
kubernetes 1.20 crashes Lens 4.01 on Ubuntu 2.04 with following error:
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:3776509)
    at http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:8681245
    at Array.map (<anonymous>)
    at http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:8681213
    at Array.map (<anonymous>)
    at r.value (http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:8681157)
    at r.value (http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:8686505)
    at ve (http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:18448)
    at http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:70625
    at ce (http://dcf3ddaf-c57f-43e0-945e-cb4af3ff77dc.localhost:45225/build/Lens.js:2:16554)

**Comment by J3m5** [comment]
#1711 duplicate
