### ISSUE TITLE
Minified React error #31

### ISSUE THREAD

**Issue by YorikSar** [lensapp/lens#1855]
**Describe the bug**
I'm getting "Minified React error #31" from time to time suddenly

**To Reproduce**
I'm sorry, I can't provide concrete steps to reproduce this. It just happens at seemingly random times.

**Environment (please complete the following information):**
- Lens Version: 4.0.5 (happened on 4.0.4 as well)
- OS: macOS
- Installation method: dmg, I think.

**Logs:**
I'm getting this error with following stacks:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmessage%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at va (http://localhost:58097/build/Lens.js:2:4466096)
    at http://localhost:58097/build/Lens.js:2:4470970
    at ko (http://localhost:58097/build/Lens.js:2:4480397)
    at gs (http://localhost:58097/build/Lens.js:2:4520783)
    at uc (http://localhost:58097/build/Lens.js:2:4511324)
    at sc (http://localhost:58097/build/Lens.js:2:4511249)
    at $s (http://localhost:58097/build/Lens.js:2:4508279)
    at http://localhost:58097/build/Lens.js:2:4459921
    at t.unstable_runWithPriority (http://localhost:58097/build/Lens.js:2:4535163)
    at Ui (http://localhost:58097/build/Lens.js:2:4459630)
 ```

```
    in div
    in div
    in r
    in div
    in r
    in t
    in t
    in main
    in div
    in r
    in t
    in t
    in r
    in t
    in Unknown
    in r
```

**Comment by aleksfront** [comment]
Full error message is:
```
Objects are not valid as a React child (found: object with keys {message}). If you meant to render a collection of children, use an array instead.
```

**Comment by kilpatty** [comment]
Just received what I *think* is a similar error - posting logs here to help with debugging:

```
App crash at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/?lens-namespaces=default
```


```
Component stack:


    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440586
    at div
    at div
    at div
    at zD (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8191616)
    at div
    at jF (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8220244)
    at div
    at div
    at NF (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8226415)
    at footer
    at div
    at JY (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8260598)
    at pa (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7561652)
    at t (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:191498)
    at eT (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8263194)
```
    
```
    Error stack:

 
TypeError: Cannot read property 'containers' of undefined
    at Vm.getContainers (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7831473)
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:8210383
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440607
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440220
    at ce (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:12079)
    at e.track (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:23443)
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440196
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440033
    at G (http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440170)
    at http://32c9cefd-2cd3-4534-baac-5c69b78369e5.localhost:56004/build/Lens.js:2:7440586
```


Will post if I figure out how to get around this.

**Comment by Nokel81** [comment]
Closing in favour of #2393 since this is unactionable unfortunately.

As for your error @kilpatty I think it might be related to the line `pods.api.ts#L269` since that is the only place in the code that references `containers` from an object.
