### ISSUE TITLE
Attempting to change the name of a namespace results in a (self called) app crash

### ISSUE THREAD

**Issue by Andrei-Paul** [lensapp/lens#1876]
**Describe the bug**
Attempting to change the name of a namespace results in a (self called) app crash.

**To Reproduce**
1. Go to Namespaces
2. Click on ⠇and select Edit
3. Change name: of namespace and click Save
The effect is that a new namespace is created, the old one is left intact, but the Lens app claims a crash.

**Expected behavior**
namespace renamed

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.0.5
- OS: Windows 10.0.19041.685
- Installation method (e.g. snap or AppImage in Linux): Lens-Setup-4.0.5.exe

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
App crash at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/namespaces
To help us improve the product please report bugs to Slack community or Github issues tracker.

Error stack:
 
TypeError: e.getStatus is not a function
    at customizeTableRowProps (http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:8509351)
    at r.value (http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:1360434)
    at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:6140471
    at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:65400
    at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:65013
    at ce (http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:16554)
    at e.track (http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:27918)
    at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:64989
    at http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:64826
    at M (http://ade8f9f1-d507-496d-b697-df278801b50d.localhost:2021/build/Lens.js:2:64963)

Component stack:

    in c
    in div
    in div
    in t
    in div
    in r
    in div
    in r
    in div
    in div
    in r
    in r
    in r
    in main
    in div
    in c
    in r
    in t
    in t
    in r
    in main
    in div
    in r
    in r
    in t
    in Unknown
    in r
```

**Comment by osddeitf** [comment]
I'm experienced the similar issues when edit resources (I've tried Deployment, StatefulSet, Ingress,...) too, they updated, but below are logs when I edited Ingress:
```
Error stack:

TypeError: e.getRoutes is not a function
    at customRowHeights (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:8541192)
    at http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:6135902
    at Array.map (<anonymous>)
    at r.value (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:6135878)
    at r.value (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:6136341)
    at we (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:18448)
    at http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:70625
    at ce (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:16554)
    at e.track (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:27918)
    at r.c [as render] (http://c5fc59f6-3681-40c8-afe6-3a15de316f71.localhost:49270/build/Lens.js:2:70573)
```
May be some update introduced some regression bug recently.
It's annoying when I have to restart by pressing Cmd+R, it's restart all my opened terminal.

**Comment by Nokel81** [comment]
This is no longer a bug in 4.2.

**Comment by Nokel81** [comment]
This is still a problem in 4.2. Though it doesn't crash anymore.

**Comment by Nokel81** [comment]
The source of this bug is that when we edit a resource we aren't actually using the equivalent of `kubectl edit` (which reject renaming namespaces rightly I think).

Some other things that I have noticed:
- The Namespace view appears to "work". Namely, if you edit a namespace the old one disappears and the new own appears (until you reload)
- If you are editing a namespace and "reload" then only that namespace will be displayed in the view (and the drop down)

https://user-images.githubusercontent.com/8225332/112207840-02c6ea80-8bee-11eb-88a7-d7989823447d.mov
