### ISSUE TITLE
App crash when saving secret

### ISSUE THREAD

**Issue by clambin** [lensapp/lens#1903]
**Describe the bug**
Experienced an app crash when updating & saving a secret.

Exact error message was: App crash at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/secrets?namespaces=default&details=/api/v1/namespaces/default/secrets/tado-exporter

also got the following error stack:

```
Error stack:

 
TypeError: e.getKeys is not a function
    at renderTableContents (http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:8611844)
    at r.value (http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:1360736)
    at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:6140338
    at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:65400
    at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:65013
    at ce (http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:16554)
    at e.track (http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:27918)
    at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:64989
    at http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:64826
    at M (http://f149345d-d630-497b-ba50-d3c2f3b84bb8.localhost:53723/build/Lens.js:2:64963)
```

The secret *was* saved, however.

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: OSX 11.1
- Installation method (e.g. snap or AppImage in Linux): download

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: 🚀 Starting Lens from "/Users/christophe/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: LensProxy server has started at http://localhost:62957
info: [EXTENSION-DISCOVERY] loading extensions from /Users/christophe/Library/Application Support/Lens
info: [CLUSTER]: "default" init success {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","context":"default","apiUrl":"https://192.168.0.11:6443"}
info: [EXTENSION-INSTALLER] installing dependencies at /Users/christophe/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] dependencies installed at /Users/christophe/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/christophe/.k8slens/extensions
info: [EXTENSION]: enabled lens-license@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from /Users/christophe/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: Update for version 4.0.6 is not available (latest version: 4.0.6, downgrade is disallowed).
info: [CLUSTER]: activate {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:f149345d-d630-497b-ba50-d3c2f3b84bb8" {"data":"Authentication proxy started\n","meta":{"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: Downloading kubectl 1.20.0 from https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/darwin/amd64/kubectl to /Users/christophe/Library/Application Support/Lens/binaries/kubectl/1.20.0/kubectl
(node:58239) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info: [CLUSTER]: refresh {"id":"f149345d-d630-497b-ba50-d3c2f3b84bb8","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://192.168.0.11:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
```

**Additional context**
N/A

**Comment by jakolehm** [comment]
Does this happen only with a specific secret/cluster? Asking because I cannot reproduce this.

**Comment by clambin** [comment]
Found the culprit:  I'd recently switched to a dev version of k3s v1.20.1+k3s (due to k3s issue https://github.com/k3s-io/k3s/issues/2704). That one seems to be causing this behaviour: after switching back to k3s v1.19.4+k3s2, the problem went away.

The behaviour was true for all secrets, even configmaps, etc.  

Not clear to me if this is due a problem with k3s 1.20, or that particular dev version:  can't upgrade to anything else due to that k3s bug. Will leave up to you to decide if you want to close this, or investigate further.

**Comment by aleksfront** [comment]
Seems to be related to #1923
