### ISSUE TITLE
Application has stopped opening

### ISSUE THREAD

**Issue by guymeron** [lensapp/lens#1948]
**Describe the bug**
Application has stopped opening. loading splash screen doesn't and application window don't appear.

**To Reproduce**
Open the application

**Expected behavior**
Splash screen should appear and load the application 

**Environment (please complete the following information):**
- Lens Version: Version 4.0.6 (4.0.6.20201230.21)
- OS: MacOS Big Sur 11.1
- Installation method: brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: 🚀 Starting Lens from "/Users/i/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/i/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/i/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/i/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /Users/i/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/i/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
(node:24571) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clusters' of undefined
    at KubeConfig.loadFromString (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:105:56)
    at KubeConfig.loadFromFile (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:75:14)
    at Xe (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:52944)
    at Ot.getKubeconfig (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:79166)
    at new Ot (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:75804)
    at qt.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:92755)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
    at qt.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:914:16)
    at qt.load (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:36832)
    at qt.load (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:90124)
(node:24571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: Update for version 4.0.6 is not available (latest version: 4.0.6, downgrade is disallowed).
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
irrelevant
```

**Additional context**
Downgrading version to 4.0.5 has the same behaviour

**Comment by jakolehm** [comment]
Does it start to work if you remove `/Users/i/Library/Application Support/Lens` (please take a backup of that folder first if you have precious kubeconfigs in Lens)?

**Comment by guymeron** [comment]
@jakolehm deleting the folder has solved the issue.
Thanks :) 👍

**Comment by stone-z** [comment]
I'm having the same issue on Ubuntu 18.04. Running from the command line gives no output at all.

This applies to versions 4.0.6, 4.0.5, 4.0.4, and 4.0.3 which all do not start.

Version 4.0.2 will still open and seems to work as expected otherwise.
