### ISSUE TITLE
Segmentation fault (core dumped) while starting lens

### ISSUE THREAD

**Issue by Swetad90** [lensapp/lens#2045]
I have installed lens 4.0.7 using snap on Ubuntu 18.04.1 LTS

Below are the snap details:
  snap version
  snap    2.48.2
  snapd   2.48.2
  series  16
  ubuntu  18.04
   kernel  4.15.0-130-generic  

At first starting lens asked to install the below shared libraries:
libgbm-dev
libxcb-dri3-0
libxcomposite-dev
libxdamage-dev
libxi-dev
libxtst-dev
libatk-adaptor
libgtk-3-0

And then while starting lens with command `sudo /snap/kontena-lens/152/kontena-lens --no-sandbox`, I get
`Segmentation fault`.

Can anyone tell me what else could I be missing here? Is there anything additional I have to enable on ubuntu for lens?

**Comment by Swetad90** [comment]
I also tried installing the Appimage but that too fails with the same error:

 ./Lens-4.0.8.AppImage

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get 'logs' path
    at Object.<anonymous> (/tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:1964)
    at n (/tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:165)
    at Module.<anonymous> (/tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:19436)
    at n (/tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:165)
    at /tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:1602
    at Object.<anonymous> (/tmp/.mount_Lens-4uTv4Nd/resources/app.asar/static/build/main.js:1:1612)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
Segmentation fault (core dumped)

**Comment by jim-docker** [comment]
Does it start without specifying `--no-sandbox`?

**Comment by Swetad90** [comment]
No, gives the below error without `--no-sandbox`

`Running as root without --no-sandbox is not supported. See https://crbug.com/638180`

**Comment by jim-docker** [comment]
Do you need to run as root? Also it seems odd that lens would ask to install shared libraries, it's packaged with what it needs via snap

**Comment by Swetad90** [comment]
I did run as root. And it gave the same error.

**Comment by jim-docker** [comment]
Ah, I meant did you try running not as root, I'm guessing yes. (not as root, without `--no-sandbox`)

**Comment by Nokel81** [comment]
Is this still a problem in 4.1.4?

**Comment by oscaralvarezrejas** [comment]
Please double check your DISPLAY variable, be sure you include the right port acording your X11 server configuration.
for example :
export DISPLAY=localhost:11.0
