### ISSUE TITLE
App crash at http://00000000-0000-0000-0000-000000000000.localhost:55042/workloads?namespaces=ci-gitlab

### ISSUE THREAD

**Issue by joaocc** [lensapp/lens#2051]
**Describe the bug**
Crash while browsing a cluster

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: macOS 10.13.6

**Logs:**
```
Component stack:


    in r
    in r
    in t
    in Unknown
    in r
Error stack:

 
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Failed%20to%20fetch&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:4412065)
    at F (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:4412165)
    at P (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:4412811)
    at Object.toArray (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:4413324)
    at r.value (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:6193258)
    at http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:6193633
    at http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:47431
    at Array.map (<anonymous>)
    at Proxy.forEach.Array.<computed>.hr.<computed> (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:47406)
    at r.value (http://280b3785-e6da-4616-88f7-2f756025addc.localhost:55042/build/Lens.js:2:6193590)
```

**Comment by aleksfront** [comment]
May be related to #1855

**Comment by Nokel81** [comment]
Closing in favour of #2393 since this is unactionable unfortunately.
