### ISSUE TITLE
Label name containing periods causes app crash

### ISSUE THREAD

**Issue by mkoziel2000** [lensapp/lens#2086]
Creating the following resource causes the Lens app to crash when trying to view the resource.

apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  name: "inventory-connector"
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: 192.168.1.1
    database.port: "1433"

The problem looks to be Lens trying to decipher the "strimzi.io/cluster" label name.  It thinks the period in the name is not valid and causes the app to crash.

Contents of the crash:
```
Error stack:


 Error: Lexical error on line 1. Unrecognized text.
...adata.labels.strimzi\.io/cluster
-----------------------^
    at n.parseError (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3703966)
    at n.e.yy.parseError (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3724531)
    at Object.parseError (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3706566)
    at Object.next (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3710539)
    at Object.lex (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3710706)
    at g (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3704388)
    at n.parse (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3704664)
    at s.nodes (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3722767)
    at s.query (http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3722396)
    at http://e6171934-8626-487c-9a9d-217f2b3e4bbd.localhost:62708/build/Lens.js:2:3660315
```

**Comment by jim-docker** [comment]
What Lens version is this happening for?

**Comment by mkoziel2000** [comment]
This was happening on an older version (3.6.10), when I upgraded to 4.0.8, the bug was resolved.  This can be closed.
