### ISSUE TITLE
Lens UI not showing up

### ISSUE THREAD

**Issue by ragnarpa** [lensapp/lens#2093]
**Describe the bug**

Install Lens either via Homebrew or installer directly. Try to open Lens. Lens UI does not show up.

**To Reproduce**

- Install Lens for Mac (via Homebrew or using installer directly) version 4.0.8
- Try to open Lens
- Lens UI does not show up

**Expected behavior**
Lens UI shows up.

**Screenshots**
No screenshots.

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): Homebrew and standard .dmg installation

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
❯ /Applications/Lens.app/Contents/MacOS/Lens
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/Users/ragnarpaide/Library/Application Support/Lens"
info: [STORE]: LOADED from /Users/ragnarpaide/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/ragnarpaide/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/ragnarpaide/Library/Application Support/Lens/lens-workspace-store.json
(node:39396) UnhandledPromiseRejectionWarning: TypeError: t is not iterable
    at de.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:30438)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
    at de.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:914:16)
    at de.load (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:59839)
    at App.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:120600)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:39396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jim-docker** [comment]
You could try renaming `~/Library/Application Support/Lens` and then restart Lens to see if it is due to config corruption of some sort. You can delete that folder if you don't need any Lens config you may have set up, or if it is easy to set up the config (clusters etc) again.

**Comment by ragnarpa** [comment]
Thanks. Cleaning `~/Library/Application Support/Lens` helped.
