### ISSUE TITLE
Lens UI does not show up after update

### ISSUE THREAD

**Issue by javirln** [lensapp/lens#2100]
**Describe the bug**

Install Lens either via Homebrew or installer directly. Try to open Lens. Lens UI does not show up.

**To Reproduce**

- Install Lens for Mac (via Homebrew or using installer directly) version 4.0.8
- Try to open Lens
- Lens UI does not show up
**Expected behavior**
Lens UI shows up.

**Screenshots**
No screenshots.

**Environment (please complete the following information):**

Lens Version: 4.0.8
OS: macOS
Installation method (e.g. snap or AppImage in Linux): Homebrew and standard .dmg installation
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
$ DEBUG=true DEBUG_PROXY=true /Applications/Lens.app/Contents/MacOS/Lens
info: 🚀 Starting Lens from "/Users/myuser/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/myuser/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/myuser/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/myuser/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /Users/myuser/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/myuser/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
(node:15504) UnhandledPromiseRejectionWarning: Error: contexts[4].context.cluster is missing
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:111:19
    at Function.map (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:207:24)
    at Object.newContexts (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:92:14)
    at KubeConfig.loadFromString (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:106:40)
    at KubeConfig.loadFromFile (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:75:14)
    at Xe (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:53051)
    at Ot.getKubeconfig (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:79344)
    at new Ot (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:75932)
    at qt.fromStore (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:93012)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
(node:15504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: contexts[4].context.cluster is missing
info: Update for version 4.0.8 is not available (latest version: 4.0.8, downgrade is disallowed).
debug: checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by javirln** [comment]
After more debugging and inspecting the `kubeconfig` file I see the wrong value has the following content:
```yaml
- context:
   cluster: ""
   user: ""
  name: default
```
The issue can be ignored. Sorry for the noise
