### ISSUE TITLE
App crash when clicking into a pod

### ISSUE THREAD

**Issue by jonocodes** [lensapp/lens#2289]
**Describe the bug**
Crashing when opening pod detail.

App crash at http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/pods?lens-namespaces=prod&lens-search=federa&lens-kube-details=%2Fapi%2Fv1%2Fnamespaces%2Fprod%2Fpods%2Fgraphql-federation-797d87db58-dh55d

**To Reproduce**
1. Go to the list of pods
2. Click on any pod
3. See error

Note that clicking on the three dot hamburger at the end of the row of the pod works. I can open the shell or the logs from there. I just can generally click into a pod to get its info.

**Screenshots**
![image](https://user-images.githubusercontent.com/1310468/110186007-c95a4680-7dc8-11eb-842d-be4f225b5e23.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: Arch Linux
- Installation method: aur/lens-bin (Arch User Repo)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:

    at QI (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:8013519)
    at span
    at div
    at jd (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7756151)
    at div
    at kI (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:8016142)
    at Details
    at div
    at div
    at div
    at Bp (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7728188)
    at Qd (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7753647)
    at sy (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7874585)
    at pa (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7560311)
    at t (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:191498)
    at eT (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:8261853)


Error stack:
 
TypeError: Cannot read property 'getId' of undefined
    at http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:8013840
    at http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:42956
    at Array.map (<anonymous>)
    at Proxy.forEach.Array.<computed>.pr.<computed> (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:42931)
    at QI.render (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:8013805)
    at Ce (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:13973)
    at http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7444538
    at ce (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:12079)
    at e.track (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:23443)
    at QI.s [as render] (http://62f88d5b-e64f-4557-bea1-d72c31363312.localhost:46857/build/Lens.js:2:7444486)

```

**Additional context**
This does not happen for all kube clusters. I have two hosted on AWS. Only one of the clusters seems to have this problem in Lens.

**Comment by jonocodes** [comment]
well it looks like this was fixed in Lens 4.1.4  :)
