### ISSUE TITLE
AppCrash: TypeError: Cannot read property 'showTimestamps' of undefined

### ISSUE THREAD

**Issue by rendasaev** [lensapp/lens#2652]
### Error stack
`
TypeError: Cannot read property 'showTimestamps' of undefined
    at VD.renderResourceSelector (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8294415)
    at VD.render (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8294930)
    at Ce (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:13973)
    at http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:7555662
    at ce (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:12079)
    at e.track (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:23443)
    at VD.s [as render] (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:7555610)
    at VD.Ee (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:7555758)
    at VD.t.render (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:7554714)
    at _s (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:4654529)
`

### Component stack
`
at VD (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8293593)
    at div
    at div
    at $D (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8299764)
    at footer
    at div
    at Jz (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8505313)
    at cc (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:7680420)
    at t (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:223892)
    at $z (http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/build/Lens.js:2:8506817)
`

App crash at http://47a6ec19-ccda-4972-b986-790bdba38c53.localhost:58154/pods?lens-namespaces=pmh-prod

Version: 
![image](https://user-images.githubusercontent.com/67231406/116351635-a82c3a00-a7fc-11eb-8efc-1123576e04e3.png)

**Comment by kanguru-au** [comment]
Similarly...
```
App crash at http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/pods?lens-namespaces=default%2Clens-metrics%2Ctomcat
```
### Error Stack:
```
TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8298282)
    at ce (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:12079)
    at e.computeValue (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:18380)
    at e.trackAndCompute (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:18206)
    at e.get (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:17257)
    at e.read (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:51873)
    at KD.get (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:53326)
    at KD.render (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8298389)
    at Ce (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:13973)
    at http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:7557924

```
### Component stack:
```
    at KD (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8296029)
    at div
    at tF (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8302064)
    at div
    at div
    at cF (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8308047)
    at footer
    at div
    at pU (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8513336)
    at cc (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:7682615)
    at t (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:223994)
    at BU (http://5bd6f7ac-e926-4072-9697-fa3e76b7f02b.localhost:50959/build/Lens.js:2:8514840)
```
### Newer version, though:
![image](https://user-images.githubusercontent.com/16165074/116404391-eca5ed00-a871-11eb-85cd-d16236735454.png)

**Comment by Nokel81** [comment]
Thanks for the report. I guess we didn't manage to fix this in the last release.

**Comment by jeongukjae** [comment]
Same problem here

Error Stack

```text
TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:8299041)
    at ce (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:12079)
    at e.computeValue (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:18380)
    at e.trackAndCompute (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:18206)
    at e.get (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:17257)
    at e.read (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:51873)
    at KD.get (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:53326)
    at KD.render (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:8299148)
    at Ce (http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:13973)
    at http://3e5a21c4-034a-41d9-95c5-959d209750d5.localhost:63698/build/Lens.js:2:7558683
```

**Comment by cwoodcox** [comment]
Same!

```
Component Stack:

    at KD (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8296788)
    at div
    at tF (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8302823)
    at div
    at div
    at cF (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8308806)
    at footer
    at div
    at pU (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8514060)
    at cc (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:7683374)
    at t (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:223994)
    at BU (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8515564)
```

```
Error stack:

TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8299041)
    at ce (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:12079)
    at e.computeValue (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:18380)
    at e.trackAndCompute (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:18206)
    at e.get (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:17257)
    at e.read (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:51873)
    at KD.get (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:53326)
    at KD.render (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:8299148)
    at Ce (http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:13973)
    at http://1819cd75-5958-42fd-9c35-9405210d74b2.localhost:56204/build/Lens.js:2:7558683
```

```
Lens: 4.2.4
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
© 2021, Mirantis, Inc.
```

**Comment by awoimbee** [comment]
Same, it's happening quite a lot but eventually goes away after lots of `ctrl+r`.
```
Component stack:
    at KD (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8295447)
    at div
    at tF (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8301482)
    at div
    at div
    at cF (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8307465)
    at footer
    at div
    at pU (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8512719)
    at cc (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:7682033)
    at t (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:223994)
    at BU (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8514223)

Error stack:
TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8297700)
    at ce (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:12079)
    at e.computeValue (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:18380)
    at e.trackAndCompute (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:18206)
    at e.get (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:17257)
    at e.read (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:51873)
    at KD.get (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:53326)
    at KD.render (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:8297807)
    at Ce (http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:13973)
    at http://16addcd1-ccdf-4120-98c6-9e7ce2f36ff6.localhost:33375/build/Lens.js:2:7557342
```

**Comment by masoudgs** [comment]
It's happening continuously. Would you give a priority to this bug?

**Comment by exocode** [comment]
4.2.5 too
```

Component stack:

    at KF (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8447673)
    at div
    at tD (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8453708)
    at div
    at div
    at cD (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8459691)
    at footer
    at div
    at pU (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8664945)
    at cc (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:7833783)
    at t (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:224373)
    at BU (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8666449)


Error stack:

 
TypeError: Cannot read property 'showTimestamps' of undefined
    at KF.get logs (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8449926)
    at ce (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:12079)
    at e.computeValue (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:18380)
    at e.trackAndCompute (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:18206)
    at e.get (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:17257)
    at e.read (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:51873)
    at KF.get (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:53326)
    at KF.render (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:8450033)
    at Ce (http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:13973)
    at http://1110903c-be86-4346-8a19-71d72605b448.localhost:53950/build/Lens.js:2:7709092
```

**Comment by Nokel81** [comment]
5.0.0 should be out tomorrow, you can try out the beta here https://k8slens.dev/lens5beta
