### ISSUE TITLE
updating secrets using lens on a self hosted workspace ends up in errors:

### ISSUE THREAD

**Issue by zozo6015** [lensapp/lens#2656]
**Describe the bug**
Updating secrets using lens in a self hosted workspace ends up in errors

**To Reproduce**
open up a secret and paste the configuration entries in there and then hit save
1. Go to 'Configuration'
2. Click on 'Secrets'
3. Click on a secret which has file based configs 
4. Click on the eye 
5. in the form select all configuration texts and replace the text
6. Click save
4. See errors
```
Component stack:


    at qp (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:7842926)
    at cc (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:7683374)
    at t (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:223994)
    at BU (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:8515599)
```
```
Error stack:

 
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Failed%20to%20fetch for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:4584576)
    at M (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:4584731)
    at Object.toArray (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:4585445)
    at qp.getMessage (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:7843507)
    at http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:7843758
    at http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:42956
    at Array.map (<anonymous>)
    at Proxy.forEach.Array.<computed>.pr.<computed> (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:42931)
    at qp.render (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:7843710)
    at Ce (http://9f177495-57ff-4f38-9a4c-9bdb334d3436.localhost:49752/build/Lens.js:2:13973)
```

**Expected behavior**
a green notification to show up that config was saved

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: OSX Big Sur 11.3
- Installation method (e.g. snap or AppImage in Linux): from package downloaded from github release

**Comment by zozo6015** [comment]
I have found out that the same error messages comes up when I try to do changes in configmap objects as well.

**Comment by zozo6015** [comment]
It seam to be fixed in the last update.
