### ISSUE TITLE
Lens not listing the namespaces in the drop-down filter

### ISSUE THREAD

**Issue by DavSanchez** [lensapp/lens#2696]
**Describe the bug**
Lens has stopped listing the namespaces in the drop-down filter, I think from the last 2 upgrades. I had added the namespaces manually in the settings because I don't have permissions to list them. It was working fine until the namespaces stopped showing, I have not changed any configuration nor the `.kube/config` file.

**To Reproduce**
1. Select a cluster
2. Go to whatever item that shows the namespaces (e.g. Workloads -> Pods)
3. Try to use the drop-down filter that should show all the namespaces.
4. Nothing appears there.

**Expected behavior**
As was happening before, I expected the drop-down filter to allow me to select namespaces and filter the resources accordingly.

**Screenshots**
If applicable, add screenshots to help explain your problem (namespaces and nodes redacted, but there are like 5 different namespaces here that I expected would be listed in the drop-down.)

![Namespace drop-down filter does not show namespaces](https://user-images.githubusercontent.com/11422515/116903957-0316c480-ac35-11eb-8fbe-9c326001c7a1.jpg)

![the namespaces were correctly added in the settings for the cluster](https://user-images.githubusercontent.com/11422515/116904001-12960d80-ac35-11eb-81c2-fc4846687680.jpg)

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): scoop

**Logs:**
I have redacted some paths and also the namespace names, as this is from work:
```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 succeeded ✅
info: 🚀 Starting Lens from "C:\Users\<redacted>\Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\lens-extensions.json
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\lens-workspace-store.json
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\lens-user-store.json
info: 🔑 Getting free port for LensProxy server
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-1","name":"redacted-namespace-1","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-2","name":"redacted-namespace-2","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-3","name":"redacted-namespace-3","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-4","name":"redacted-namespace-4","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-5","name":"redacted-namespace-5","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-7","name":"redacted-namespace-7","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"redacted-id-8","name":"redacted-namespace-8","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at http://localhost:53667
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from C:\Users\<redacted>\Lens
info: [CLUSTER]: "redacted-namespace-1" init success {"id":"redacted-id-1","context":"redacted-namespace-1","apiUrl":"https://api.deu01.k8s.anteater.dub.aws.k8s.3stripes.net"}
info: [CLUSTER]: "redacted-namespace-2" init success {"id":"redacted-id-2","context":"redacted-namespace-2","apiUrl":"https://api.pdh8b.k8s.he.k8s.emea.adsint.biz"}
info: [CLUSTER]: "redacted-namespace-3" init success {"id":"redacted-id-3","context":"redacted-namespace-3","apiUrl":"https://api.pcn01.k8s.argali.pek.aws.k8s.adidas.com.cn"}
info: [CLUSTER]: "redacted-namespace-4" init success {"id":"redacted-id-4","context":"redacted-namespace-4","apiUrl":"https://api.peu01.k8s.anteater.dub.aws.k8s.3stripes.net"}
info: [CLUSTER]: "redacted-namespace-5" init success {"id":"redacted-id-5","context":"redacted-namespace-5","apiUrl":"https://api.scn01.k8s.argali.pek.aws.k8s.adidas.com.cn"}
info: [CLUSTER]: "redacted-namespace-6" init success {"id":"redacted-id-6","context":"redacted-namespace-6","apiUrl":"https://api.no5j2.k8s.he.k8s.emea.adsint.biz"}
info: [CLUSTER]: "redacted-namespace-7" init success {"id":"redacted-id-7","context":"redacted-namespace-7","apiUrl":"https://api.seu01.k8s.anteater.dub.aws.k8s.3stripes.net"}
info: [CLUSTER]: "redacted-namespace-8" init success {"id":"redacted-id-8","context":"redacted-namespace-8","apiUrl":"https://api.n9tzk.k8s.he.k8s.emea.adsint.biz"}
info: [EXTENSION-INSTALLER] installing dependencies at C:\Users\<redacted>\Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:53667 ...
info: [EXTENSION-INSTALLER] dependencies installed at C:\Users\<redacted>\Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\<redacted-user-home>\.k8slens\extensions
info: [EXTENSION]: enabled lens-license@0.1.0
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\extension-store\lens-survey\preferences-store.json
info: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from C:\Users\<redacted>\Lens\extension-store\lens-telemetry\preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [WINDOW-MANAGER]: Main window loaded
info: 📡 Checking for app updates
info: Checking for update
info: [CLUSTER]: activate {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:redacted-id-6" {"data":"Authentication proxy started\n","meta":{"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: Update for version 4.2.3 is not available (latest version: 4.2.3, downgrade is disallowed).
info: APP:QUIT
info: [CLUSTER]: disconnect {"id":"redacted-id-1","name":"redacted-namespace-1","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-1","name":"redacted-namespace-1","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-2","name":"redacted-namespace-2","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-2","name":"redacted-namespace-2","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-3","name":"redacted-namespace-3","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-3","name":"redacted-namespace-3","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-4","name":"redacted-namespace-4","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-4","name":"redacted-namespace-4","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-5","name":"redacted-namespace-5","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-5","name":"redacted-namespace-5","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: unbind events {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: disconnect {"id":"redacted-id-7","name":"redacted-namespace-7","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-7","name":"redacted-namespace-7","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"redacted-id-8","name":"redacted-namespace-8","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"redacted-id-8","name":"redacted-namespace-8","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: activate {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\<redacted-user>\\scoop\\apps\\lens\\4.2.3\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
info: [KUBE-AUTH]: out-channel "kube-auth:redacted-id-6" {"data":"Authentication proxy started\n","meta":{"id":"redacted-id-6","name":"redacted-namespace-6","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}

```

**Kubeconfig:**
Sorry I had to redact a lot of the content here for the same reason as above. There are around 35 clusters and contexts here, all in the same format. I have not changed this file directly since first created (should only have changed due to kubectl or Lens action).
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: <redacted>
  name: <redacted>
- cluster:
    certificate-authority-data: ... 
    server: ...
  name: ...
- cluster:
    certificate-authority-data: ... 
    server: ...
  name: ...
contexts:
- context:
    cluster: <redacted> 
    user: <redacted>
  name: <redacted>
- context:
    cluster: ...
    user: ...
  name: ...
- context:
    cluster: ...
    user: ...
  name: ...
current-context: <redacted> 
kind: Config
preferences: {}
users:
- name: <redacted>
  user:
    auth-provider:
      config:
        access-token: <redacted> 
        apiserver-id: <redacted>
        client-id: <redacted>
        config-mode: "0"
        environment: AzurePublicCloud
        expires-in: "<redacted-int>"
        expires-on: "<redacted-int>"
        refresh-token: <redacted>
        tenant-id: <redacted>
      name: <redacted>
```

If there is any additional information you think I can provide please let me know. Thank you very much!

Best regards,
David

**Comment by Nokel81** [comment]
This has been fixed in 5.0.0.
