### ISSUE TITLE
TypeError: Cannot read property 'containers' of undefined

### ISSUE THREAD

**Issue by willymwai** [lensapp/lens#2854]
**Describe the bug**
Trying to view container logs of a deleted pod causes the app to crash

**To Reproduce**
1. Open pod container logs
2. Delete pod from kubectl shell
3. Try selecting a different container under pod logs

**Expected behavior**
An error showing that the container/pod cannot be found

**Screenshots**
![image](https://user-images.githubusercontent.com/3677734/119306159-7333cb80-bc72-11eb-96e9-b978562a5193.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows executable

**Comment by kalihman** [comment]
Having this issue too. 
![스크린샷 2021-05-28 오후 1 48 48](https://user-images.githubusercontent.com/9553745/119930961-70f7a700-bfbb-11eb-8940-8f6ab0d78ba0.png)

**Comment by mathewpeterson** [comment]
Is there any work around for this? I receive this error every time I open Lens, even after restart.

**Comment by efeerdogru** [comment]
I deleted kube config and re-add AKS clusters, so we can say it's a fresh install.

Lens connects one of the cluster, but not other. Clusters are same; one is prod, other is dev.

It tries to connect, shows a screen for a second, tries to load dashboard from prometheus I think, then crashes. 

```
Component stack:


    at http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:471194:16
    at div
    at div
    at div
    at InfoPanel (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:527883:9)
    at div
    at Logs (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:529865:9)
    at div
    at div
    at Dock (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:530277:9)
    at div
    at div
    at MainLayout (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:475441:9)
    at ErrorBoundary (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:474984:9)
    at Router (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:18291:30)
    at App (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:531355:9)
    at ThemeProvider (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:555915:24)
```

```
Error stack:

 
TypeError: Cannot read property 'containers' of undefined
    at pods_api_Pod.getContainers (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:502691:26)
    at http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:529108:28
    at http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:471194:49
    at http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:471158:25
    at trackDerivedFunction (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:1881:18)
    at Reaction.track (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:2409:18)
    at useObserver (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:471156:14)
    at http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:471194:16
    at Ch (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442361:137)
    at li (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442384:154)
    at ki (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442382:169)
    at ii (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442381:178)
    at ck (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442478:126)
    at bk (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442454:347)
    at ak (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442454:278)
    at Tj (http://a7e9d14882bc36b9adc7f9ee4b23766d.localhost:64276/build/Lens.js:442454:138)
```

**Comment by efeerdogru** [comment]
> 
> 
> Is there any work around for this? I receive this error every time I open Lens, even after restart.

Yes, delete folder: `~\AppData\Roaming\Lens\lens-local-storage` if you're in Windows, or same path in other OS.

**Comment by mathewpeterson** [comment]
I can confirm nuking `~/Library/Application Support/Lens` and reinstalling the application resolved my issue.
