### ISSUE TITLE
Cannot install Metrics Stack: operation not permitted (kubectl.exe)

### ISSUE THREAD

**Issue by nebula2** [lensapp/lens#2984]
**Describe the bug**
On my Windows 10 x64 machine with Lens installed - when trying to install the metrics stack for my Rpi k3s cluster I get an error saying:

```A JavaScript error occured in the main process

Uncaught Exception:
Error: EPERM: operation not permitted, open
'C:\Users\jackf\AppData\Roaming\Lens\binaries\kubectl\1.21.1+k3s1\kubecl.exe'
```

**To Reproduce**
1. Right-click on your cluster and click on settings
1. Under Features->Metrics Stack click on 'Install'
1. See error

**Expected behavior**
Prometheus stack get's installed

**Screenshots**
![image](https://user-images.githubusercontent.com/5841525/121074650-6d8ec780-c7d4-11eb-962e-27c4ec37f4dc.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- Electron: 9.4.0
- Chrome: 83.0.4103.122
- Node: 12.14.1
- OS: Windows 10 x64 (OS Build 19042.985)
- Installation method (e.g. snap or AppImage in Linux): Downloaded from website. Issue occures both installed globally and only for user

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
C:\Repos> cd "C:\Program Files\Lens"
C:\Program Files\Lens> .\Lens.exe
C:\Program Files\Lens>
info: 📟 Setting Lens as protocol client for lens://
info: 📟 succeeded ✅
```
(that is the end - nothing is really logged)

EDIT:
Found logs in appdata:
```
[31merror[39m: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Program Files\\Lens\\resources\\app.asar\\static\\build\\main.js:1:158674)\n    at ProxyServer.emit (C:\\Program Files\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Program Files\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:223:5)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"}
[32minfo[39m: [CLUSTER]: disconnect {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: unbind events {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: SERVICE:QUIT
[32minfo[39m: 📟 Setting Lens as protocol client for lens://
[32minfo[39m: 📟 succeeded ✅
[32minfo[39m: 🚀 Starting Lens from "C:\Users\jackf\AppData\Roaming\Lens"
[32minfo[39m: 🐚 Syncing shell environment
[32minfo[39m: 💾 Loading stores
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-user-store.json
[32minfo[39m: 🔑 Getting free port for LensProxy server
[32minfo[39m: [CLUSTER-MANAGER]: init cluster {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: 🔌 Starting LensProxy
[32minfo[39m: [LENS-PROXY]: Proxy server has started at http://localhost:59462
[32minfo[39m: 🔎 Testing LensProxy connection ...
[32minfo[39m: ⚡ LensProxy connection OK
[32minfo[39m: 🖥️  Starting WindowManager
[32minfo[39m: 🧩 Initializing extensions
[32minfo[39m: [EXTENSION-DISCOVERY] loading extensions from C:\Users\jackf\AppData\Roaming\Lens
[32minfo[39m: [CLUSTER]: "default" init success {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","context":"default","apiUrl":"https://192.168.178.79:6443"}
[32minfo[39m: [EXTENSION-INSTALLER] installing dependencies at C:\Users\jackf\AppData\Roaming\Lens
[32minfo[39m: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:59462 ...
[32minfo[39m: [EXTENSION-INSTALLER] dependencies installed at C:\Users\jackf\AppData\Roaming\Lens
[32minfo[39m: [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\jackf\.k8slens\extensions
[32minfo[39m: [EXTENSION]: enabled lens-license@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [STORE]: SAVING C:\Users\jackf\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [WINDOW-MANAGER]: Main window loaded
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: 📡 Checking for app updates
[32minfo[39m: Checking for update
[32minfo[39m: [CLUSTER]: activate {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: bind events {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: reconnect {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-workspace-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-user-store.json
[32minfo[39m: [CLUSTER-STORE] start to listen (1)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [EXTENSION]: enabled @nevalla/kube-resource-map@0.2.0
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /preferences
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /landing
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /landing/:workspaceId
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /extensions
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
[32minfo[39m: [LENS-VIEW]: init dashboard, clusterId=79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f
[32minfo[39m: [LENS-VIEW]: waiting cluster to be ready, clusterId=79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f
[31merror[39m: Can't find working API for the Kubernetes resource ingresses
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f" {"data":"Authentication proxy started\n","meta":{"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
[32minfo[39m: [LENS-VIEW]: loaded from http://79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f.localhost:59462/
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-workspace-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\lens-user-store.json
[32minfo[39m: [CLUSTER-STORE] start to listen (5)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [APP]: Init dashboard, clusterId=79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f, frameId=5
[32minfo[39m: Downloading kubectl 1.21.1+k3s1 from https://storage.googleapis.com/kubernetes-release/release/v1.21.1+k3s1/bin/windows/amd64/kubectl.exe to C:\Users\jackf\AppData\Roaming\Lens\binaries\kubectl\1.21.1+k3s1\kubectl.exe
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[31merror[39m: getaddrinfo ENOENT storage.googleapis.com {"errno":"ENOENT","code":"ENOENT","syscall":"getaddrinfo","hostname":"storage.googleapis.com"}
[31merror[39m: getaddrinfo ENOENT storage.googleapis.com {"errno":"ENOENT","code":"ENOENT","syscall":"getaddrinfo","hostname":"storage.googleapis.com"}
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[32minfo[39m: [STORE]: LOADED from C:\Users\jackf\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [EXTENSION]: enabled @nevalla/kube-resource-map@0.2.0
[32minfo[39m: Update for version 4.2.4 is not available (latest version: 4.2.4, downgrade is disallowed).
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[32minfo[39m: [STORE]: SAVING C:\Users\jackf\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [IPC]: undefined: /cluster/79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f/settings {"currentLocation":"http://localhost:59462/cluster/79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f"}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refreshMetadata {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [STORE]: SAVING C:\Users\jackf\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [FEATURE]: render templates from C:\Program Files\Lens\resources\extensions\metrics-cluster-feature\resources\
[32minfo[39m: Downloading kubectl 1.21.1+k3s1 from https://storage.googleapis.com/kubernetes-release/release/v1.21.1+k3s1/bin/windows/amd64/kubectl.exe to C:\Users\jackf\AppData\Roaming\Lens\binaries\kubectl\1.21.1+k3s1\kubectl.exe
[31merror[39m: getaddrinfo ENOENT storage.googleapis.com {"errno":"ENOENT","code":"ENOENT","syscall":"getaddrinfo","hostname":"storage.googleapis.com"}
[31merror[39m: getaddrinfo ENOENT storage.googleapis.com {"errno":"ENOENT","code":"ENOENT","syscall":"getaddrinfo","hostname":"storage.googleapis.com"}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"79f4f212-f8ad-4c0b-a0ae-7de06c4eb25f","name":"default","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```yml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ~~XXX~~
    server: https://192.168.178.79:6443
  name: default
- cluster:
    certificate-authority-data: ~~XXX~~
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: ~~XXX~~
    client-key-data: ~~XXX~~
- name: docker-desktop
  user:
    client-certificate-data: ~~XXX~~
    client-key-data: ~~XXX~~

```

**Additional context**
Issue also occures when running as administrator

**Comment by nebula2** [comment]
Seems like there are two main issues here.
1. My DNS is blocking `storage.googleapis.com`
  - solved that
 2. after resolving the DNS issue it still did not work because there is no fitting kubectl.exe in the archives. 
  - [this](https://github.com/lensapp/lens/issues/2805#issuecomment-847612987) solved it for me
