### ISSUE TITLE
App crash at /services

### ISSUE THREAD

**Issue by nachosalvi** [lensapp/lens#3023]
Component stack:

    at Notifications (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:494535:9)
    at ErrorBoundary (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:472644:9)
    at Router (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:16938:30)
    at App (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:529122:9)
    at ThemeProvider (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:552331:24)

Error stack:

 
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Failed%20to%20fetch for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at O (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:362886:207)
    at P (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:362886:355)
    at Object.toArray (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:362888:177)
    at Notifications.getMessage (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:494580:41)
    at http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:494586:34
    at http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:4118:23
    at Array.map (<anonymous>)
    at Proxy.<anonymous> (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:4117:36)
    at Notifications.render (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:494584:152)
    at allowStateChanges (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:1444:12)
    at http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:470128:59
    at trackDerivedFunction (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:1996:18)
    at Reaction.track (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:2524:18)
    at Notifications.reactiveRender [as render] (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:470126:14)
    at qi (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:442151:188)
    at pi (http://e6fe2882167269a76d6f932812cf3fe7.localhost:55607/build/Lens.js:442150:173)

**Comment by Nokel81** [comment]
Next time please follow the bug reporting format. We need to know version, OS, and what you were doing.

**Comment by aleksfront** [comment]
Might be related to #1855
