### ISSUE TITLE
App crash at http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/crd/datadoghq.com/watermarkpodautoscalers

### ISSUE THREAD

**Issue by cforce** [lensapp/lens#3100]
View carshes on viewing crd/datadoghq.com/watermarkpodautoscalers
Doing the same with kubectl get works

```
 http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7552631
    at div
    at div
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7804646)
    at div
    at qh (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7812615)
    at div
    at ip (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7814798)
    at div
    at div
    at ny (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7964629)
    at Ay (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7973947)
    at UE (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7935255)
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:227449)
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:229529)
    at cc (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7682615)
    at main
    at div
    at http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7552631
    at Lk (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:8266983)
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:227449)
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:229529)
    at cc (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7682615)
    at main
    at div
    at pU (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:8513301)
    at cc (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7682615)
    at t (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:223994)
    at BU (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:8514805)
```

Error stack:

 
```
Error: Parse error on line 1:
...ernal.currentValue..
-----------------------^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', '[', got '1'
    at i.parseError (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:783658)
    at i.e.yy.parseError (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:804223)
    at i.parse (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:784753)
    at o._normalize (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:803401)
    at o.stringify (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:803009)
    at o.value (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:801590)
    at http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7936416
    at Array.map (<anonymous>)
    at renderTableContents (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7936397)
    at ny.getRow (http://cc6a06a0-a3e8-4fec-b8a5-c1ba80be635e.localhost:63423/build/Lens.js:2:7966830)
```

**Comment by nevalla** [comment]
Thanks for reporting this. Please could you copy/paste the custom resource definition yaml for `watermarkpodautoscalers`?

**Comment by cforce** [comment]
https://github.com/DataDog/watermarkpodautoscaler/blob/main/chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml
