### ISSUE TITLE
Mobx ClusterManager error

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#3131]
```
[0] [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@333]' TypeError: Cannot set property 'src' of undefined
[0]     at ClusterManager.updateEntityFromCluster (webpack-internal:///./src/main/cluster-manager.ts:159:30)
[0]     at ClusterManager.updateCatalog (webpack-internal:///./src/main/cluster-manager.ts:136:18)
[0]     at executeAction (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1130:15)
[0]     at ClusterManager.updateCatalog (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1114:12)
[0]     at Object.fireImmediately (webpack-internal:///./src/main/cluster-manager.ts:77:136)
[0]     at executeAction (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1130:15)
[0]     at Reaction@333 (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1114:12)
[0]     at reactionRunner (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2670:109)
[0]     at Reaction.onInvalidate_ (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2651:7)
[0]     at Reaction.runReaction_ (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2286:16)
```

**Comment by jakolehm** [comment]
Probably happens only if some cluster has a custom icon.
