### ISSUE TITLE
Can not connect to k8s cluster after version 3.1.0

### ISSUE THREAD

**Issue by Itoktsnhc** [lensapp/lens#315]
**Describe the bug**
Can not connect to k8s cluster (aks china) after version 3.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11204672/80328677-98d58200-8872-11ea-8973-68d529ab4903.png)

**Environment 
- Lens Version: 3.3.1
- OS: windows 10 pro
- Installation method: release exe
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: Checking for update
info: Update for version 3.3.1 is not available (latest version: 3.3.1, downgrade is disallowed).
(node:23352) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at env (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\webpack:\src\main\kube-auth-proxy.ts:54:17)
    at C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641406
    at Object.next (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641511)
    at a (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:640228)
(node:23352) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at env (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\webpack:\src\main\kube-auth-proxy.ts:54:17)
    at C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641406
    at Object.next (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641511)
    at a (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:640228)
(node:23352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: Failed to connect to cluster bwntest: {"name":"RequestError","message":"Error: ESOCKETTIMEDOUT","cause":{"code":"ESOCKETTIMEDOUT","connect":false},"error":{"code":"ESOCKETTIMEDOUT","connect":false},"options":{"json":true,"timeout":10000,"headers":{"host":"4a010d12-a8f4-401b-876f-68165e9a952c.localhost:49153"},"uri":"http://127.0.0.1:49153/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```

kubectl can connect

**Comment by mokhos** [comment]
I have the same issue. After the 3.1.0 I cannot connect to the cluster!

**Comment by chicofranchico** [comment]
I'm also on 3.3.1 but on MacOSX. It seems I cannot connect to any configuration (neither GKE, EKS or OIDC). I also get timeouts.

**Comment by davydkov** [comment]
I think this is the same
https://github.com/lensapp/lens/issues/238
Though, apparently, the fix did not work

**Comment by Itoktsnhc** [comment]
3.4.0-beta.2 same issue

**Comment by josephtaylor** [comment]
It'd be nice if there was a way to turn off the auto-update so we could continue to use an actual working version.

**Comment by alexander-kucherov** [comment]
3.4.0 same problem

**Comment by jakolehm** [comment]
Do you all see the same error message?
```
(node:23352) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
```

**Comment by davydkov** [comment]
I fixed issue by removing bundled `kubectl` and put a symlink to the `kubectl` from the PATH

**Comment by Itoktsnhc** [comment]
> I fixed issue by removing bundled `kubectl` and put a symlink to the `kubectl` from the PATH

@davydkov  Thanks your workaround!
On windows you can close lens first and delete all files and  folders in the target folder:
 C:\Users\[username]\AppData\Roaming\Lens\binaries\kubectl  .
Then open lens and waiting for the kubectl auto download finish, and hit reconnect.

**Comment by Nokel81** [comment]
Is this still a problem in 4.1.4?

**Comment by Itoktsnhc** [comment]
I haven't encountered it after I cleaned up the binary

**Comment by Nokel81** [comment]
Okay thanks for the update. I think I'll close this and if someone encounters this again they can open a new issue.
