### ISSUE TITLE
Node panel won't open for AKS Virtual Node

### ISSUE THREAD

**Issue by jonstelly** [lensapp/lens#3206]
**Describe the bug**
Azure AKS instance with [Virtual Nodes](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes) enabled, clicking on the virtual node on the Nodes page causes an exception.

**To Reproduce**
1. Deploy AKS with Virtual Nodes enabled (detailed steps found on the link above)
2. Add cluster to Lens
3. Open Nodes tab
4. Click on the virtual node
5. Observe Error

**Expected behavior**
For node flyout to open without error

**Screenshots**
Nodes Tab
![image](https://user-images.githubusercontent.com/967068/123743326-a91c2f00-d872-11eb-975e-4945b39b61fa.png)

Exception
![image](https://user-images.githubusercontent.com/967068/123743352-b76a4b00-d872-11eb-9ad2-9ece120148e2.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.0-beta.13.20210628.2
- OS: Windows 10

**Logs:**
```
TypeError: Cannot read property 'endsWith' of undefined
    at node_details_resources_NodeDetailsResources.toMi (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:531010:22)
    at node_details_resources_NodeDetailsResources.render (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:531032:114)
    at qi (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442364:188)
    at pi (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442363:173)
    at ck (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442446:427)
    at bk (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442427:347)
    at ak (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442427:278)
    at Tj (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442427:138)
    at Lj (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442420:163)
    at http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442300:115
    at exports.unstable_runWithPriority (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442511:343)
    at gg (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442299:325)
    at jg (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442300:61)
    at ig (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442299:428)
    at Hb (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442469:101)
    at gd (http://c64d77838e622bc7bebd8bdc1487a188.localhost:54149/build/Lens.js:442250:352)
```

**Additional context**
From looking at NodeDetailsResources it looks like the fix may be as simple as adding null coalescing to the endsWith call:

```
  toMi(resource: string) {
    if (resource?.endsWith("Ki")) {
      return `${(parseInt(resource) / 1024).toFixed(1)}Mi`;
    }
```

**Comment by jonstelly** [comment]
Fixed in build from linked pull request:

![image](https://user-images.githubusercontent.com/967068/123893292-c2c87f80-d921-11eb-9097-ca9db3d2f0c9.png)
