### ISSUE TITLE
Lens5 on MacOs never starts

### ISSUE THREAD

**Issue by sergialonsaco** [lensapp/lens#3239]
**Describe the bug**
I've installed the latest version of Lens 5.0.0 and when starting it, it keeps on the loading initial screen.

**To Reproduce**
1. Install latest Lens version 5.0.0 downloaded from the website
2. Start Lens

**Expected behavior**
Lens should start as usual.

**Screenshots**
![Screenshot 2021-07-01 at 09 25 53](https://user-images.githubusercontent.com/45431066/124083643-6911a380-da4e-11eb-9be1-6ba1191774b8.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.0
- OS: MacOs Big Sur 11.4
- Installation method (e.g. snap or AppImage in Linux): Downloaded DMG file from website.

**Comment by nevalla** [comment]
If you open the app from the command line `/Applications/Lens.app/Contents/MacOS/Lens` do you see any errors? Could you paste the logs (without any sensitive data)?

**Comment by adriandrozdz** [comment]
I have the same issue and console output is this
```/Applications/Lens.app/Contents/MacOS/Lens                                                                                                                                                                                                                                                                                                                          ok
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
info: 🚀 Starting Lens from "/Users/adriandrozdz/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
error: shellEnv: Error: Resolving shell environment is taking very long. Please review your shell configuration.
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-user-store.json
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/lens-weblink-store.json
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:51394
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/adriandrozdz/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] installing dependencies at /Users/adriandrozdz/Library/Application Support/Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:51394 ...
info: [EXTENSION-INSTALLER] dependencies installed at /Users/adriandrozdz/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/adriandrozdz/.k8slens/extensions
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info: [STORE]: LOADED from /Users/adriandrozdz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json
error: [EXTENSIONS-LOADER]: can't load main for "lens-telemetry": TypeError: Cannot create a second singleton while creating a first {"extension":{"id":"/Users/adriandrozdz/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry/lens-telemetry-5.0.0-latest.20210629.3.tgz","manifestPath":"/Users/adriandrozdz/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"5.0.0-latest.20210629.3","description":"Lens IDE telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p && npm pack","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"files":["dist/**/*"],"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","@types/node":"^14.14.14","@types/react":"^17.0.0","@types/universal-analytics":"^0.4.4","analytics-node":"^3.4.0-beta.3","conf":"^7.1.2","jest":"^26.6.3","mobx":"^6.3.2","mobx-react":"^7.1.0","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2","webpack-cli":"^3.3.11"}},"isBundled":true,"isEnabled":true,"isCompatible":true}}
error: [EXTENSION]: failed to activate lens-survey@5.0.0-latest.20210629.3: Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
info: [EXTENSION]: enabled lens-license@5.0.0-latest.20210629.3
[CLUSTER-CONNECT] cluster proxy started on port 51408
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
error: [EXTENSION]: failed to activate lenscloud-lens-extension@5.0.0-latest.20210629.3: Error: Error while obtaining machine id: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
/bin/sh: ioreg: command not found
info: [WINDOW-MANAGER]: Main window loaded```

**Comment by nevalla** [comment]
@adriandrozdz anything else after those lines? I can see couple of errors related to extensions but AFAIK those should not prevent Lens to open.

Also noticing that syncing the shell environment is erroring out. Do you have any shell init scripts that might block shell opening?

**Comment by adriandrozdz** [comment]
@nevalla No, nothing after last line, I have no shell scripts AFAIK but this happens no matter how I try to start Lens via command or by clicking the icon. What I probably should have mentioned is that the icon in task bar appears but when choosing Preferences from it it shows blank window and I guess more important thing is that Lens starts normally with `sudo` but of course this is not a good solution. I'm running Mac on Intel with latest MacOS version.

**Comment by adriandrozdz** [comment]
@nevalla OK there's been some progress. I am using iTerm2 with zsh, oh-my-zsh and when I removed node / npm / npx products from it, Lens started with no problems

**Comment by sergialonsaco** [comment]
In my case, I can't see anything else in the logs when executing from cmd, using iterm2 with zsh and oh-my-zsh too. 
```
/Applications/Lens.app/Contents/MacOS/Lens
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
~/workspace ❯
```

**Comment by nevalla** [comment]
> In my case, I can't see anything else in the logs when executing from cmd, using iterm2 with zsh and oh-my-zsh too.
> 
> ```
> /Applications/Lens.app/Contents/MacOS/Lens
> info: 📟 Setting Lens as protocol client for lens://
> info: 📟 Protocol client register succeeded ✅
> ~/workspace ❯
> ```

This looks like there's already Lens process running. Please check that app is not running on the background (ie there's no tray icon or process running)

**Comment by sergialonsaco** [comment]
I got this logs when executing from shell now: 
```
❯ /Applications/Lens.app/Contents/MacOS/Lens
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
info: 🚀 Starting Lens from "/Users/xxx/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
error: shellEnv: Error: Resolving shell environment is taking very long. Please review your shell configuration.
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-user-store.json
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-cluster-store.json
warn: [CLUSTER-STORE]: Failed to update/create a cluster: fr: User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig
warn: [CLUSTER-STORE]: Failed to update/create a cluster: fr: User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/lens-weblink-store.json
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:59887
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/xxx/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] installing dependencies at /Users/xxx/Library/Application Support/Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:59887 ...
info: [EXTENSION-INSTALLER] dependencies installed at /Users/xxx/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/xxx/.k8slens/extensions
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info: [STORE]: LOADED from /Users/xxx/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json
error: [EXTENSIONS-LOADER]: can't load main for "lens-telemetry": TypeError: Cannot create a second singleton while creating a first {"extension":{"id":"/Users/xxx/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry/lens-telemetry-5.0.0-latest.20210629.3.tgz","manifestPath":"/Users/xxx/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"5.0.0-latest.20210629.3","description":"Lens IDE telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p && npm pack","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"files":["dist/**/*"],"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","@types/node":"^14.14.14","@types/react":"^17.0.0","@types/universal-analytics":"^0.4.4","analytics-node":"^3.4.0-beta.3","conf":"^7.1.2","jest":"^26.6.3","mobx":"^6.3.2","mobx-react":"^7.1.0","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2","webpack-cli":"^3.3.11"}},"isBundled":true,"isEnabled":true,"isCompatible":true}}
info: [STORE]: SAVING /Users/xxx/Library/Application Support/Lens/lens-extensions.json
error: [EXTENSION]: failed to activate lens-survey@5.0.0-latest.20210629.3: Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
info: [EXTENSION]: enabled lens-license@5.0.0-latest.20210629.3
[CLUSTER-CONNECT] cluster proxy started on port 59905
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
error: [EXTENSION]: failed to activate lenscloud-lens-extension@5.0.0-latest.20210629.3: Error: Error while obtaining machine id: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
/bin/sh: ioreg: command not found
info: [WINDOW-MANAGER]: Main window loaded
info: APP:ACTIVATE {"hasVisibleWindows":true}
```

After this the window of Lens loading stays in that state forever.

**Comment by nevalla** [comment]
Okay this looks very similar as @adriandrozdz is having. What shell environment do you use, do you have something on shell init scripts like oh-my-zsh or other scripts that might prevent shell opening?

**Comment by sergialonsaco** [comment]
> Okay this looks very similar as @adriandrozdz is having. What shell environment do you use, do you have something on shell init scripts like oh-my-zsh or other scripts that might prevent shell opening?

I'm using iTerm2 with zsh and oh-my-zsh on it. I can't find something that prevent shell opening, and I was opening it with the same configuration with the previous Lens version 4.2.0. Any clue on what could I check to see if there is something that prevent shell opening?

**Comment by nevalla** [comment]
as far as I know, the only change we've made here is that we put timeout to shell sync. Currently it is 5 seconds. Maybe that is a bit too aggressive? If you open new terminal, can you estimate how long does it take to open?

**Comment by sergialonsaco** [comment]
> as far as I know, the only change we've made here is that we put timeout to shell sync. Currently it is 5 seconds. Maybe that is a bit too aggressive? If you open new terminal, can you estimate how long does it take to open?

Yes, it took between 10-12 seconds to open. And it could make sense that the timeout is a but aggressive as in the logs there is the following error:
```
error: shellEnv: Error: Resolving shell environment is taking very long. Please review your shell configuration.
```
But is this shell sync what is making Lens not starting?

**Comment by nevalla** [comment]
> But is this shell sync what is making Lens not starting?

hard to say but I can see it's already causing some issues since `PATH` env var is not properly set. 

I will increase the timeout.
