### ISSUE TITLE
can not open lens5

### ISSUE THREAD

**Issue by justingkao** [lensapp/lens#3244]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```[32minfo[39m: 📟 Setting Lens as protocol client for lens://
[32minfo[39m: 📟 Protocol client register succeeded ✅
[32minfo[39m: 🚀 Starting Lens from "C:\Users\xxxx\AppData\Roaming\Lens"
[32minfo[39m: 🐚 Syncing shell environment
[32minfo[39m: 💾 Loading stores
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-user-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-hotbar-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-extensions.json
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\lens-weblink-store.json
[32minfo[39m: 🔌 Starting LensProxy
[32minfo[39m: [LENS-PROXY]: Proxy server has started at 127.0.0.1:60772
[32minfo[39m: 🔎 Testing LensProxy connection ...
[32minfo[39m: ⚡ LensProxy connection OK
[32minfo[39m: 🖥️  Starting WindowManager
[32minfo[39m: 🧩 Initializing extensions
[32minfo[39m: [EXTENSION-DISCOVERY] loading extensions from C:\Users\xxx\AppData\Roaming\Lens
[32minfo[39m: [EXTENSION-INSTALLER] installing dependencies at C:\Users\xxx\AppData\Roaming\Lens
[32minfo[39m: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:60772 ...
[32minfo[39m: [EXTENSION-INSTALLER] dependencies installed at C:\Users\xxx\AppData\Roaming\Lens
[32minfo[39m: [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\xxxx\.k8slens\extensions
[32minfo[39m: [STORE]: LOADED from C:\Users\xxx\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\auth-token-store.json
[31merror[39m: [EXTENSIONS-LOADER]: can't load main for "lens-telemetry": TypeError: Cannot create a second singleton while creating a first {"extension":{"id":"C:\\Users\\xxx\\AppData\\Roaming\\Lens\\node_modules\\lens-telemetry\\package.json","absolutePath":"C:\\Users\\xxx\\AppData\\Local\\Programs\\Lens\\resources\\extensions\\telemetry\\lens-telemetry-5.0.0-latest.20210629.3.tgz","manifestPath":"C:\\Users\\xxx\\AppData\\Roaming\\Lens\\node_modules\\lens-telemetry\\package.json","manifest":{"name":"lens-telemetry","version":"5.0.0-latest.20210629.3","description":"Lens IDE telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p && npm pack","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"files":["dist/**/*"],"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","@types/node":"^14.14.14","@types/react":"^17.0.0","@types/universal-analytics":"^0.4.4","analytics-node":"^3.4.0-beta.3","conf":"^7.1.2","jest":"^26.6.3","mobx":"^6.3.2","mobx-react":"^7.1.0","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2","webpack-cli":"^3.3.11"}},"isBundled":true,"isEnabled":true,"isCompatible":true}}
[31merror[39m: [EXTENSION]: failed to activate lens-survey@5.0.0-latest.20210629.3: Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
[32minfo[39m: [EXTENSION]: enabled lens-license@5.0.0-latest.20210629.3
[31merror[39m: [EXTENSION]: failed to activate lenscloud-lens-extension@5.0.0-latest.20210629.3: Error: Error while obtaining machine id: Error: Command failed: %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid
ERROR: Registry editing has been disabled by your administrator.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
Add any other context about the problem here.

**Comment by justingkao** [comment]
Why does lens5 need to read/write reg

**Comment by nevalla** [comment]
> Why does lens5 need to read/write reg

It seems that one library ([node-machine-id](https://github.com/automation-stack/node-machine-id)) that Lens uses, reads unique machineId from registry on Windows. Despite the library claims: 
> And No elevated rights required

We need to fix this, at least so that it catches that error.
