### ISSUE TITLE
Lens5 - no more logs and console buttons when a pod is selected?

### ISSUE THREAD

**Issue by strus38** [lensapp/lens#3266]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5890515/124464004-f0834d80-dd93-11eb-8bc4-c4419db060b7.png)

**To Reproduce**
Click on a POD ... I used to have a console and logs to inspect a pod, no more since Lens 5.

**Environment (please complete the following information):**
- Lens Version: 5
- OS: windows
- Installation method (e.g. snap or AppImage in Linux): Windows setup

**Comment by tomislater** [comment]
On ubuntu these icons are also missing. On macOS everything works correctly.

**Comment by m-czyz** [comment]
PopOS/Ubuntu also has that problem - installed by snap

**Comment by echupriyanov** [comment]
For me under macOS with v5.0.1 those icons are missing too

**Comment by PhilRanzato** [comment]
Aldo for me under Windows with v5.0.0 those icons are missing

**Comment by alexandrenas** [comment]
I've faced the same issue on Mac and I've found a way to fix it. 

I've opened the folder ~/Library/Application Support/Lens/node_modules/ and then you can see the subfolders below:

kube-object-event-status
lens-license
lens-metrics-cluster-feature
lens-node-menu
lens-pod-menu
lens-survey
lens-telemetry
lenscloud-lens-extension

For each one of these subfolders, you will find a .tgz file

Extract it and move the folder dist to the same level as the package.json file

Be aware for the folder lens-metrics-cluster-feature you need to move also the folder resources

Restart the Lens.

**Comment by strus38** [comment]
Well fine, but I switched back to lens 4 since even the connection manager
is working nicely while in V5 it works when it wants.

**Comment by jonstelly** [comment]
I had seen this issue in a previous lens 5 beta.  It had gone away in later betas and 5.0 release.  It's back for me with 5.0.1.

I opened the dev console and I see some errors   It's worth  noting that I got the 5.0.1 update available notification in the app, I click yes to install it and lens restarts, but it hadn't updated lens.  So I downloaded 5.0.1 and installed manually.  I wonder if that didn't clean up 5.0.0 files?

Error:
```
[EXTENSIONS-LOADER]: can't load renderer for "example-extension": TypeError: Cannot read property 'apiManager' of undefined
    at Object.<anonymous> (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:2980)
    at n (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:279)
    at Object.<anonymous> (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:1676)
    at Object.<anonymous> (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:2342)
    at n (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:279)
    at C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:1078
    at Object.<anonymous> (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:1:1087)
    at Object.<anonymous> (C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension\dist\renderer.js:23:3)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at extension_loader_ExtensionLoader.requireExtension (http://localhost:64534/build/Lens.js:510845:20) {id: "C:\Users\jon\AppData\Roaming\Lens\node_modules\example-extension\package.json", absolutePath: "C:\Users\jon\AppData\Local\Programs\kontena-lens\resources\extensions\example-extension", manifestPath: "C:\Users\jon\AppData\Roaming\Lens\node_modules\example-extension\package.json", manifest: {…}, isBundled: true, …}
```

EDIT: I did have lens 5.0.0 and 5.0.1 showing as installed in the Windows Control Panel.  I removed both, verified the lens directory was deleted, then installed 5.0.1 and I see a different error in the developer console:

SIDENOTE: It would be great if you could provide links to older releases (include the binaries in the github releases and don't delete old releases there?).  I had deleted my 5.0.0 installer so I had to scrounge around, I finally found the link to 5.0.0 from the chocolatey package [link](https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.0.0-latest.20210629.3.exe)

```
[EXTENSIONS-LOADER]: can't load renderer for "kube-object-event-status": Error: Cannot find module 'C:\Users\jon\AppData\Roaming\Lens\node_modules\kube-object-event-status\dist\renderer.js'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at extension_loader_ExtensionLoader.requireExtension (http://localhost:53702/build/Lens.js:510845:20)
    at Object.fireImmediately (http://localhost:53702/build/Lens.js:510816:57)
    at executeAction (http://localhost:53702/build/Lens.js:1266:15)
    at Reaction (http://localhost:53702/build/Lens.js:1250:12)
    at reactionRunner (http://localhost:53702/build/Lens.js:2735:44)
    at Reaction.onInvalidate_ (http://localhost:53702/build/Lens.js:2716:7)
    at Reaction.runReaction_ (http://localhost:53702/build/Lens.js:2381:16)
    at runReactionsHelper (http://localhost:53702/build/Lens.js:2524:29)
    at reactionScheduler (http://localhost:53702/build/Lens.js:2499:10)
    at http://localhost:53702/build/Lens.js:2537:14 {id: "C:\Users\jon\AppData\Roaming\Lens\node_modules\kube-object-event-status\package.json", absolutePath: "C:\Users\jon\AppData\Local\Programs\Lens\resources\extensions\kube-object-event-status", manifestPath: "C:\Users\jon\AppData\Roaming\Lens\node_modules\kube-object-event-status\package.json", manifest: {…}, isBundled: true, …}
```

**Comment by nicolaerosia** [comment]
same issue, any workaround?

**Comment by jakolehm** [comment]
This is most likely caused by a change in #3261  .

**Comment by nicolaerosia** [comment]
fixed, thank you!

**Comment by mjarmoc** [comment]
On ubuntu still not fixed.

**Comment by MartinGolding515** [comment]
What is the workaround for windows?

**Comment by jonstelly** [comment]
5.0.2 fixed this for me, are you on 5.0.2?  If you’re having this issue on 5.0.2 open the dev console (Ctrl+shift+I) and see if there are errors in the console. Paste them here or on a new issue.

**Comment by MartinGolding515** [comment]
First I get error every time i connect to a cluster - it usually works the second time. Then I struggle to get the metrics working, needing to disconnect / close / quit app. Then I find the logs and console buttons are missing. 

![image](https://user-images.githubusercontent.com/70753541/125049325-c504a980-e098-11eb-940e-76da17d0f04e.png)

**Comment by strus38** [comment]
Just tried on Lens 5.0.2, still the same issue:
![image](https://user-images.githubusercontent.com/5890515/125065499-300eaa00-e0b2-11eb-99fe-eaa2904a49b8.png)

![image](https://user-images.githubusercontent.com/5890515/125065641-5c2a2b00-e0b2-11eb-9987-a338ba99c483.png)

![image](https://user-images.githubusercontent.com/5890515/125065676-664c2980-e0b2-11eb-9aed-909094463915.png)

**Comment by unikzforce** [comment]
@strus38 have you tried 5.1.1 latest?

**Comment by strus38** [comment]
Not yet!... Will do in August, can't before.

Le dim. 18 juil. 2021 à 13:54, unikzforce ***@***.***> a
écrit :

**Comment by ottsion** [comment]
i tried all but not work for me, in the end i uninstall all lens and npm, node which installed in my computer, then install lens successfully
it may have some kind of trouble with npm, node you installed before

**Comment by PhilRanzato** [comment]
> i tried all but not work for me, in the end i uninstall all lens and npm, node which installed in my computer, then install lens successfully
> it may have some kind of trouble with npm, node you installed before

For me in windows I had to uninstall all Lens versions installed (somehow I had 3 lens installed with different versions) and after a "fresh" installation of 5.1.3 the logs and exec button are shown as expected

**Comment by strus38** [comment]
It works fine with newer releases.
