### ISSUE TITLE
Crash while loading cluster overview view.

### ISSUE THREAD

**Issue by placer14** [lensapp/lens#3309]
**Describe the bug**
Switched from one cluster (while inspecting a node instance) to another cluster. Recieved this crash while switching. Occurs intermittantly. (Restart allows the Overview to load normally.) Have seen this crash twice.

=== crash details in-app ===
App crash at /events
To help us improve the product please report bugs to Slack community or Github issues tracker.

```
Component stack:


    at virtual_list_VirtualList (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:496164:9)
    at div
    at LogList (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:529464:9)
    at div
    at Logs (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:529896:9)
    at div
    at div
    at Dock (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:530308:9)
    at div
    at div
    at MainLayout (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:475494:9)
    at ErrorBoundary (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:475037:9)
    at Router (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:18291:30)
    at App (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:531386:9)
    at ThemeProvider (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:556003:24)
```

```
Error stack:

 
TypeError: Cannot read property 'resetAfterIndex' of null
    at virtual_list_VirtualList.componentDidUpdate (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:496215:34)
    at Yi (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442399:502)
    at dk (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442439:160)
    at exports.unstable_runWithPriority (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442514:343)
    at gg (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442302:325)
    at Uj (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442432:279)
    at Lj (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442423:371)
    at http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442303:115
    at exports.unstable_runWithPriority (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442514:343)
    at gg (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442302:325)
    at jg (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442303:61)
    at ig (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442302:428)
    at Wj (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:442424:190)
    at reactionScheduler (http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:2536:12)
    at http://a3d00c6b51780c5d5303bef80e905ed2.localhost:52286/build/Lens.js:2537:14
    at Hh (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:306:141185)
```

**To Reproduce**

**Expected behavior**
Normal load of cluster overview.

**Screenshots**
<img width="1440" alt="Screen Shot 2021-07-07 at 3 26 11 PM" src="https://user-images.githubusercontent.com/305332/124817357-b18dfd00-df37-11eb-8651-e180c624d62f.png">

**Environment (please complete the following information):**
Lens: 5.0.0-latest.20210629.3
Electron: 9.4.4
Chrome: 83.0.4103.122
Node: 12.14.1

Install via website download.

**Logs:**
No logs available.

**Kubeconfig:**
Rather not post. Generated using `aws eks update-kubeconfig`. 

**Additional context**
Nothing usual that I can think of.

**Comment by Nokel81** [comment]
fixed by #3230
