### ISSUE TITLE
During lens working the connection kicked out 

### ISSUE THREAD

**Issue by amitzbb** [lensapp/lens#3352]
```
TypeError: Cannot read property 'includes' of undefined
    at parseKubeApi (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:499100:29)
    at api_manager_ApiManager.getApi (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:499757:67)
    at api_manager_ApiManager.resolveApi (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:499776:25)
    at api_manager_ApiManager.getStore (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:499796:43)
    at KubeObjectDetails.get object (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:507041:34)
    at trackDerivedFunction (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1881:18)
    at ComputedValue.computeValue_ (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1657:13)
    at ComputedValue.trackAndCompute (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1637:25)
    at ComputedValue.get (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1608:18)
    at ObservableObjectAdministration.getObservablePropValue_ (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:4787:34)
    at KubeObjectDetails.get (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:5326:26)
    at KubeObjectDetails.render (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:507050:17)
    at allowStateChanges (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1329:12)
    at http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:471735:59
    at trackDerivedFunction (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:1881:18)
    at Reaction.track (http://0b6f898994a6eb9ad758bf90dc359d6f.localhost:50545/build/Lens.js:2409:18)
```

**Comment by jim-docker** [comment]
Hello, can you tell us what you were doing to cause this? (Opened a details page?)

**Comment by amitzbb** [comment]
just happend during work , i was watching pods log
