### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by gdelbergue** [lensapp/lens#3366]
**Describe the bug**

I restarted Lens and window is now stuck on black screen (nothing is showing up in the window). It worked well yesterday and for many weeks. I used v5.0.2. I did try to reinstaller but it didn't fix the issue.

**Expected behavior**
Lens is loading

**Screenshots**

![Screenshot 2021-07-13 at 09 53 03](https://user-images.githubusercontent.com/4040959/125413429-b120f12c-8cc6-4964-a6a9-afb2542575c6.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.2
- OS: macOS 11.4
- Installation method (e.g. snap or AppImage in Linux): Homebrew

**Logs:**

```
 ~  /Applications/Lens.app/Contents/MacOS/Lens ; exit;             ✔  09:47:49 
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
info: 🚀 Starting Lens from "/Users/example/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-user-store.json
2021-07-13 09:47:55.478 Lens[38864:1210137] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 39252 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 39252 was invalidated.}
2021-07-13 09:47:59.404 Lens[38864:1210010] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 39252 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 39252 was invalidated.}
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/lens-weblink-store.json
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:52229
info: 🔎 Testing LensProxy connection ...
info: ⚡ LensProxy connection OK
2021-07-13 09:48:04.776 Lens[38864:1210154] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 39252 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 39252 was invalidated.}
2021-07-13 09:48:09.778 Lens[38864:1210038] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 39252 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 39252 was invalidated.}
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/example/Library/Application Support/Lens
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [EXTENSION-INSTALLER] installing dependencies at /Users/example/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] dependencies installed at /Users/example/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/example/.k8slens/extensions
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info: [STORE]: LOADED from /Users/example/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json
error: [EXTENSIONS-LOADER]: can't load main for "lens-telemetry": TypeError: Cannot create a second singleton while creating a first {"extension":{"id":"/Users/example/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry/lens-telemetry-5.0.2-latest.20210705.2.tgz","manifestPath":"/Users/example/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"5.0.2-latest.20210705.2","description":"Lens IDE telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p && npm pack","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"files":["dist/**/*"],"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","@types/node":"^14.14.14","@types/react":"^17.0.0","@types/universal-analytics":"^0.4.4","analytics-node":"^3.4.0-beta.3","conf":"^7.1.2","jest":"^26.6.3","mobx":"^6.3.2","mobx-react":"^7.1.0","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2","webpack-cli":"^3.3.11"}},"isBundled":true,"isEnabled":true,"isCompatible":true}}
error: [EXTENSION]: failed to activate lens-survey@5.0.2-latest.20210705.2: Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
info: [EXTENSION]: enabled lens-license@5.0.2-latest.20210705.2
[CLUSTER-CONNECT] cluster proxy started on port 52239
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
info: [EXTENSION]: enabled lenscloud-lens-extension@5.0.2-latest.20210705.2
```

**Kubeconfig:**

Checked with a validator, it is valid

**Additional context**

**Comment by gdelbergue** [comment]
After many restarts, it started again. However, I can see Lens is trying to load all files in .kube folder.

```
warn: [KUBECONFIG-SYNC]: failed to start watching changes: Error: ENOENT: no such file or directory, stat '/Users/example/Library/Application Support/Lens/kubeconfigs'
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"/Users/example/.kube"}
warn: [KUBECONFIG-SYNC]: Failed to compute diff: YAMLException: null byte is not allowed in input at line 1, column 1:
    
    ^ {"filePath":"/Users/example/.kube/.DS_Store"}
warn: [KUBECONFIG-SYNC]: encountered errors while loading config: "value" must be of type object {"filePath":"/Users/example/.kube/kubectx","details":[{"message":"\"value\" must be of type object","path":[],"type":"object.base","context":{"type":"object","label":"value","value":"example-prod"}}]}
```

Maybe `.DS_Store` and `kubectx` could be ignored ?

**Comment by Nokel81** [comment]
Hello is this still happening on the latest version (5.1.1)?

As for those files under `~/.kube`, those warnings are expected and those files are just ignored anyway.

**Comment by gdelbergue** [comment]
> Hello is this still happening on the latest version (5.1.1)?
> 
> As for those files under `~/.kube`, those warnings are expected and those files are just ignored anyway.

Yes, reproduced after update to v5.1.2.

**Comment by Nokel81** [comment]
If you open the developer tools once you get the blank window do you see any errors?

**Comment by gdelbergue** [comment]
> If you open the developer tools once you get the blank window do you see any errors?

When I open Developer Tools with black screen, I need to Reload but every time I reload, app crash (it closes). Then I restart and black screen disappears

**Comment by gdelbergue** [comment]
After an update on another computer (running macOS BigSur 11.4), app no longer starts. I cloned repo and started from master. Here is the log:

```
$ nodemon --watch static/build/main.js --exec "electron --remote-debugging-port=9223 --inspect ."
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): static/build/main.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `electron --remote-debugging-port=9223 --inspect .`
Debugger listening on ws://127.0.0.1:9229/9b0d07e4-df4f-47e4-b224-f09dbedf3f6b
For help, see: https://nodejs.org/en/docs/inspector
info: 📟 Setting OpenLens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
SentryError: Attempted to enable Electron native crash reporter but no DSN was supplied
    at new SentryError (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/utils/dist/error.js:9:28)
    at MainBackend.<anonymous> (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/dist/main/backend.js:152:27)
    at step (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/node_modules/tslib/tslib.js:124:57)
    at /Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/node_modules/tslib/tslib.js:113:16)
    at MainBackend._installNativeHandler (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/dist/main/backend.js:146:24)
    at new MainBackend (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/electron/dist/main/backend.js:66:34)
    at MainClient.BaseClient (/Users/guyguy333/Projects/github.com/lensapp/lens/node_modules/@sentry/core/dist/baseclient.js:52:25) {
  name: 'SentryError'
}

DevTools listening on ws://127.0.0.1:9223/devtools/browser/eb447b0a-ef3d-4228-94c3-5a8a807f2999
info: 🚀 Starting OpenLens from "/Users/guyguy333/Library/Application Support/OpenLensDev"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
Running 2.1.0-beta.4 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-user-store.json
Running 5.0.0-alpha.3 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-user-store.json
Running 5.0.3-beta.1 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-user-store.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-user-store.json
2021-07-21 10:48:48.881 Electron[13777:9395652] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 14089 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 14089 was invalidated.}
2021-07-21 10:48:53.130 Electron[13777:9395632] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 14089 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 14089 was invalidated.}
Running 2.0.0-beta.2 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 2.4.1 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 2.6.0-beta.2 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 2.6.0-beta.3 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 2.7.0-beta.0 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 2.7.0-beta.1 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 3.6.0-beta.1 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Number of clusters to migrate:  0
Running 5.0.0-beta.10 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 5.0.0-beta.13 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 5.1.2 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-cluster-store.json
Running 5.0.0-alpha.0 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-hotbar-store.json
Running 5.0.0-alpha.2 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-hotbar-store.json
Running 5.0.0-beta.5 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-hotbar-store.json
Running 5.0.0-beta.10 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-hotbar-store.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-extensions.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-filesystem-provisioner-store.json
Running 5.0.0-alpha.0 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-weblink-store.json
Running 5.0.0-alpha.2 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-weblink-store.json
Running 5.0.0-beta.5 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-weblink-store.json
Running 5.0.0-beta.10 migration for /Users/guyguy333/Library/Application Support/OpenLensDev/lens-weblink-store.json
info: [STORE]: LOADED from /Users/guyguy333/Library/Application Support/OpenLensDev/lens-weblink-store.json
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:50193
info: 🔎 Testing LensProxy connection ...
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: ⚡ LensProxy connection OK
2021-07-21 10:48:58.694 Electron[13777:9395652] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 14089 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 14089 was invalidated.}
2021-07-21 10:49:03.696 Electron[13777:9395652] FinderSync Collaboration: remote proxy error = Error Domain=NSCocoaErrorDomain Code=4099 "The connection on anonymousListener or serviceListener from pid 14089 was invalidated." UserInfo={NSDebugDescription=The connection on anonymousListener or serviceListener from pid 14089 was invalidated.}
info: 🖥️  Starting WindowManager
Skip checkForUpdatesAndNotify because application is not packed
info: 🤓 Installing developer tools
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/guyguy333/Library/Application Support/OpenLensDev
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: APP:ACTIVATE {"hasVisibleWindows":false}
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
[13781:0721/104909.485393:ERROR:gles2_cmd_decoder.cc(18937)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[13781:0721/104909.485435:ERROR:gles2_cmd_decoder.cc(18958)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[13781:0721/104909.485449:ERROR:gles2_cmd_decoder.cc(13783)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[13781:0721/104909.485461:ERROR:gles2_cmd_decoder.cc(18937)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[13781:0721/104909.485474:ERROR:gles2_cmd_decoder.cc(18958)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[13781:0721/104909.485483:ERROR:gles2_cmd_decoder.cc(13783)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[13781:0721/104909.485498:ERROR:gles2_cmd_decoder.cc(18937)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[13781:0721/104909.485508:ERROR:gles2_cmd_decoder.cc(18958)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[13781:0721/104909.485516:ERROR:gles2_cmd_decoder.cc(13783)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[13781:0721/104909.489737:ERROR:gles2_cmd_decoder.cc(18987)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[13781:0721/104909.489761:ERROR:gles2_cmd_decoder.cc(18987)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[13781:0721/104909.489771:ERROR:gles2_cmd_decoder.cc(18987)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
info: [EXTENSION-INSTALLER] installing dependencies at /Users/guyguy333/Library/Application Support/OpenLensDev
info: [EXTENSION-INSTALLER] dependencies installed at /Users/guyguy333/Library/Application Support/OpenLensDev
info: [EXTENSION-INSTALLER] installing package from /Users/guyguy333/.k8slens/extensions/nevalla--kube-resource-map to /Users/guyguy333/Library/Application Support/OpenLensDev
info: [EXTENSION-INSTALLER] package /Users/guyguy333/.k8slens/extensions/nevalla--kube-resource-map installed to /Users/guyguy333/Library/Application Support/OpenLensDev
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/guyguy333/.k8slens/extensions
info: [STORE]: SAVING /Users/guyguy333/Library/Application Support/OpenLensDev/lens-extensions.json
(node:13777) ExtensionLoadWarning: Warnings loading extension at /Users/guyguy333/Library/Application Support/OpenLensDev/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
info: [DEVTOOLS-INSTALLER]: installed React Developer Tools
info: APP:ACTIVATE {"hasVisibleWindows":true}
info: APP:ACTIVATE {"hasVisibleWindows":true}
info: APP:ACTIVATE {"hasVisibleWindows":true}
```

<img width="1429" alt="Screenshot 2021-07-21 at 10 54 03" src="https://user-images.githubusercontent.com/4040959/126460883-d45cf393-c083-460f-b6f1-1e12288fa720.png">

**Comment by alekc** [comment]
Same (or similar thing) for me. 

It's happening after running `brew upgrade lens` from 4 to the 5.x. 

![image](https://user-images.githubusercontent.com/302807/129558409-1300c1c9-cfb2-48f0-b351-2d0eae66a6c2.png)

In my case it looks like it has been caused by the migration of the settings from an older version?

Removing the `/Users/xxx/Library/Application Support/Lens/lens-user-store.json` fixed the issue and the lens has been able to start.

**Comment by radiomistress** [comment]
Ran into this same issue in fedora 34. Solved it with `rm -rf ~/.config/Lens/`

**Comment by Nokel81** [comment]
@alekc That looks like you ran the upgrade while lens was still running. Those migrations shouldn't be run my the renderer.

**Comment by Nokel81** [comment]
@guyguy333 Would you be able to share a screenshot of of the devtools not loading?

**Comment by gdelbergue** [comment]
@Nokel81 I no longer have the issue after a reset of config and I didn't reproduce
