### ISSUE TITLE
Changing npm registry for installing extentions

### ISSUE THREAD

**Issue by iishabakaev** [lensapp/lens#3374]
Lens ver: 5.0.2-latests.20210705.2

I find out that's current registry for installing all extentions is hardcoded:

> export async function attemptInstallByInfo({ name, version, requireConfirmation = false }: ExtensionInfo) {
>   const disposer = ExtensionInstallationStateStore.startPreInstall();
>   const registryUrl = new URLParse("https://registry.npmjs.com").set("pathname", name).toString();

```
{url: "https://registry.npmjs.com/@nevalla/kube-resource-map", err: Error: Client network socket disconnected before secure TLS connection was established
    at connR…}err: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:312:28)
    at TLSSocket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)url: "https://registry.npmjs.com/@nevalla/kube-resource-map"__proto__: Object
Promise.catch (async)
attemptInstallByInfo @ extensions.tsx:304
extensions_installFromInput @ extensions.tsx:452
installFromInput @ extensions.tsx:524
Rb @ react-dom.production.min.js:52
Xb @ react-dom.production.min.js:52
Yb @ react-dom.production.min.js:53
Ze @ react-dom.production.min.js:100
se @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Jb @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Hb @ react-dom.production.min.js:292
gd @ react-dom.production.min.js:73
```

And because of this I can't use this behind a firewall
I want that lens uses my ~/.npmrc configuration file with my local registry

**Comment by Nokel81** [comment]
I think this is a bug because there is a known place to look for an alternative.
