### ISSUE TITLE
Lens fails to start on Linux when /tmp is mounted with noexec flag

### ISSUE THREAD

**Issue by lisenet** [lensapp/lens#3387]
**Describe the bug**
Lens fails to start on Linux when `/tmp` is mounted with `noexec` flag. Such configuration is part of "Best Security Practices" in enterprise environments.

**To Reproduce**
1. `$ sudo mount -o remount,noexec /tmp`
2. Download a Lens .deb package
3. `$ sudo apt install ./Lens-5.0.2-latest.20210705.2.amd64.deb`
4. Start the application:

```
$ lens
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Lens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Lens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.kFZYct: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```

**Expected behavior**
The application starts.

**Environment (please complete the following information):**
- Lens Version: Lens-5.0.2-latest.20210705.2.amd64.deb
- OS: Ubuntu 18.04 LTS
- Installation method: Linux (apt)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Lens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Lens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.kFZYct: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
```

**Comment by Nokel81** [comment]
Does chromium work? And if so do you know what temp folder it uses?

**Comment by lisenet** [comment]
Chromium does work, yes. If I were to guess I'd say that it uses `${HOME}/.cache/chromium`, but I'm not a Chromium developer, therefore take it with a grain of salt. The process creates a lot of files/folders/sockets in various places on the filesystem, however, there is only a single hidden folder under `/tmp` tied to a process ID:

`/tmp/.org.chromium.Chromium.lcV3LB/SingletonSocket`

```
$ mount|grep "/tmp"
/dev/mapper/ubuntu--vg-tmp on /tmp type ext4 (rw,nosuid,nodev,noexec,relatime)
```

**Comment by lisenet** [comment]
I've just tested the latest available release of Lens 5.3.0, it still fails.

**Comment by XMarat** [comment]
I have same problem on debian 6

**Comment by lisenet** [comment]
@XMarat have you got `/tmp` mounted with `noexec` flag on your Debian box?
