### ISSUE TITLE
No install/uninstall button for Metrics after upgrade to v5

### ISSUE THREAD

**Issue by petermicuch** [lensapp/lens#3467]
**Describe the bug**
There is not install/uninstall button for Metric in the cluster settings after upgrade from v4 to v5. If cluster had metrics installed, you can see them, but you can not uninstall. If cluster did not have metrics, you can not actually install it using Lens as before.

**To Reproduce**
1. Right click cluster icon and select 'Settings'
2. Click on 'Metrics'
3. There is no option to install metrics stack using Lens. Only to select metrics you want to hide.

**Expected behavior**
Install button shall be visible in case, there are no metrics installed, or uninstall, in case metrics were installed using Lens.

**Environment (please complete the following information):**
- Lens Version: 5.1.2-latest.20210719.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Win installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: ≡ƒôƒ Setting Lens as protocol client for lens://
info: ≡ƒôƒ Protocol client register succeeded Γ£à
info: ≡ƒÜÇ Starting Lens from "C:\Users\test\AppData\Roaming\Lens"
info: ≡ƒÉÜ Syncing shell environment
info: ≡ƒÆ╛ Loading stores
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-user-store.json
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-hotbar-store.json
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-extensions.json
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
info: [STORE]: LOADED from C:\Users\test\AppData\Roaming\Lens\lens-weblink-store.json
info: ≡ƒöî Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at 127.0.0.1:1129
info: ≡ƒöÄ Testing LensProxy connection ...
info: ΓÜí LensProxy connection OK
info: ≡ƒûÑ∩╕Å  Starting WindowManager
info: ≡ƒº⌐ Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from C:\Users\test\AppData\Roaming\Lens
info: [EXTENSION-INSTALLER] installing dependencies at C:\Users\test\AppData\Roaming\Lens
info: [WINDOW-MANAGER]:┬áLoading Main window from url: http://localhost:1129 ...
info: [KUBECONFIG-SYNC]: starting requested syncs
info: ≡ƒôí Checking for app updates
info: Checking for update
warn: [KUBECONFIG-SYNC]: failed to start watching changes: Error: ENOENT: no such file or directory, stat 'C:\Users\test\AppData\Roaming\Lens\kubeconfigs'
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"C:\\Users\\test\\.kube"}
info: [WINDOW-MANAGER]: Main window loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: Update for version 5.1.2-latest.20210719.1 is not available (latest version: 5.1.2-latest.20210719.1, downgrade is disallowed).
Error: npm ERR! code E404
npm ERR! 404 Not Found - GET https://pkgs.dev.azure.com/shsds/_packaging/aipc_npm_nuget%40Local/npm/registry/react-open-doodles - NotFound
npm ERR! 404
npm ERR! 404  'react-open-doodles@^1.0.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'example-extension'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\test\npm-cache\_logs\2021-07-21T09_16_30_837Z-debug.log

    at ChildProcess.<anonymous> (C:\Users\test\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:205192)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Trace
    at App.<anonymous> (C:\Users\test\AppData\Local\Programs\kontena-lens\resources\app.asar\static\build\main.js:1:257521)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
info: [CLUSTER]: activate {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:681e3692df51ca8c64d1c82ab770a1d6" {"data":"Authentication proxy started\n","meta":{"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":false,"accessible":false,"disconnected":true}}
error: Failed to connect cluster "aks": StatusCodeError: 404 - "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
info: [CLUSTER]: activate {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":true,"accessible":false,"disconnected":false}
info: [CLUSTER]: reconnect {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":true,"accessible":false,"disconnected":false}
info: [KUBE-AUTH]: out-channel "kube-auth:681e3692df51ca8c64d1c82ab770a1d6" {"data":"Authentication proxy started\n","meta":{"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":false,"online":true,"accessible":false,"disconnected":false}}
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
info: [STORE]: SAVING C:\Users\test\AppData\Roaming\Lens\lens-cluster-store.json
(node:21844) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info: [CLUSTER]: refresh {"id":"681e3692df51ca8c64d1c82ab770a1d6","name":"aks","ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Comment by petermicuch** [comment]
The npm error that you see is there because lens is using `.npmrc` settings from my home directory, which was not the case before I guess, as I have not seen such error before migrating to v5. But even when I comment out mu `.npmrc` file and the error is gone, the install/uninstall option is missing.

**Comment by petermicuch** [comment]
Oh my, this functionality was moved to `Extensions` tab out of the settings. My bad.
