### ISSUE TITLE
Proxy errors logged after cluster is disconnected

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#3472]
**Describe the bug**
Proxy errors are logged after a cluster is disconnected. This seems to happen consistently on Windows, I have seen it occasionally on mac. Lens shouldn't be trying to "watch" the cluster after it has been disconnected so this shouldn't impact Lens behaviour, but the abundance of error messages will flood Sentry once #3432 is released. Maybe there is a race condition?

**To Reproduce**
1. Connect to a cluster
2. Disconnect from the cluster
3. Observe flood of proxy errors

**Environment (please complete the following information):**
- Lens Version: 5.1.2
- OS: Windows consistently

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [CLUSTER]: disconnect {"id":"ff1772e62d280e1e04026551b61e4f4e","name":"docker-desktop","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: unbind events {"id":"ff1772e62d280e1e04026551b61e4f4e","name":"docker-desktop","ready":true,"online":true,"accessible":true,"disconnected":false}
debug: [KUBE-AUTH]: stopping local proxy {"id":"ff1772e62d280e1e04026551b61e4f4e","name":"docker-desktop","ready":true,"online":true,"accessible":true,"disconnected":false}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/apps/v1/daemonsets?watch=1&resourceVersion=201208"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/apps/v1/replicasets?watch=1&resourceVersion=201210"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/events?watch=1&resourceVersion=201211"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/pods?watch=1&resourceVersion=201199"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/batch/v1beta1/cronjobs?watch=1&resourceVersion=201211"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/namespaces?watch=1&resourceVersion=201199"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/batch/v1/jobs?watch=1&resourceVersion=201211"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/nodes?watch=1&resourceVersion=201199"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/apps/v1/deployments?watch=1&resourceVersion=201208"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/events?watch=1&resourceVersion=201199"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/namespaces?watch=1&resourceVersion=201199"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/events?watch=1&resourceVersion=201208"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/pods?watch=1&resourceVersion=201208"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/apis/apps/v1/statefulsets?watch=1&resourceVersion=201209"}
debug: Failed proxy to target: {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "127.0.0.1:62505",
  "port": "62505",
  "hostname": "127.0.0.1",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/",
  "path": "/",
  "href": "http://127.0.0.1:62505/"
}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:118029)\n    at ProxyServer.emit (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\jiim\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}

```

**Comment by Nokel81** [comment]
I indeed this this is a race condition. Because the kube-auth-proxy server gets shut down before the cluster state update is pushed to the renderer which then will delete the iframe and navigate away.
