### ISSUE TITLE
Crash at opening new cluster

### ISSUE THREAD

**Issue by ivanmatmati** [lensapp/lens#3514]
**Describe the bug**
Got an error message at cluster opening.

**To Reproduce**
I created a cluster with :
`kind create cluster --name=clusterb`
Without checking if the cluster was finished being created I opened it.

**Environment (please complete the following information):**
- Lens Version: 4.0.2
- OS: Manjaro Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
Error stack:

TypeError: Cannot read property 'kind' of undefined
    at r.value (http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:3775674)
    at http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:8680652
    at Array.map (<anonymous>)
    at http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:8680620
    at Array.map (<anonymous>)
    at r.value (http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:8680564)
    at r.value (http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:8685912)
    at ve (http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:18448)
    at http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:70625
    at ce (http://1175acc1-c90f-4ff6-93c2-90631d4fa464.localhost:38937/build/Lens.js:2:16554)

Component stack:
    in r
    in aside
    in div
    in r
    in r
    in t
    in Unknown
    in r

The error message reappears every time I try to (re)open the cluster.

**Comment by Nokel81** [comment]
This has been fixed between your version and the current version (5.1.3).
