### ISSUE TITLE
Error invoking remote method 'cluster:activate'

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#3552]
**Describe the bug**

```
Error invoking remote method 'cluster:activate': TypeError: Cannot read property 'length' of undefined
```

**To Reproduce**
1. Click a cluster in catalog
2. See error

<img width="887" alt="Screenshot 2021-08-02 at 14 20 16" src="https://user-images.githubusercontent.com/1474479/127853873-087dcd5f-ae56-4e16-b5a2-465b1ec77b17.png">

**Expected behavior**

No crash

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
[0] info: [STORE]: SAVING /Users/hchen/Library/Application Support/OpenLensDev/lens-cluster-store.json
[0] (node:36043) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
[0]     at Cluster.eval (webpack-internal:///./src/main/cluster.ts:454:37)
[0]     at Generator.next (<anonymous>)
[0]     at eval (webpack-internal:///./src/main/cluster.ts:72:61)
[0]     at new Promise (<anonymous>)
[0]     at __async (webpack-internal:///./src/main/cluster.ts:56:10)
[0]     at Cluster.getAllowedNamespaces (webpack-internal:///./src/main/cluster.ts:453:12)
[0]     at Cluster.eval (webpack-internal:///./src/main/cluster.ts:319:43)
[0]     at Generator.next (<anonymous>)
[0]     at eval (webpack-internal:///./src/main/cluster.ts:72:61)
[0]     at new Promise (<anonymous>)
[0] (node:36043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[0] (node:36043) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] Error occurred in handler for 'cluster:activate': TypeError: Cannot read property 'length' of undefined
[0]     at Cluster.eval (webpack-internal:///./src/main/cluster.ts:454:37)
[0]     at Generator.next (<anonymous>)
[0]     at eval (webpack-internal:///./src/main/cluster.ts:72:61)
[0]     at new Promise (<anonymous>)
[0]     at __async (webpack-internal:///./src/main/cluster.ts:56:10)
[0]     at Cluster.getAllowedNamespaces (webpack-internal:///./src/main/cluster.ts:453:12)
[0]     at Cluster.eval (webpack-internal:///./src/main/cluster.ts:319:43)
[0]     at Generator.next (<anonymous>)
[0]     at eval (webpack-internal:///./src/main/cluster.ts:72:61)
[0]     at new Promise (<anonymous>)
```

**Comment by chenhunghan** [comment]
Ah. already fixed https://github.com/lensapp/lens/commit/ad865023688374f1151f34af1b367188c30d3a0b
