### ISSUE TITLE
Unable to launch: GPU process isn't usable

### ISSUE THREAD

**Issue by turowicz** [lensapp/lens#3760]
Ubuntu 21.10 with NVIDIA driver 470.63.01 getting the following error:

```
$ ./lens 
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +7ms
info:    ▪ 🚀 Starting Lens from "/opt/Lens/lens" +51ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ▪ 💾 Loading stores +48ms
info:    ▪ [KS]: LOADED from /home/wojtek/.config/Lens/lens-user-store.json +17ms
info:    ▪ [GA]: LOADED from /home/wojtek/.config/Lens/lens-cluster-store.json +4ms
info:    ▪ [UU]: LOADED from /home/wojtek/.config/Lens/lens-hotbar-store.json +2ms
info:    ▪ [YT]: LOADED from /home/wojtek/.config/Lens/lens-extensions.json +1ms
info:    ▪ [QC]: LOADED from /home/wojtek/.config/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ [EI]: LOADED from /home/wojtek/.config/Lens/lens-weblink-store.json +3ms
info:    ▪ 🔌 Starting LensProxy +13ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:39293 +4ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ ⚡ LensProxy connection OK +92ms
info:    ▪ 🖥️  Starting WindowManager +2ms
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ 🧩 Initializing extensions +22ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/wojtek/.config/Lens +1ms
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /home/wojtek/.config/Lens +82ms
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /home/wojtek/.config/Lens +475ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /home/wojtek/.k8slens/extensions +1ms
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info:    ▪ [C]: LOADED from /home/wojtek/.config/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json +48ms
info:    ▪ [C]: LOADED from /home/wojtek/.config/Lens/extension-store/lens-survey/preferences-store.json +2ms
telemetry main extension activated
info:    ▪ [N]: LOADED from /home/wojtek/.config/Lens/extension-store/lens-telemetry/preferences-store.json +35ms
info:    ┏ [IPC-RENDERER]: adding extension listener +75ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'loadRemoteSpacesClusters',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'leaveOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ▪ [EXTENSION]: enabled lens-license@5.2.0-latest.20210908.1 +17ms
info:    ▪ [EXTENSION]: enabled lens-survey@5.2.0-latest.20210908.1 +4ms
info:    ▪ [EXTENSION]: enabled lens-telemetry@5.2.0-latest.20210908.1 +0ms
[CLUSTER-CONNECT] cluster proxy started on port 36329
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
info:    ▪ [EXTENSION]: enabled lenscloud-lens-extension@5.2.0-latest.20210908.1 +13ms
[14047:0909/093000.192380:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Failed to generate minidump.Illegal instruction (core dumped)
```

**Comment by turowicz** [comment]
Prime Profile

![image](https://user-images.githubusercontent.com/1055391/132643860-d92bac1f-beba-40f2-a2f3-b8c7213f22c2.png)

**Comment by turowicz** [comment]
Thats Lens 5.2.x from .deb. The one from snap (4.x) works fine. But it's an older version...

**Comment by Nokel81** [comment]
Would you be able to set the following env var's to `true` and run Lens again from the command line?

    ELECTRON_ENABLE_LOGGING

    ELECTRON_DEBUG_NOTIFICATIONS

    ELECTRON_ENABLE_STACK_DUMPING

**Comment by turowicz** [comment]
@Nokel81 
```
ELECTRON_ENABLE_LOGGING=true ELECTRON_DEBUG_NOTIFICATIONS=true ELECTRON_ENABLE_STACK_DUMPING=true lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +8ms
[2595432:0913/154039.023578:ERROR:file_path_watcher_linux.cc(316)] inotify_init() failed: Too many open files (24)
info:    ▪ 🚀 Starting Lens from "/opt/Lens/lens" +55ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ▪ 💾 Loading stores +37ms
info:    ▪ [KS]: LOADED from /home/wojtek/.config/Lens/lens-user-store.json +14ms
info:    ▪ [GA]: LOADED from /home/wojtek/.config/Lens/lens-cluster-store.json +2ms
info:    ▪ [UU]: LOADED from /home/wojtek/.config/Lens/lens-hotbar-store.json +2ms
info:    ▪ [YT]: LOADED from /home/wojtek/.config/Lens/lens-extensions.json +1ms
info:    ▪ [QC]: LOADED from /home/wojtek/.config/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ [EI]: LOADED from /home/wojtek/.config/Lens/lens-weblink-store.json +3ms
info:    ▪ 🔌 Starting LensProxy +9ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:37033 +2ms
info:    ▪ 🔎 Testing LensProxy connection ... +2ms
info:    ▪ ⚡ LensProxy connection OK +95ms
info:    ▪ 🖥️  Starting WindowManager +1ms
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ 🧩 Initializing extensions +25ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/wojtek/.config/Lens +1ms
[2595432:0913/154039.242817:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 1 time(s)
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /home/wojtek/.config/Lens +81ms
[2595432:0913/154039.454218:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 2 time(s)
[2595432:0913/154039.625475:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 3 time(s)
[2595432:0913/154039.729983:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 4 time(s)
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /home/wojtek/.config/Lens +488ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /home/wojtek/.k8slens/extensions +1ms
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
[2595432:0913/154039.834382:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 5 time(s)
Lens Cloud Extension activated
info:    ▪ [C]: LOADED from /home/wojtek/.config/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json +43ms
info:    ▪ [C]: LOADED from /home/wojtek/.config/Lens/extension-store/lens-survey/preferences-store.json +2ms
telemetry main extension activated
info:    ▪ [N]: LOADED from /home/wojtek/.config/Lens/extension-store/lens-telemetry/preferences-store.json +28ms
info:    ┏ [IPC-RENDERER]: adding extension listener +57ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +2ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'loadRemoteSpacesClusters',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'leaveOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.2.0-latest.20210908.1' }
info:    ┗ [4] }
[2595432:0913/154039.932099:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 6 time(s)
info:    ▪ [EXTENSION]: enabled lens-license@5.2.0-latest.20210908.1 +16ms
info:    ▪ [EXTENSION]: enabled lens-survey@5.2.0-latest.20210908.1 +5ms
info:    ▪ [EXTENSION]: enabled lens-telemetry@5.2.0-latest.20210908.1 +1ms
[CLUSTER-CONNECT] cluster proxy started on port 34157
[CLUSTER-CONNECT] cluster proxy is using aes-256-gcm for end-to-end encryption
info:    ▪ [EXTENSION]: enabled lenscloud-lens-extension@5.2.0-latest.20210908.1 +16ms
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: EMFILE: too many open files, watch '/home/wojtek/.k8slens/extensions'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/opt/Lens/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/Lens/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/Lens/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/opt/Lens/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:559:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async NodeFsHandler._addToNodeFs (/opt/Lens/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:609:16)
    at async /opt/Lens/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
[2595432:0913/154040.027540:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 7 time(s)
[2595432:0913/154040.117376:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 8 time(s)
[2595432:0913/154040.203422:WARNING:gpu_process_host.cc(1283)] The GPU process has crashed 9 time(s)
[2595432:0913/154040.203456:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Failed to generate minidump.Received signal 4 ILL_ILLOPN 558e20704818
#0 0x558e22e773b9 (/opt/Lens/lens+0x43473b8)
  r8: 000000000000006c  r9: 0000000000000000 r10: 00000d1294969deb r11: 0000000000000293
 r12: 00007f73fff56410 r13: aaaaaaaaaaaaaaaa r14: 00007f73fff56430 r15: 00007f73fff56880
  di: 0000558e26ccc5b8  si: 0000000000000000  bp: 00007f73fff56870  bx: 00007f73fff56898
  dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000000  sp: 00007f73fff56360
  ip: 0000558e20704818 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by turowicz** [comment]
seems to work now
