### ISSUE TITLE
got error on ide

### ISSUE THREAD

**Issue by lemanlai** [lensapp/lens#3762]
1. lens version: 5.2.0
2. env: mac 11.5.2 intel i7
3. kube/config:  there contexts
4. error:
  - 4.1:  Component stack:
```
Component stack:


    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:7000:16
    at div
    at div
    at div
    at InfoPanel (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:540141:9)
    at div
    at Logs (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:542162:9)
    at div
    at div
    at Dock (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:542574:9)
    at div
    at div
    at MainLayout (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:488171:9)
    at ErrorBoundary (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:487632:47)
    at ErrorBoundary (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:487741:36)
    at Router (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:20003:30)
    at App (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:543653:9)
    at ThemeProvider (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:568366:24)
```
   - 4.2: Error stack:
```
Error stack:

 
TypeError: Cannot read property 'namespace' of undefined
    at pods_api_Pod.getNs (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:512082:30)
    at pods_api_Pod.getOwnerRefs (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:512113:32)
    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:541401:30
    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:7000:49
    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:6964:25
    at trackDerivedFunction (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:1881:18)
    at Reaction.track (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:2409:18)
    at useObserver (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:6962:14)
    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:7000:16
    at Ch (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450238:137)
    at li (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450261:154)
    at ki (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450259:169)
    at ii (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450258:178)
    at ck (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450355:126)
    at bk (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450331:347)
    at ak (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450331:278)
    at Tj (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450331:138)
    at Lj (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450324:163)
    at Jg (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450318:175)
    at lk (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450366:27)
    at http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450370:301
    at Xj (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450325:244)
    at tk (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450370:287)
    at exports.render (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:450377:69)
    at bootstrap (http://2289fccbc122286241a62dd8564232ee.localhost:49991/build/Lens.js:578519:32)
```

5. more
  I have three contexts. OK for other two. Error on this one for only 2 days. It was ok before. After reinstall Lens.  error still .

**Comment by Nokel81** [comment]
duplicate of https://github.com/lensapp/lens/issues/3543
