### ISSUE TITLE
App crash at /pods: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by europ** [lensapp/lens#3781]
#### Summary
```txt
App crash at /pods
```

#### How to reproduce
1. Connect to a cluster
1. Go to: Workloads > Pods
1. Kill a running pod: three dots on the right > remove

#### Component Stack
```console
    at KubeObjectDetails (http://####.localhost:50433/build/Lens.js:506847:9)
    at ErrorBoundary (http://####.localhost:50433/build/Lens.js:474940:9)
    at Router (http://####.localhost:50433/build/Lens.js:18291:30)
    at App (http://####.localhost:50433/build/Lens.js:531289:9)
    at ThemeProvider (http://####.localhost:50433/build/Lens.js:555906:24)
```

#### Error Stack
```console
TypeError: Cannot read property 'includes' of undefined
    at parseKubeApi (http://####.localhost:50433/build/Lens.js:498955:29)
    at api_manager_ApiManager.getApi (http://####.localhost:50433/build/Lens.js:499612:67)
    at api_manager_ApiManager.resolveApi (http://####.localhost:50433/build/Lens.js:499631:25)
    at api_manager_ApiManager.getStore (http://####.localhost:50433/build/Lens.js:499651:43)
    at KubeObjectDetails.get object (http://####.localhost:50433/build/Lens.js:506896:34)
    at trackDerivedFunction (http://####.localhost:50433/build/Lens.js:1881:18)
    at ComputedValue.computeValue_ (http://####.localhost:50433/build/Lens.js:1657:13)
    at ComputedValue.trackAndCompute (http://####.localhost:50433/build/Lens.js:1637:25)
    at ComputedValue.get (http://####.localhost:50433/build/Lens.js:1608:18)
    at ObservableObjectAdministration.getObservablePropValue_ (http://####.localhost:50433/build/Lens.js:4787:34)
    at KubeObjectDetails.get (http://####.localhost:50433/build/Lens.js:5326:26)
    at KubeObjectDetails.render (http://####.localhost:50433/build/Lens.js:506905:17)
    at allowStateChanges (http://####.localhost:50433/build/Lens.js:1329:12)
    at http://####.localhost:50433/build/Lens.js:471614:59
    at trackDerivedFunction (http://####.localhost:50433/build/Lens.js:1881:18)
    at Reaction.track (http://####.localhost:50433/build/Lens.js:2409:18)
```

#### Environment
* Lens: 5.0.0-latest.20210629.3
* Electron: 9.4.4
* Chrome: 83.0.4103.122
* Node: 12.14.1
* OS: Windows 10 Pro
* Installation method: Installed via downloaded binary (.exe) from https://k8slens.dev/
    * some upgrades were already performed

**Comment by Nokel81** [comment]
Is this still an issue when using 5.2.0? And if it is, would you be able to run Lens from the command line with `DEBUG` set to true?

**Comment by europ** [comment]
I have upgraded my LENS to `5.2.0-latest.20210908.1`, no crash occurred yet.

In case of crash, I will try to reproduce it with set `DEBUG=true` and attach the information into this issue.

**Comment by jakolehm** [comment]
This seems to be fixed.
