### ISSUE TITLE
App crash at /cluster

### ISSUE THREAD

**Issue by corelix** [lensapp/lens#4143]
**Describe the bug**
##### Component stack:
```
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:9707:16
    at div
    at div
    at div
    at InfoPanel (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:662832:9)
    at div
    at Logs (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:664857:9)
    at div
    at div
    at Dock (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:665269:9)
    at div
    at div
    at MainLayout (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:572754:9)
    at ErrorBoundary (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:572215:47)
    at ErrorBoundary (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:572324:36)
    at Router (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:32134:30)
    at App (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:666495:9)
    at ThemeProvider (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:700171:24)
```
##### Error stack
```
TypeError: Cannot read property 'namespace' of undefined
    at pods_api_Pod.getNs (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:588921:30)
    at pods_api_Pod.getOwnerRefs (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:588952:32)
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:664096:30
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:9707:49
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:9671:25
    at trackDerivedFunction (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:2024:18)
    at Reaction.track (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:2552:18)
    at useObserver (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:9669:14)
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:9707:16
    at Ch (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535650:137)
    at li (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535673:154)
    at ki (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535671:169)
    at ii (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535670:178)
    at ck (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535767:126)
    at bk (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535743:347)
    at ak (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535743:278)
    at Tj (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535743:138)
    at Lj (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535736:163)
    at Jg (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535730:175)
    at lk (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535778:27)
    at http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535782:301
    at Xj (http://b88e7eb40bc3464155c25c9369e8c969.localhost:49236/build/Lens.js:535737:244)
```
**To Reproduce**
1. Click on the connection in the hotbar
2. See error

**Expected behavior**
See dashboard

**Screenshots**
<img width="1426" alt="Screenshot 2021-10-26 at 20 17 10" src="https://user-images.githubusercontent.com/59166948/138928685-3760f083-4256-4dc3-9d4d-4132d34184de.png">

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: OSX Big Sur 11.6 
- Installation method (e.g. snap or AppImage in Linux):

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3942
