### ISSUE TITLE
App crash at /daemonsets

### ISSUE THREAD

**Issue by jayaramcloud** [lensapp/lens#4174]
App crash at /daemonsets
To help us improve the product please report bugs to Slack community or GitHub issues tracker.

Component stack:

    at MonacoEditor (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:107661:28)
    at EditorPanel (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:662590:9)
    at div
    at CreateResource (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:662897:9)
    at div
    at div
    at Dock (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:665167:9)
    at div
    at div
    at MainLayout (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:572652:9)
    at ErrorBoundary (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:572113:47)
    at ErrorBoundary (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:572222:36)
    at Router (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:32134:30)
    at App (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:666393:9)
    at ThemeProvider (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:700069:24)
Error stack:

 
TypeError: Cannot read property 'toString' of undefined
    at MODEL_ID (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:195195:21)
    at ModelServiceImpl.getModel (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:195507:25)
    at Object.getModel (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:85070:65)
    at MonacoModelsManager.getModel (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:116806:90)
    at Object.value [as editorDidMount] (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:662616:83)
    at MonacoEditor.editorDidMount (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:107738:20)
    at MonacoEditor.initMonaco (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:107728:18)
    at MonacoEditor.componentDidMount (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:107669:14)
    at Yi (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535712:411)
    at dk (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535752:160)
    at exports.unstable_runWithPriority (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535827:343)
    at gg (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535615:325)
    at Uj (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535745:279)
    at Lj (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535736:371)
    at http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535616:115
    at exports.unstable_runWithPriority (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535827:343)
    at gg (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535615:325)
    at jg (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535616:61)
    at ig (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535615:428)
    at Wj (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:535737:190)
    at reactionScheduler (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:2679:12)
    at http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:2680:14
    at Gh (C:\Users\jkrishnaswamy\AppData\Local\Programs\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:347:141185)
    at reactionScheduler (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:2679:12)
    at runReactions (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:2648:3)
    at endBatch (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:2315:5)
    at _endAction (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:1461:3)
    at executeAction (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:1414:5)
    at storageHelper_StorageHelper.merge (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:1393:12)
    at value (http://82563dbd779c452d64269e55f5c09692.localhost:52534/build/Lens.js:7191:26)

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3972
