### ISSUE TITLE
Cannot create a string longer than 0x3fffffe7 characters

### ISSUE THREAD

**Issue by servo1x** [lensapp/lens#451]
**Describe the bug**

Leaving lens open and idle, eventually results in an alert window message about not being able to create a string.

**To Reproduce**

1. Leave lens open and idle
2. Alert window eventually pops up with this message

**Expected behavior**

Does not seem to break the app after clicking ok, seems like this error could be logged to console and not be raised as an alert window.

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): OSX installer.
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

```javascript
// A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot create a string longer than 0x3fffffe7 characters
    at Buffer.utf8Slice (<anonymous>)
    at stringSlice (buffer.js:569:42)
    at Buffer.toString (buffer.js:643:10)
    at Request.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request/request.js:1135:39)
    at Request.emit (events.js:205:15)
    at IncomingMessage.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by servo1x** [comment]
Not seeing this issue anymore on 3.5.

**Comment by HristoA** [comment]
Hi.
I face the same issue few times past week.

![image](https://user-images.githubusercontent.com/20325836/99236948-8156ea00-2800-11eb-8373-132e49f2bccb.png)
![image](https://user-images.githubusercontent.com/20325836/99236982-8caa1580-2800-11eb-896b-cc478507064d.png)

**Comment by HristoA** [comment]
Still exist in 3.6.9

**Comment by jakolehm** [comment]
This sounds like a memory leak.

**Comment by HristoA** [comment]
On version 4.0 still exist. Any way to give additional debug info?
![image](https://user-images.githubusercontent.com/20325836/101625462-1cb83500-3a24-11eb-9cdd-5d0d6af60820.png)
![image](https://user-images.githubusercontent.com/20325836/101625369-f7c3c200-3a23-11eb-958b-beaf21153774.png)
