### ISSUE TITLE
Metric not working, error "found duplicate series for the match group"

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#5006]
**Describe the bug**
This bug may be related to https://github.com/lensapp/lens/issues/4962, but my initial position is different. Feel free to mark it as duplicate if appropriate. 

Metrics are not working in lens when using loki-stack. I tried all available settings in metrics.

**To Reproduce**

Unsure. I have a cluster with [loki-stack](https://grafana.com/docs/loki/latest/installation/helm/) installed. As you can see from the log output, I actually have to kafka-clusters, running in two different namespaces. I suspect that having two pods with identical names in two namespaces somehow breaks the grouping or aggregation in your queries.

**Expected behavior**
Metric should work.

**Environment (please complete the following information):**
- Lens Version: 5.4.1-latest.20220304.1
- OS: Windows 10

**Logs:**
```
error:   ÔöÅ [Metrics]: metrics not available +10s
error:   Ôöâ [1] {
error:   Ôöâ [2]   status: 'error',
error:   Ôöâ [3]   errorType: 'execution',
error:   Ôöâ [4]   error: 'found duplicate series for the match group {namespace="monitoring", pod="kafka-cluster-kafka-0"} on the right hand-side of the operation: <SEE BELOW FOR JSON> ;many-to-many matching not allowed: matching labels must be unique on one side'
error:   Ôöù [5] }
warn:    ÔöÅ [METRICS-ROUTE]: failed to get metrics for clusterId=3892b60b3f773fb3724cab2fa52b0269: Metrics not available +1ms
warn:    Ôöâ [1] Error: Metrics not available
warn:    Ôöâ [2]     at C:\Users\schrom\AppData\Local\Programs\Lens\resources\app.asar\static\build\main.js:1:264542
warn:    Ôöâ [3]     at runMicrotasks (<anonymous>)
warn:    Ôöâ [4]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
warn:    Ôöâ [5]     at async Promise.all (index 0)
warn:    Ôöâ [6]     at async Object.routeMetrics [as route] (C:\Users\schrom\AppData\Local\Programs\Lens\resources\app.asar\static\build\main.js:1:265213)
warn:    Ôöù [7]     at async X.route (C:\Users\schrom\AppData\Local\Programs\Lens\resources\app.asar\static\build\main.js:1:276073)

```

Here is the well formatted <SEE BELOW FOR JSON> part from the log:
```
[{
        __name__ = "kube_pod_info",
        app_kubernetes_io_component = "metrics",
        app_kubernetes_io_instance = "loki",
        app_kubernetes_io_managed_by = "Helm",
        app_kubernetes_io_name = "kube-state-metrics",
        app_kubernetes_io_part_of = "kube-state-metrics",
        app_kubernetes_io_version = "2.2.4",
        created_by_kind = "StatefulSet",
        created_by_name = "kafka-cluster-kafka",
        exported_namespace = "kafka-dev",
        exported_node = "pool1-77b658cf4d-q77t5",
        helm_sh_chart = "kube-state-metrics-4.0.2",
        host_ip = "192.168.1.160",
        host_network = "false",
        instance = "10.244.3.152:8080",
        job = "kubernetes-service-endpoints",
        namespace = "monitoring",
        node = "pool1-77b658cf4d-c9c2q",
        pod = "kafka-cluster-kafka-0",
        pod_ip = "10.244.7.31",
        service = "loki-kube-state-metrics",
        uid = "a8582bc7-3d48-4a1a-b816-f7039d0e981b"
    }, {
        __name__ = "kube_pod_info",
        app_kubernetes_io_component = "metrics",
        app_kubernetes_io_instance = "loki",
        app_kubernetes_io_managed_by = "Helm",
        app_kubernetes_io_name = "kube-state-metrics",
        app_kubernetes_io_part_of = "kube-state-metrics",
        app_kubernetes_io_version = "2.2.4",
        created_by_kind = "StatefulSet",
        created_by_name = "kafka-cluster-kafka",
        exported_namespace = "e2e",
        exported_node = "pool1-77b658cf4d-q77t5",
        helm_sh_chart = "kube-state-metrics-4.0.2",
        host_ip = "192.168.1.160",
        host_network = "false",
        instance = "10.244.3.152:8080",
        job = "kubernetes-service-endpoints",
        namespace = "monitoring",
        node = "pool1-77b658cf4d-c9c2q",
        pod = "kafka-cluster-kafka-0",
        pod_ip = "10.244.7.88",
        service = "loki-kube-state-metrics",
        uid = "82818e2e-c23e-4710-b01d-3fd6a854ce3c"
    }
]
```

**Additional context**

Metrics format is manually set to "Prometheus Operator" as suggested in another issue adressing recent changes in property names in prometheus helm chart V15 ("kubernetes_node" becoming "node" etc).

**Comment by ondrej-smola** [comment]
Same here, i think it is related to running Thanos/HA Prometheus setup. After rolling update/failover of persistent prometheus instances this issue happens. In my case it only affects cluster view, other metrics are displayed correctly ... errors is always 'found duplicate series for the match group ...' . Maybe added 'replica' label to deduplicate series may be causing this. We have Loki installed also but it does not seems to be related to loki itself IMHO. Tested also with 5.5.1.

**Comment by rhyswilliamsza** [comment]
Experiencing the same whenever the node exporter daemonsets are recreated with new names. Is it possible it's caused by the 'pod' name changing?

![image](https://github.com/lensapp/lens/assets/14295288/b6830c3b-e24b-4d07-a62e-61889870420d)

**Comment by alex-ioma** [comment]
Hi there, this is still an issue. Is there a plan for a fix?
