### ISSUE TITLE
Integration tests that require minikube are skipped on Linux

### ISSUE THREAD

**Issue by nevalla** [lensapp/lens#522]
**Describe the bug**
Integration tests that require Minikube are skipped on Linux CICD pipeline despite minikube should be available

**Expected behavior**
Test should not be skipped
 
**Logs:**
```
 minikube not running, skipping test

      49 |     const status = spawnSync("minikube status", {shell: true})
      50 |     if (status.status !== 0) {
    > 51 |       console.warn("minikube not running, skipping test")
         |               ^
      52 |       return
      53 |     }
      54 |     await clickWhatsNew(app)

      at Object.<anonymous> (spec/integration/specs/app_spec.ts:51:15)

  console.warn
    minikube not running, skipping test

      62 |     const status = spawnSync("minikube status", {shell: true})
      63 |     if (status.status !== 0) {
    > 64 |       console.warn("minikube not running, skipping test")
         |               ^
      65 |       return
      66 |     }
      67 |     await clickWhatsNew(app)

      at Object.<anonymous> (spec/integration/specs/app_spec.ts:64:15)
```

**Comment by jim-docker** [comment]
`minikube status` fails with:
```
X Error getting cluster config: stat: stat /home/vsts/.minikube/profiles/minikube/config.json: permission denied
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

Fix waiting for after vue/react refactor: https://github.com/jim-docker/lens/commit/60ae2d60da4cfe4edfd1ef619dd0dfa14c1e5055

**Comment by jim-docker** [comment]
Tests now fail for different reason:
```
 ● app start › allows to add a cluster

    : Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error:

      50 |   })
      51 | 
    > 52 |   it('allows to add a cluster', async () => {
         |   ^
      53 |     const status = spawnSync("minikube status", {shell: true})
      54 |     if (status.status !== 0) {
      55 |       console.warn("minikube not running, skipping test")

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (integration/specs/app_spec.ts:52:3)

  ● app start › allows to add a cluster

    waitUntilTextExists Promise was rejected with the following reason: timeoutError: Promise was rejected with the following reason: timeout

      at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at node_modules/webdriverio/build/lib/commands/waitUntil.js:36:15
```
