### ISSUE TITLE
App Doesn't start on Linux

### ISSUE THREAD

**Issue by arash-bizcover** [lensapp/lens#544]
**Describe the bug**
Application Doesn't start (in my case Ubuntu 18.04)

**To Reproduce**
```
chmod a+x Lens-3.5.1-rc.1.AppImage
./Lens-3.5.1-rc.1.AppImage
```

**Expected behavior**
App to start 

```
No screenhost - deosn't start
```

**Environment (please complete the following information):**
- Lens Version: 3.5.1-rc.1
- OS: Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage in Linux
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
(node:28121) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at parseEnv (/tmp/.mount_Lens-3teD3wu/resources/app.asar/node_modules/shell-env/index.js:15:35)
    at AsyncFunction.module.exports.sync (/tmp/.mount_Lens-3teD3wu/resources/app.asar/node_modules/shell-env/index.js:47:10)
    at Object.t.shellSync (/tmp/.mount_Lens-3teD3wu/resources/app.asar/webpack:/src/main/shell-sync.ts:15:1)
    at App.<anonymous> (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:323068)
    at /tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:322362
    at Object.next (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:322467)
    at /tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:321380
    at new Promise (<anonymous>)
    at n (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:321128)
    at App.protocol (/tmp/.mount_Lens-3teD3wu/resources/app.asar/webpack:/src/main/index.ts:32:3)
    at App.emit (events.js:205:15)
(node:28121) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at parseEnv (/tmp/.mount_Lens-3teD3wu/resources/app.asar/node_modules/shell-env/index.js:15:35)
    at AsyncFunction.module.exports.sync (/tmp/.mount_Lens-3teD3wu/resources/app.asar/node_modules/shell-env/index.js:47:10)
    at Object.t.shellSync (/tmp/.mount_Lens-3teD3wu/resources/app.asar/webpack:/src/main/shell-sync.ts:15:1)
    at App.<anonymous> (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:323068)
    at /tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:322362
    at Object.next (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:322467)
    at /tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:321380
    at new Promise (<anonymous>)
    at n (/tmp/.mount_Lens-3teD3wu/resources/app.asar/main.js:1:321128)
    at App.protocol (/tmp/.mount_Lens-3teD3wu/resources/app.asar/webpack:/src/main/index.ts:32:3)
    at App.emit (events.js:205:15)
(node:28121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by hreidar** [comment]
Same here for me. Has been working for a few months and then stopped after an update. In this update, the lunch icon did change.

**Comment by hreidar** [comment]
Hi, any news on this. Is it possible to revert back to a working version? Snap only shows this broken 3.5.1

**Comment by WyriHaximus** [comment]
Having older versions on snap would be highly appreciated!

**Comment by hreidar** [comment]
env DISABLE_WAYLAND=1 kontena-lens

(process:1023018): Gtk-WARNING **: 20:17:54.714: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 20:17:54.714: Failed to load module "appmenu-gtk-module"
CLUSTER STORE, MIGRATION: 2.6.0-beta.3
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. YAMLException: end of the stream or a document separator is expected at line 1, column 16:
    [object Object],[object Object],[object Object]
                   ^
    at ElectronStore._migrate (/snap/kontena-lens/108/resources/app.asar/node_modules/conf/index.js:159:11)
    at new Conf (/snap/kontena-lens/108/resources/app.asar/node_modules/conf/index.js:121:9)
    at new ElectronStore (/snap/kontena-lens/108/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at new e (/snap/kontena-lens/108/resources/app.asar/webpack:/src/common/cluster-store.ts:7:1)
    at Function.workspace [as getInstance] (/snap/kontena-lens/108/resources/app.asar/webpack:/src/common/cluster-store.ts:95:41)
    at Object.resetInstance (/snap/kontena-lens/108/resources/app.asar/webpack:/src/common/cluster-store.ts:106:10)
    at r (/snap/kontena-lens/108/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/108/resources/app.asar/webpack:/src/main/index.ts:2:1)
    at r (/snap/kontena-lens/108/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/108/resources/app.asar/webpack:/src/main/feature.ts:102:39)
    at r (/snap/kontena-lens/108/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at object (/snap/kontena-lens/108/resources/app.asar/webpack:/webpack/bootstrap:76:36)
    at Object.<anonymous> (/snap/kontena-lens/108/resources/app.asar/webpack:/webpack/bootstrap:76:56)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

**Comment by hreidar** [comment]
The above command is working on latest debian, not on Ubuntu 20.04

**Comment by hreidar** [comment]
Please give us older working versions in snap

**Comment by nevalla** [comment]
https://github.com/lensapp/lens/pull/630 probably fixes this.

**Comment by hreidar** [comment]
ok, will test when 3.5.2 enters snap repo

**Comment by nevalla** [comment]
3.5.2 is now out containing a fix for this. Please re-open if this is still an issue.

**Comment by hreidar** [comment]
Hi @nevalla , the app does not lunch a GUI on Ubuntu 20.04 after updating and I still see the following error using a trick that fixes that problem on Debian.

```
hreidar@thinkpad-t480s:~$ env DISABLE_WAYLAND=1 kontena-lens

(process:467756): Gtk-WARNING **: 10:50:28.900: Locale not supported by C library.
	Using the fallback 'C' locale.
CLUSTER STORE, MIGRATION: 2.6.0-beta.3
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. YAMLException: end of the stream or a document separator is expected at line 1, column 16:
    [object Object],[object Object],[object Object]
                   ^
    at ElectronStore._migrate (/snap/kontena-lens/109/resources/app.asar/node_modules/conf/index.js:159:11)
    at new Conf (/snap/kontena-lens/109/resources/app.asar/node_modules/conf/index.js:121:9)
    at new ElectronStore (/snap/kontena-lens/109/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at new e (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:7:1)
    at Function.workspace [as getInstance] (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:95:41)
    at Object.resetInstance (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:106:10)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/src/main/index.ts:2:1)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/src/main/feature.ts:102:39)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at object (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:76:36)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:76:56)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

^Z
[1]+  Stopped                 env DISABLE_WAYLAND=1 kontena-lens
hreidar@thinkpad-t480s:~$ 
hreidar@thinkpad-t480s:~$ snap info kontena-lens
name:      kontena-lens
summary:   Lens - The Kubernetes IDE
publisher: Lakend Labs Inc (jakolehm)
store-url: https://snapcraft.io/kontena-lens
contact:   info@lakendlabs.com
license:   unset
description: |
  Lens is the most powerful IDE for people who need to deal with Kubernetes clusters on a daily
  basis. Ensure your clusters are properly setup and configured. Enjoy increased visibility, real
  time statistics, log streams and hands-on troubleshooting capabilities. With Lens, you can work
  with your clusters more easily and fast, radically improving productivity and the speed of
  business.
commands:
  - kontena-lens
snap-id:      Dek6y5mTEPxhySFKPB4Z0WVi5EPS9osS
tracking:     latest/stable
refresh-date: today at 10:45 GMT
channels:
  latest/stable:    3.5.2 2020-08-06 (109) 88MB classic
  latest/candidate: 3.5.1 2020-07-02 (108) 88MB classic
  latest/beta:      3.5.1 2020-07-02 (108) 88MB classic
  latest/edge:      3.5.2 2020-08-06 (109) 88MB classic
installed:          3.5.2            (109) 88MB classic
```

**Comment by hreidar** [comment]
@nevalla, I notice that you are talking about 3.5.3, I don't see that in my snap repo at this time

**Comment by arash-bizcover** [comment]
Issue for me was fixed on 3.5.2. (_got from snap edge_)

What is weird is the app starts a default terminal (bash) and gets executed upon that. I have a wrapper on my terminal (bashrc) which causes problem for the app to run.

**Comment by hreidar** [comment]
where are the app logs located, anyone knows that so I can post debug logs?

**Comment by hreidar** [comment]
@arash-bizcover which distro/version are you using?

**Comment by arash-bizcover** [comment]
@hreidar I tested on my local ubuntu 18.04 as well as a new 20.04(on vm)

**Comment by hreidar** [comment]
ok, I'm using a recent install on Ubuntu 20.04 and I have not, to my knowledge, changed anything. The app worked at one time before some upgrade but I have no idea why things broke

**Comment by hreidar** [comment]
Hi, I managed to lunch the GUI by running ```sudo kontena-lens``` from terminal. The app does not lunch GUI if I double click the lunch icon.

**Comment by nevalla** [comment]
> @nevalla, I notice that you are talking about 3.5.3, I don't see that in my snap repo at this time

Sorry...I meant `3.5.2`

**Comment by arash-bizcover** [comment]
ah damn!
I ran the app as root and it corrupted my root folders .....

```
# kontena-lens 
/root/Desktop was removed, reassigning DESKTOP to homedir
/root/Downloads was removed, reassigning DOWNLOAD to homedir
/root/Templates was removed, reassigning TEMPLATES to homedir
/root/Public was removed, reassigning PUBLICSHARE to homedir
/root/Documents was removed, reassigning DOCUMENTS to homedir
/root/Music was removed, reassigning MUSIC to homedir
/root/Pictures was removed, reassigning PICTURES to homedir
/root/Videos was removed, reassigning VIDEOS to homedir
```

**Comment by nevalla** [comment]
@hreidar, this indicates that your issue is somehow related to cluster store migration:
```
CLUSTER STORE, MIGRATION: 2.6.0-beta.3
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. YAMLException: end of the stream or a document separator is expected at line 1, column 16:
    [object Object],[object Object],[object Object]
                   ^
    at ElectronStore._migrate (/snap/kontena-lens/109/resources/app.asar/node_modules/conf/index.js:159:11)
    at new Conf (/snap/kontena-lens/109/resources/app.asar/node_modules/conf/index.js:121:9)
    at new ElectronStore (/snap/kontena-lens/109/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at new e (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:7:1)
    at Function.workspace [as getInstance] (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:95:41)
    at Object.resetInstance (/snap/kontena-lens/109/resources/app.asar/webpack:/src/common/cluster-store.ts:106:10)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/src/main/index.ts:2:1)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/src/main/feature.ts:102:39)
    at r (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:9:5)
    at object (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:76:36)
    at Object.<anonymous> (/snap/kontena-lens/109/resources/app.asar/webpack:/webpack/bootstrap:76:56)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

^Z
[1]+  Stopped                 env DISABLE_WAYLAND=1 kontena-lens
```
Need to investigate that a bit further.

**Comment by nevalla** [comment]
> ah damn!
> I ran the app as root and it corrupted my root folders .....
> 
> ```
> # kontena-lens 
> /root/Desktop was removed, reassigning DESKTOP to homedir
> /root/Downloads was removed, reassigning DOWNLOAD to homedir
> /root/Templates was removed, reassigning TEMPLATES to homedir
> /root/Public was removed, reassigning PUBLICSHARE to homedir
> /root/Documents was removed, reassigning DOCUMENTS to homedir
> /root/Music was removed, reassigning MUSIC to homedir
> /root/Pictures was removed, reassigning PICTURES to homedir
> /root/Videos was removed, reassigning VIDEOS to homedir
> ```
> 
> why is this app developed like this 😞

Ouch. That logic is coming outside of Lens. Perhaps Snap(?) is doing that?

**Comment by arash-bizcover** [comment]
Yes I apologise, it was not Lens.
It was this damn Snapd!

**Comment by nevalla** [comment]
@hreidar If possible, please could you remove `~/.config/Lens/lens-cluster-store.json` and start from fresh. After that you have to re-add your clusters to Lens.

**Comment by hreidar** [comment]
@nevalla I do not have any ```~/.config/Lens/lens-cluster-store.json``` on my machine. I did remove the app and add it again at some point when I was debugging. Now it seems that I'm unable to start it from the command line using ```sudo kontena-lens``` as I managed to do yesterday.

**Comment by webwurst** [comment]
I am seeing the same issue:
```
> snap list kontena-lens
Name          Version  Rev  Tracking       Publisher  Notes
kontena-lens  3.5.2    109  latest/stable  jakolehm   classic

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

> kontena-lens

(process:110958): Gtk-WARNING **: 15:16:21.299: Locale not supported by C library.
	Using the fallback 'C' locale.

(kontena-lens:110958): Gtk-WARNING **: 15:16:21.299: cannot open display: :0
```

On the same system `Lens-3.5.2.AppImage` seems to work fine for me.

**Comment by hreidar** [comment]
same here, the AppImage of Lens-3.5.2 works

**Comment by nox-404** [comment]
Hello there:

I ran into the same issue using master branch...
The issue seems to be that the reference to the electron app is undefined:

https://github.com/lensapp/lens/blob/master/src/migrations/cluster-store/3.6.0-beta.1.ts#L12

To be able to start the app anyway on linux, set this in the store:

\- $HOME/.config/LensDev/lens-cluster-store.json
```
{
	"__internal__": {
		"migrations": {
			"version": "3.6.0-beta.1"
		}
	}
}
```

You'll still get some store errors but it starts anyway (skips the migration)

**Comment by nox-404** [comment]
Another solution for me was to delete  the LensDev & Lens config directories...

**Comment by nevalla** [comment]
I'm closing this now, since the original issue is already solved. Lens 3.6.0 is out now. Please open new issue with new details if this is still issue there.
