### ISSUE TITLE
Can not see Lens at Desktop

### ISSUE THREAD

**Issue by NICK-DUAN** [lensapp/lens#791]
When I opened the software on the macbook pro, I saw the welcome interface with a progress bar, and when the progress bar was completed, I couldn't see the Lens window.
When I click "Show all windows" in the Dock, a blue box will be displayed. I suspect this is the location of the software, but it cannot be displayed.
I asked Apple's customer service, and I tried all the methods they said, but only the new account is valid. But I don’t want to change my account.
Please help me take a look at my problem. Lens has helped me improve my work efficiency. I feel bad without Lens.

The blue box like this:
![企业微信截图_a61569d5-6a04-4825-a243-52ea8650672e](https://tvax4.sinaimg.cn/large/d44de8e1gy1gicm308v6jj22t20wq7wn.jpg)

**Comment by NICK-DUAN** [comment]
anyone here?

**Comment by NICK-DUAN** [comment]
@jakolehm @nevalla

**Comment by nevalla** [comment]
if you open the app from the command line `/Applications/Lens.app/Contents/MacOS/Lens`, do you see any errors?

**Comment by NICK-DUAN** [comment]
```
➜  ~ /Applications/Lens.app/Contents/MacOS/Lens
info: [IPC]: setup channel "cluster:init"
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/Users/nickduan/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":false}
info: [CLUSTER]: "cls-j76dvbbm-context-default" init success {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","context":"cls-j76dvbbm-context-default","apiUrl":"https://cls-j76dvbbm.ccs.tencent-cloud.com"}
info: [CLUSTER-MANAGER]: init cluster {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":false}
info: [CLUSTER]: "cls-c658w16c-context-default" init success {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","context":"cls-c658w16c-context-default","apiUrl":"https://cls-c658w16c.ccs.tencent-cloud.com"}
info: LensProxy server has started at http://localhost:55243

error: ENOENT: no such file or directory, open '/Users/nickduan/.kube/config' {"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/nickduan/.kube/config"}

info: Update for version 3.6.0-rc.2 is not available (latest version: 3.6.0-rc.2, downgrade is disallowed).
info: Closing proxy server
info: [CLUSTER]: disconnect {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":true}
info: [CLUSTER]: unbind events {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":true}
info: [CLUSTER]: disconnect {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":true}
info: [CLUSTER]: unbind events {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":true}
```

But it doesn't seem that this error is a problem that the software can't display on the desktop.

Then I copy my cluster kubeconfig to this path, But it's only the wrong hour, and the problem is still there.

**Comment by NICK-DUAN** [comment]
> ```
> ➜  ~ /Applications/Lens.app/Contents/MacOS/Lens
> info: [IPC]: setup channel "cluster:init"
> info: [IPC]: setup channel "cluster:activate"
> info: [IPC]: setup channel "cluster:disconnect"
> info: [IPC]: setup channel "cluster:install-feature"
> info: [IPC]: setup channel "cluster:uninstall-feature"
> info: [IPC]: setup channel "cluster:upgrade-feature"
> info: 🚀 Starting Lens from "/Users/nickduan/Library/Application Support/Lens"
> info: Checking for update
> info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/config.json
> info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/lens-cluster-store.json
> info: [STORE]: LOADED from /Users/nickduan/Library/Application Support/Lens/lens-workspace-store.json
> info: [CLUSTER-MANAGER]: init cluster {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":false}
> info: [CLUSTER]: "cls-j76dvbbm-context-default" init success {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","context":"cls-j76dvbbm-context-default","apiUrl":"https://cls-j76dvbbm.ccs.tencent-cloud.com"}
> info: [CLUSTER-MANAGER]: init cluster {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":false}
> info: [CLUSTER]: "cls-c658w16c-context-default" init success {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","context":"cls-c658w16c-context-default","apiUrl":"https://cls-c658w16c.ccs.tencent-cloud.com"}
> info: LensProxy server has started at http://localhost:55243
> 
> error: ENOENT: no such file or directory, open '/Users/nickduan/.kube/config' {"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/nickduan/.kube/config"}
> 
> info: Update for version 3.6.0-rc.2 is not available (latest version: 3.6.0-rc.2, downgrade is disallowed).
> info: Closing proxy server
> info: [CLUSTER]: disconnect {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":true}
> info: [CLUSTER]: unbind events {"id":"e9453608-7081-4d1d-af7f-a2a0ec4001a1","name":"cls-j76dvbbm-context-default","initialized":true}
> info: [CLUSTER]: disconnect {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":true}
> info: [CLUSTER]: unbind events {"id":"1cd0d201-8808-45e4-b7d9-9a77c5c919c2","name":"cls-c658w16c-context-default","initialized":true}
> ```
> 
> But it doesn't seem that this error is a problem that the software can't display on the desktop.
> 
> Then I copy my cluster kubeconfig to this path, But it's only the wrong hour, and the problem is still there.

@nevalla By the way, this test I'm using the 3.6.0-rc.2 version.

**Comment by anthonymag** [comment]
Hi! I am experiencing the same issue.

I open the app, and the loading splash screen shows. But then it disappears and I don't see anything else. I don't have that blue window though that @NICK-DUAN mentioned.

The background processes are running:
```
~ ⌚ 15:33:23
$ ps aux | grep Lens
anthony.magalhaes 43535   0.0  0.0  4268300    688 s000  R+    3:33PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Lens
anthony.magalhaes 40437   0.0  0.9  5983424 153756 s001  S+    3:28PM   0:02.32 /Applications/Lens.app/Contents/Frameworks/Lens Helper (Renderer).app/Contents/MacOS/Lens Helper (Renderer) --type=renderer --field-trial-handle=1718379636,2736161848648406958,16668266884709797469,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=en-US --app-path=/Applications/Lens.app/Contents/Resources/app.asar --node-integration --webview-tag --no-sandbox --no-zygote --background-color=#1e2124 --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --service-request-channel-token=12006816265601829498 --renderer-client-id=6 --no-v8-untrusted-code-mitigations
anthony.magalhaes 40322   0.0  0.3  4638152  54536 s001  S+    3:28PM   0:01.14 /Applications/Lens.app/Contents/Frameworks/Lens Helper (GPU).app/Contents/MacOS/Lens Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,2736161848648406958,16668266884709797469,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --gpu-preferences=IAAAAAAAAAAgAAAAAAAAAAAAYAAAAAAACAAAAAAAAAAIAQAAIAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAAMABAAAAAAAAyAEAAAAAAADQAQAAAAAAANgBAAAAAAAA4AEAAAAAAADoAQAAAAAAAPABAAAAAAAA+AEAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAAAAAAcAAAAQAAAAAAAAAAAAAAAIAAAAEAAAAAAAAAAAAAAACgAAABAAAAAAAAAAAAAAAAsAAAAQAAAAAAAAAAAAAAANAAAAEAAAAAAAAAAAAAAADgAAABAAAAAAAAAAAQAAAAAAAAAQAAAAAAAAAAEAAAAGAAAAEAAAAAAAAAABAAAABwAAABAAAAAAAAAAAQAAAAgAAAAQAAAAAAAAAAEAAAAKAAAAEAAAAAAAAAABAAAACwAAABAAAAAAAAAAAQAAAA0AAAAQAAAAAAAAAAEAAAAOAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABAAAAA4AAAAQAAAAAAAAAAYAAAAAAAAAEAAAAAAAAAAGAAAABgAAABAAAAAAAAAABgAAAAcAAAAQAAAAAAAAAAYAAAAIAAAAEAAAAAAAAAAGAAAACgAAABAAAAAAAAAABgAAAAsAAAAQAAAAAAAAAAYAAAANAAAAEAAAAAAAAAAGAAAADgAAAA== --service-request-channel-token=4978236281365158107
```

If I launch from the command line, I don't see anything particularly useful either
```
$ /Applications/Lens.app/Contents/MacOS/Lens --help
info: Checking for update
info: Update for version 3.5.3 is not available (latest version: 3.5.3, downgrade is disallowed).
```

I am macOS Catalina 10.15.5 if that means anything.

**Comment by NICK-DUAN** [comment]
@anthonymag Right-click Lens on the dock, select "Show All Windows", and then shake your mouse on the desktop. You can see that a blue window appears. You can try to reproduce the same problem like this.

**Comment by NICK-DUAN** [comment]
Is there a solution?

**Comment by anthonymag** [comment]
Hi again, has there been any progress here? I haven't been able to use Lens for months. This issue is still persisting for me, even after reinstalling. I do now see the blue window the @NICK-DUAN mentioned before.

```
$ /Applications/Lens.app/Contents/MacOS/Lens
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/Users/anthony.magalhaes/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/anthony.magalhaes/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/anthony.magalhaes/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/anthony.magalhaes/Library/Application Support/Lens/lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"1c498e26-8c65-427b-b2c6-c4fc0a7416c0","name":"arn:aws:eks:us-east-1:262024835551:cluster/git-en-boite-antmag","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "arn:aws:eks:us-east-1:262024835551:cluster/git-en-boite-antmag" init success {"id":"1c498e26-8c65-427b-b2c6-c4fc0a7416c0","context":"arn:aws:eks:us-east-1:262024835551:cluster/git-en-boite-antmag","apiUrl":"https://6F5D91034CA8ED34C8B9CF69DE0D8631.yl4.us-east-1.eks.amazonaws.com"}
info: LensProxy server has started at http://localhost:64697
info: Update for version 3.6.9 is not available (latest version: 3.6.9, downgrade is disallowed).
[22373:1123/145721.889851:ERROR:gles2_cmd_decoder.cc(18937)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[22373:1123/145721.889914:ERROR:gles2_cmd_decoder.cc(18958)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[22373:1123/145721.889934:ERROR:gles2_cmd_decoder.cc(13783)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[22373:1123/145721.889957:ERROR:gles2_cmd_decoder.cc(18937)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[22373:1123/145721.889972:ERROR:gles2_cmd_decoder.cc(18958)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[22373:1123/145721.890012:ERROR:gles2_cmd_decoder.cc(13783)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[22373:1123/145721.892025:ERROR:gles2_cmd_decoder.cc(18987)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[22373:1123/145721.892063:ERROR:gles2_cmd_decoder.cc(18987)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
```

**Comment by anthonymag** [comment]
Interesting, I just tried again as root and it worked
```
$ sudo /Applications/Lens.app/Contents/MacOS/Lens
Password:
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/var/root/Library/Application Support/Lens"
info: Checking for update
STORE MIGRATION (/var/root/Library/Application Support/Lens/config.json): 2.1.0-beta.4
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/config.json
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.0.0-beta.2
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.4.1
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.6.0-beta.2
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.6.0-beta.3
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.7.0-beta.0
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 2.7.0-beta.1
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 3.6.0-beta.1
STORE MIGRATION (/var/root/Library/Application Support/Lens/lens-cluster-store.json): 3.6.9
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-workspace-store.json
info: LensProxy server has started at http://localhost:64817
info: Generated new staging user ID: 62037622-2cd3-5dfb-8571-3ad6f67d6ff3
error: Error: Error: net::ERR_CERT_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
(node:24814) UnhandledPromiseRejectionWarning: Error: net::ERR_CERT_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
(node:24814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24814) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: [STORE]: SAVING config.json
```

Are my permissions wrong for the application?

**Comment by miskun** [comment]
This is weird. Are you having some kind of enterprise policies / settings for your Mac?

**Comment by anthonymag** [comment]
It's a company computer but the settings are very lax and I've never had an issue with another app.

**Comment by miskun** [comment]
There is nothing in Lens to my knowledge that would require sudo. We'll need to take closer look what could potentially cause this. All maintainers are now 100% busy with upcoming 4.0 release but I hope we can get somebody to investigate this issue after 4.0 is shipping. IT MIGHT be fixed in 4.0 too as we are updating underlying Electron (just by looking at this, might be Electron related issue too).

**Comment by NICK-DUAN** [comment]
Hi, @anthonymag. I know what the hell the blue box is, it's your `Lens`, but for some reason, it suddenly became a very small window, use the mouse to find the small window, and expand. You can see `Lens` app.

I hope it worked for you.

**Comment by anthonymag** [comment]
No luck here unfortunately :( 
I can't minimize it either with Command+M

I tried ajusting the resolution and the blue box stays the same size always
![2020-11-24_10-20-35 (2)](https://user-images.githubusercontent.com/29254374/100114584-930f4180-2e3f-11eb-88de-a6469074fa05.gif)

**Comment by anthonymag** [comment]
I logged out of my session and in with another Mac user, and the app launches normally, so I think it's related to some dependency permissions on my own account.

**Comment by Nokel81** [comment]
Is this still an issue?

**Comment by anthonymag** [comment]
I no longer have that computer so I can't check, and don't have the issue on my newer computer. It never resolved while I had it though.

**Comment by Nokel81** [comment]
Okay thanks, I think I'll close this and if someone runs into it again they can open a new issue. Thanks for the update.

**Comment by sag1** [comment]
Hello I am facing the same issue on Mac Big sur. I launched via `sudo /Applications/Lens.app/Contents/MacOS/Lens`

```
info: 🚀 Starting Lens from "/var/root/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: 🔑 Getting free port for LensProxy server
info: [CLUSTER-MANAGER]: init cluster {"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","name":"sentry-integration@k8s-pr","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: 🔌 Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at http://localhost:49886
info: 🔎 Testing LensProxy connection ...
info: [CLUSTER]: "sentry-integration@k8s-pr" init success {"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","context":"sentry-integration@k8s-pr","apiUrl":"https://x.x.x.x:6443"}
info: ⚡ LensProxy connection OK
info: 🖥️  Starting WindowManager
info: 🧩 Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from /var/root/Library/Application Support/Lens
info: [EXTENSION-INSTALLER] installing dependencies at /var/root/Library/Application Support/Lens
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:49886 ...
info: [EXTENSION-INSTALLER] dependencies installed at /var/root/Library/Application Support/Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/saintange/.k8slens/extensions
info: [EXTENSION]: enabled lens-license@0.1.0
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
info: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from /var/root/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [CLUSTER]: activate {"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","name":"sentry-integration@k8s-pr","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","name":"sentry-integration@k8s-pr","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","name":"sentry-integration@k8s-pr","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:b2a412a6-1d73-451a-99e2-5bd4d097d3b4" {"data":"Authentication proxy started\n","meta":{"id":"b2a412a6-1d73-451a-99e2-5bd4d097d3b4","name":"sentry-integration@k8s-pr","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: Downloading kubectl 1.17.17 from https://storage.googleapis.com/kubernetes-release/release/v1.17.17/bin/darwin/amd64/kubectl to /var/root/Library/Application Support/Lens/binaries/kubectl/1.17.17/kubectl
error: connect ECONNREFUSED 216.58.213.80:443 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"216.58.213.80","port":443}
error: connect ECONNREFUSED 216.58.213.80:443 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"216.58.213.80","port":443}
(node:2324) UnhandledPromiseRejectionWarning: Error: Lock is already released
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:257:60
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/adapter.js:39:9
    at new Promise (<anonymous>)
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/adapter.js:30:25
    at /Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:66322
(node:2324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:2324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: [WINDOW-MANAGER]: Main window loaded
info: 📡 Checking for app updates
info: Checking for update
error: Error: Error: net::ERR_CERT_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
error: [UPDATE-CHECKER]: failed with an error {"error":"Error: net::ERR_CERT_INVALID"}
```

**Comment by sag1** [comment]
@Nokel81 Can you reopen the ticket ? I can test if any solution

**Comment by Nokel81** [comment]
Do you have a malware detector? It is probably related to #2390

**Comment by sag1** [comment]
No. I don't have malware detector
