### ISSUE TITLE
App crash at /replicasets

### ISSUE THREAD

**Issue by DevJoyOps** [lensapp/lens#7950]
**Describe the bug**
App crash at /replicasets
Only with "raw" Replicasets.
It doesn't affect if the Replicaset is created by a Deployment.

**To Reproduce**
1. Create a new Replicaset.
2. Open Replicaset detail.

**Expected behavior**
- See the replicaset detail

**Environment:**
- OS: Windows 10
- Lens: 2023.9.290703-latest

**Logs:**
```
Component stack:

    at Details (C:\Users\auser\AppData\Local\Programs\Lens\resources\app.asar\node_modules\@lensapp\shipa-lens-extension\dist\renderer.js:81774:102)
    at div
    at div
    at div
    at NonInjectedAnimate (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:652346:13)
    at NonInjectedDrawer (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:150035:9)
    at observerComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352042:16)
    at ObserverComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352090:23)
    at NonInjectedErrorBoundary (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:658765:9)
    at observerComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352042:16)
    at ObserverComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352090:23)
    at observerComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352042:16)
    at NonInjectedKeyboardShortcutListener (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:664815:48)
    at ThemeProvider (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:227296:24)
    at https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:126768:28
    at Router (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:583997:30)
    at https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:126768:28
    at observerComponent (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:352042:16)


Error stack:

TypeError: Cannot read properties of undefined (reading 'uid')
    at ApplicationStore.getApplicationFromReplicaSet (C:\Users\auser\AppData\Local\Programs\Lens\resources\app.asar\node_modules\@lensapp\shipa-lens-extension\dist\renderer.js:77652:58)
    at Details (C:\Users\auser\AppData\Local\Programs\Lens\resources\app.asar\node_modules\@lensapp\shipa-lens-extension\dist\renderer.js:81774:67)
    at Ch (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582516:137)
    at ck (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582626:460)
    at bk (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582609:347)
    at ak (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582609:278)
    at Tj (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582609:138)
    at Lj (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582602:163)
    at https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:582482:115
    at exports.unstable_runWithPriority (https://86fd21fa0a1acff9a9332f9e7edab66b.lens.app:52791/build/lens.js?b4b4cb4e679b779d31c2:606334:343)

```

**Additional context**
- Microk8s running on remote server
- Kubectl working without any problem

**Comment by hecnavsanz** [comment]
same here .. same message when creating replicaset manually or using template. It happens to me in MacOS 13.6 (22G120) (Intel) and Windows 11 (22H2) with version: Lens-2023.9.290703-latest. Then there's no way to go back and try to access other resources, when trying to access any cluster the error above is displayed.

**Comment by panuhorsmalahti** [comment]
`v2023.10.122002-latest` contains fix for this.
