### ISSUE TITLE
Node network metrics unavailable, but all other metrics are

### ISSUE THREAD

**Issue by jalaziz** [lensapp/lens#8027]
**Describe the bug**

When inspecting metrics for a node, the "Network" tab appears to be broken. All other metrics (CPU, memory, and disk) are available.  Network metrics are also available for pods. The issue seems specifics to nodes.

**To Reproduce**
1. Go to 'Node'
2. Click on any node instance
3. Click on the "Network" icon in the "Metrics" section
4. See missing metrics

**Expected behavior**

I should see transmit and receive network metrics as I do for pods.

**Screenshots**

Node Network Metrics:

![Screenshot by Dropbox Capture](https://github.com/lensapp/lens/assets/247849/65b7acfe-5efd-4e66-8a38-6d4fe637024e)

Node Memory Metrics:

![Screenshot by Dropbox Capture](https://github.com/lensapp/lens/assets/247849/fa85008a-1f99-4d20-967a-09fb12527475)

**Environment (please complete the following information):**
- Lens Version: 2024.1.300751-latest
- OS: macOS 14.3.1
- Installation method: Homebrew
- Prometheus provider: Operator

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
2024-03-02 23:08:46.285 Lens[76197:151326887] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
info:    ▪ [LENS-EXTENSIONS]: LOADING ... +0ms
info:    ▪ [LENS-EXTENSIONS]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-extensions.json +1ms
info:    ▪ Starting v2024.1.300751-latest of Lens... +1ms
info:    ▪ 🔌 Starting LensProxy +8ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:52277 +3ms
info:    ▪ 🔎 Testing LensProxy connection ... +0ms
info:    ▪ [LENS-USER-STORE]: LOADING ... +39ms
info:    ▪ [LENS-USER-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-user-store.json +1ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADING ... +1ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-cluster-store.json +2ms
info:    ▪ ⚡ LensProxy connection OK +5ms
info:    ▪ 📟 Setting protocol client for lens:// +13ms
info:    ▪ 📟 Protocol client register succeeded ✅ +0ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADING ... +1ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-filesystem-provisioner-store.json +0ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ┏ [UNIX-SHELL-ENV]: running against /opt/homebrew/bin/zsh +1ms
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/Applications/Lens.app/Contents/MacOS/Lens' -p '"175e3d3fa7184d39a74e3bd689d5ebaa" + JSON.stringify(process.env) + "175e3d3fa7184d39a74e3bd689d5ebaa"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
info:    ▪ [LENS-WEBLINK-STORE]: LOADING ... +0ms
info:    ▪ [LENS-WEBLINK-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-weblink-store.json +1ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /Applications/Lens.app/Contents/Resources/app.asar/static/splash.html... +65ms
info:    ▪ [LENS-HOTBAR-STORE]: LOADING ... +7ms
info:    ▪ [LENS-HOTBAR-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-hotbar-store.json +1ms
info:    ▪ [LENS-TABLE-STORE]: LOADING ... +0ms
info:    ▪ [LENS-TABLE-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/lens-table-store.json +3ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +73ms
info:    ▪ [SHELL-SYNC]: Synced shell env +438ms
info:    ▪ 🧩 Initializing extensions +1ms
info:    ▪ [EXTENSIONS-LOADER]: auto initializing extensions +0ms
info:    ▪ [LENS-DESKTOP-KUBE] onActivate +295ms
info:    ▪ [LDK-STORE]: LOADING ... +1ms
info:    ▪ [LDK-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lens-desktop-kube-lens-extension/ldk-store.json +0ms
License main extension activated
info:    ▪ [SECURITY-PREFERENCES-STORE]: LOADING ... +1ms
info:    ▪ [SECURITY-PREFERENCES-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/oci-image-lens-extension/security-preferences-store.json +0ms
info:    ▪ [LENS-APPS] Main activated +1ms
info:    ▪ [SUPPORT-EXTENSION] activated +0ms
info:    ▪ [PREFERENCES-STORE]: LOADING ... +0ms
info:    ▪ [PREFERENCES-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/survey-lens-extension/preferences-store.json +1ms
info:    ▪ [TOUR-EXTENSION] activated +0ms
info:    ▪ [TIP-STORE]: LOADING ... +0ms
info:    ▪ [TIP-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/tour-lens-extension/tip-store.json +0ms
info:    ▪ [CLOUD-PROVIDER-SYNC-EXTENSION] activated +1ms
info:    ▪ [LENS-DESKTOP-KUBE] extracting virtual machine runtime files ... +6ms
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.273Z - startup-store ~ ElectronSyncStore:initialize, path /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/startup-store.json
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.274Z - startup-store ~ ElectronSyncStore:initialize, model {"skipSignup":false}
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.274Z - startup-store ~ ipcListen
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.274Z - select-space-store ~ ElectronSyncStore:initialize, path /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/select-space-store.json
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.274Z - select-space-store ~ ElectronSyncStore:initialize, model {"543e2154-bc1b-44cd-8590-d5a90693e829":{"spaceId":"offline","isPersonalSpace":true,"spaceName":"offline"}}
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:47.274Z - select-space-store ~ ipcListen
telemetry main extension activated
info:    ▪ [PREFERENCES-STORE]: LOADING ... +40ms
info:    ▪ [PREFERENCES-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/telemetry-lens-extension/preferences-store.json +0ms
info:    ▪ [LOCAL-METADATA-STORE]: LOADING ... +23ms
info:    ▪ [LOCAL-METADATA-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/local-metadata-store.json +0ms
info:    ▪ [RELEASE-NOTES-STORE]: LOADING ... +0ms
info:    ▪ [RELEASE-NOTES-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/release-notes-store.json +0ms
info:    ▪ [END-OF-TRIAL-STORE]: LOADING ... +1ms
info:    ▪ [END-OF-TRIAL-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/end-of-trial-store.json +0ms
info:    ▪ [GRACE-PERIOD-STORE]: LOADING ... +0ms
info:    ▪ [GRACE-PERIOD-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/grace-period-store.json +0ms
info:    ▪ [SPACES-SETTINGS-STORE]: LOADING ... +0ms
info:    ▪ [SPACES-SETTINGS-STORE]: LOADED from /Users/jalaziz/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/spaces-settings-store.json +1ms
info:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM Broadcasted spaces change to SpacesListener on renderer +27ms
warn:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM No spaces in SpaceSyncer disposeSpacesReaction, not changing selected space. +0ms
info:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM Lens Spaces Extension activated +2ms
info:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM [LENS-SPACES-EXTENSION] Registering cli +0ms
info:    ▪ [CLI] Registered command undefined teamwork +14ms
info:    ▪ [CLI] Registered command teamwork get-exec-credential <spaceName> <clusterId> +0ms
info:    ▪ [CLI] Registered command undefined clusters +0ms
info:    ▪ [CLI] Registered command clusters ls +0ms
info:    ▪ [CLI] Registered command clusters show <name> +0ms
info:    ▪ [CLI] Registered command clusters connect <name> +0ms
info:    ▪ [CLI] Registered command clusters disconnect <name> +0ms
info:    ▪ [LENS-SECURITY] activated +24ms
warn:    ▪ [LENS-DESKTOP-KUBE] not a valid lens subscription, stopping ... +64ms
info:    ▪ [LENS-DESKTOP-KUBE] Registering CLI commands +44ms
info:    ▪ [EXTENSION]: enabled @lensapp/cloud-sync-reporter@1.0.28 +4ms
info:    ▪ [EXTENSION]: enabled @lensapp/lenscloud-lens-extension@2.1.14 +1ms
info:    ▪ [EXTENSION]: enabled @lensapp/lens-desktop-kube-lens-extension@0.36.3 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/lens-license-extension@0.19.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/oci-image-lens-extension@0.36.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/shipa-lens-extension@0.23.5 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/support-lens-extension@0.16.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/survey-lens-extension@0.11.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/telemetry-lens-extension@0.13.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/tour-lens-extension@1.13.2 +0ms
info:    ▪ [CLI] Registered command undefined desktop-kube +0ms
info:    ▪ [CLI] Registered command desktop-kube ls +0ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /Users/jalaziz/Library/Application Support/Lens +0ms
info:    ▪ [CLI] Registered command desktop-kube create <name> +0ms
info:    ▪ [CLI] Registered command desktop-kube show <name> +0ms
info:    ▪ [CLI] Registered command desktop-kube start <name> +0ms
info:    ▪ [CLI] Registered command desktop-kube stop <name> +1ms
info:    ▪ [CLI] Registered command desktop-kube reset <name> +0ms
info:    ▪ [CLI] Registered command desktop-kube rm <name> +0ms
info:    ▪ [CLI] Registered command desktop-kube shell <name> +0ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /Users/jalaziz/.k8slens/extensions +2ms
Checking for update
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:52277... +22ms
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +48ms
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/Users/jalaziz/Library/Application Support/Lens/kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/Users/jalaziz/.kube' }
warn:    ┏ [KUBECONFIG-SYNC]: Failed to load config +10ms
warn:    ┃ [1] {
warn:    ┃ [2]   filePath: '/Users/jalaziz/.kube/kubectx',
warn:    ┃ [3]   details: 'Error: Invalid kubeconfig: root element is not an object'
warn:    ┗ [4] }
[76197:0302/230847.605709:ERROR:cert_verify_proc_builtin.cc(701)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (O=Lens,CN=Lens Certificate Authority) -----
ERROR: No matching issuer found


warn:    ┏ [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 3/2/2024, 11:08:47 PM InvalidGrantError error, reset Lens state and set connected=false... Offline user session not found +61ms
warn:    ┃ [1] Error: Offline user session not found
warn:    ┃ [2]     at t.refreshTokens (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/lenscloud-lens-extension/dist/main.js:2:17759)
warn:    ┃ [3]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
warn:    ┗ [4]     at async AuthTokenStore.refresh (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/lenscloud-lens-extension/dist/main.js:2:32644)
info:    ▪ [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters... +1ms
error:   ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM Error: Offline user session not found +5ms
warn:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM Couldn't refresh tokens, starting token refresher later. +1ms
info:    ▪ [LENS-SPACES-EXTENSION]: 3/2/2024, 11:08:47 PM isLensCloudStatusOk on initialization returns true +244ms
Update for version 2024.1.300751-latest is not available (latest version: 2024.1.300751-latest, downgrade is disallowed).
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded +450ms
(node:76459) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `Lens Helper (Renderer) --trace-warnings ...` to show where the warning was created)
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:49.105Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:49.106Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:49.287Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:49.287Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:49.287Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ┏ [CLUSTER]: activate +3s
info:    ┃ [1] {
info:    ┃ [2]   id: '8d900d77a8069a85887d77d7f0be300d',
info:    ┃ [3]   name: 'arn:aws:eks:us-east-1:00000000000:cluster/dev-eks',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8d900d77a8069a85887d77d7f0be300d',
info:    ┃ [3]   name: 'arn:aws:eks:us-east-1:00000000000:cluster/dev-eks',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8d900d77a8069a85887d77d7f0be300d',
info:    ┃ [3]   name: 'arn:aws:eks:us-east-1:00000000000:cluster/dev-eks',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ▪ [KUBE-AUTH-PROXY]: found port=52318 +117ms
info:    ┏ [CLUSTER]: refreshAccessibility +721ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8d900d77a8069a85887d77d7f0be300d',
info:    ┃ [3]   name: 'arn:aws:eks:us-east-1:00000000000:cluster/dev-eks',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="default" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +1ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="dev" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +1ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="automation" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +2ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="kube-public" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +74ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="kube-node-lease" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +0ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="observability" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +4ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="redpanda" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +0ms
warn:    ▪ [AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="kube-system" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution +1ms
info:    ┏ [CLUSTER]: refreshMetadata +4ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8d900d77a8069a85887d77d7f0be300d',
info:    ┃ [3]   name: 'arn:aws:eks:us-east-1:00000000000:cluster/dev-eks',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ▪ [BASE-STORE]: saving /Users/jalaziz/Library/Application Support/Lens/lens-cluster-store.json... +158ms
(node:76459) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `Lens Helper (Renderer) --trace-warnings ...` to show where the warning was created)
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:54.192Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:54.192Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ▪ Creating a new port-forward redpanda/pod/redpanda-console-568dcd795b-h8b8f:8080 +157ms
info:    ▪ Creating a new port-forward observability/service/kube-prometheus-prometheus:9090 +0ms
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:54.378Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:54.378Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-03-03T07:08:54.378Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=8d900d77a8069a85887d77d7f0be300d +423ms
info:    ▪ [BASE-STORE]: saving /Users/jalaziz/Library/Application Support/Lens/lens-cluster-store.json... +212ms
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=8d900d77a8069a85887d77d7f0be300d +1s
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=8d900d77a8069a85887d77d7f0be300d +856ms
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=8d900d77a8069a85887d77d7f0be300d +3s
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=8d900d77a8069a85887d77d7f0be300d +1s
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
```

**Additional context**

**Comment by Christiaanvdl** [comment]
Hello thank you for reaching out. we are working on the issue and thank you for reporting a bug.
