### ISSUE TITLE
Terminal in connecting...

### ISSUE THREAD

**Issue by cherry-koerber** [lensapp/lens#8033]
**Describe the bug**
When open a terminal on windows 10 machine 
![image](https://github.com/lensapp/lens/assets/132275390/e8084d7c-cef8-4ea6-ba53-e013629b432d)
![image](https://github.com/lensapp/lens/assets/132275390/227d49bd-7df9-44af-b993-e41c32e59625)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error: [SHELL-SESSION]: failed to open a local shell Error launching WinPTY agent: Security check failed: pipe client pid (6940) does not match agent pid (18204) {"stack":"Error: Error launching WinPTY agent: Security check failed: pipe client pid (6940) does not match agent pid (18204)\n    at new WindowsPtyAgent (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsPtyAgent.js:83:36)\n    at new WindowsTerminal (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsTerminal.js:51:24)\n    at spawn (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\index.js:29:12)\n    at C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\core-main\\dist\\index.js:3982:17\n    at getOrInsertWith (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\utilities\\dist\\index.js:697:19)\n    at ensureShellProcess (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\core-main\\dist\\index.js:3979:69)\n    at Object.openShellProcess (C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\core-main\\dist\\index.js:3997:42)\n    at async C:\\Users\\ChandraSekharMallu\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\core-main\\dist\\index.js:4132:7"}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Tixon123** [comment]
Hello cherry-koerber,

 Thank you for reaching out to Lens support!

 Thank you for reporting a bug. 

 We are working on your issue. Stand by for further updates. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc
