### ISSUE TITLE
lens is opening and closing automatically 

### ISSUE THREAD

**Issue by i053322** [lensapp/lens#8094]
**Describe the bug**
i installed the latest version of leans for mac apple
after i insatlled it i open the app , it is opening and automatically closed , i tried to uninstall and install but it didn't work 

**Expected behavior**
application will be open 

**Environment (please complete the following information):**
- Lens Version: leatest 
- OS: [e.g. OSX] 15.0 (24A335)
-

*

**Comment by Tixon123** [comment]
Hello i053322,

 Thank you for reaching out to Lens support!

 Thank you for reporting a bug. 

 We are working on your issue. Stand by for further updates. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by Tixon123** [comment]
Hello i053322,

 Is it possible to use the Support button in Lens to open a chat? Or do you have a Pro subscription to open the case? I'm asking because we need logs from you, but unfortunately, we can't ask you to share it here. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by i053322** [comment]
Hi @Tixon123  the Lens is not opening so i can;t share logs , i think it is related to the M3 core.

**Comment by i053322** [comment]
Hi @Tixon123  an update on it ?

**Comment by panuhorsmalahti** [comment]
Hi, at least for me M3 works fine.

To debug this further can you try starting Lens in debug mode with the following commands:
```
cd /Applications/Lens.app/Contents/MacOS/
DEBUG=true ./Lens
```

do you see any errors when starting Lens with this?

**Comment by i053322** [comment]
info:    ▪ [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-anything" took 1.01 ms.

Individual runnables took:
- app-paths-setup-main:setup-app-paths	0.42 ms +0ms
info:    ▪ [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-electron-is-ready-injection-token" took 92.12 ms.

Individual runnables took:
- internal-proxy-main:setup-lens-proxy-certificate      	88.5 ms
- lens-core-main:enforce-single-application-instance    	2.12 ms
- electron-main:setup-tracking-of-auto-updating         	0.22 ms
- lens-core-main:setup-behaviour-on-close-of-last-window	0.09 ms
- lens-core-main:setup-cleanup-of-backend-on-quit       	0.09 ms
- lens-core-main:setup-sentry                           	0.09 ms
- lens-core-main:setup-immer                            	0.08 ms
- electron-main:setup-runnables-after-window-is-opened  	0.05 ms
- electron-main:setup-application-name                  	0.03 ms
- electron-main:setup-hardware-acceleration             	0.03 ms
- lens-core-main:setup-hostnames                        	0.03 ms
- lens-core-main:setup-proxy-env                        	0.02 ms
- lens-core-main:setup-mobx                             	0.01 ms +93ms
info:    ▪ [LENS-EXTENSIONS]: LOADING ... +28ms
info:    ▪ Starting v2024.9.300059-latest of Lens... +2ms
info:    ▪ [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-application-is-loading-injection-token" failed in 7.11 ms.

Individual runnables took:
- (REJECTED)	lens-core-main:load-enabled-extensions-storage           	1.59 ms
- (RESOLVED)	messaging:start-listening-of-channels                    	1.19 ms
- (RESOLVED)	lens-core-main:log-version-on-start                      	0.14 ms
- (PENDING) 	user-preferences:storage-initialization
- (PENDING) 	local-storage-feature:run-initialization-of-local-storage
- (PENDING) 	cluster-common:storage-initialization
- (PENDING) 	internal-proxy-main:run-setup-lens-proxy
- (PENDING) 	lens-core-main:setup-cluster-state-broadcasting
- (PENDING) 	lens-core-main:setup-system-ca                            +2ms
TypeError: rawExtensions.map is not a function
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/core-common/dist/index.js:1708:42
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/dist/mobx.cjs.development.js:1241:15)
    at <unnamed action> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/dist/mobx.cjs.development.js:1226:12)
    at Object.loadAndStartSyncing (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/persistent-storage/dist/index.js:119:21)
    at run (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/core-main/dist/index.js:4651:15)
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/run-many-performance-logging/dist/index.js:83:20
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/run-many-of-slow-runnables/dist/index.js:68:30
    at instantiate (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/run-many/dist/index.js:131:11)
    at async Promise.all (index 6)
    at async runMany (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/run-many/dist/index.js:152:9)
info:    ▪ [LOCAL-STORAGE]: initialized +11ms
info:    ▪ 🔌 Starting LensProxy +14ms
info:    ▪ [INTERNAL-PROXY-MAIN]: Proxy server has started at 127.0.0.1:51504 +1ms
info:    ▪ 🔎 Testing LensProxy connection ... +0ms
info:    ▪ [LENS-USER-STORE]: LOADING ... +4ms
debug:   ┏ [USER-PREFERENCES]: fromStore() +5ms
debug:   ┃ [ 1] {
debug:   ┃ [ 2]   preferences: {
debug:   ┃ [ 3]     syncKubeconfigEntries: [
debug:   ┃ [ 4]       { filePath: '/Users/i053322/.kube' },
debug:   ┃ [ 5]       { filePath: '/Users/i053322/Downloads/kubeConfig-sa30-prod.yaml' },
debug:   ┃ [ 6]       { filePath: '/Users/i053322/Documents/k8s/kubeconfig-stg-aws-10.yaml' },
debug:   ┃ [ 7]       { filePath: '/Users/i053322/Documents/k8s/kubeconfig-us10-prod.yaml' },
debug:   ┃ [ 8]       { filePath: '/Users/i053322/Documents/k8s/kubeconfig-ci-aws-10.yaml' },
debug:   ┃ [ 9]       { filePath: '/Users/i053322/Documents/k8s/kubeconfig-br10-prod.yaml' }
debug:   ┃ [10]     ],
debug:   ┃ [11]     updateChannel: 'latest'
debug:   ┃ [12]   }
debug:   ┗ [13] }
info:    ▪ [LENS-USER-STORE]: LOADED from /Users/i053322/Library/Application Support/Lens/lens-user-store.json +1ms
info:    ▪ [BASE-STORE]: saving /Users/i053322/Library/Application Support/Lens/lens-user-store.json... +0ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADING ... +8ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADED from /Users/i053322/Library/Application Support/Lens/lens-cluster-store.json +7ms
info:    ▪ [BASE-STORE]: saving /Users/i053322/Library/Application Support/Lens/lens-cluster-store.json... +1ms
info:    ▪ ⚡ LensProxy connection OK +12ms

**Comment by i053322** [comment]
@panuhorsmalahti  - it is opened and closed

**Comment by i053322** [comment]
can you please advise me ? I am block

**Comment by panuhorsmalahti** [comment]
Thanks for the logs, we're investigating the issue!

**Comment by jansav** [comment]
> can you please advise me ? I am block

This should unblock you. Sorry for the inconvenience.

```
rm ~/Library/Application\ Support/Lens/lens-extensions.json

**Comment by i053322** [comment]
thanks it solved the issue
