### ISSUE TITLE
Lens App can not connect to some clusters (RangeError: Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by vlasashk** [lensapp/lens#8110]
**Describe the bug**
Unable to connect to some clusters (in UI keeps loading without any indication of a problem, in logs reports an error)

**To Reproduce**
1. Open Lens
2. Click on 'Local Kuberconfigs'
3. Click cluster to connect to

**Expected behavior**
Successfully connect to cluster and show cluster info or in case of error show error in UI

**Screenshots**
<img width="286" alt="exmpl" src="https://github.com/user-attachments/assets/150dfe59-08ac-465b-8f32-b7b936e2889d">

**Environment (please complete the following information):**
- Lens Version: 2024.9.300059-latest
- OS: MacOS Sonoma 14.4 (23E214)
- Installation method (e.g. snap or AppImage in Linux): from website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
...
(node:28179) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit
(Use `Lens --trace-warnings ...` to show where the warning was created)
debug:   ┏ [INTERNAL-PROXY]: [JSON-API] request POST https://127.0.0.1:61053/api-kube/apis/authorization.k8s.io/v1/selfsubjectaccessreviews +87ms
...(here configs data)
(node:28179) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use events.setMaxListeners() to increase limit
Error occurred in handler for 'activate-cluster': RangeError: Maximum call stack size exceeded
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:461:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:485:41
    at async /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:664:35
    at async /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:729:29
    at async _ensure (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:804:31)
    at async Object.ensure (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:822:23)
    at async /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/cluster-manager-main/dist/index.js:1123:5
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83654)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
configs are fine since I'm able to connect to all clusters without any issues via kubectl

**Comment by clrothmann** [comment]
Thank you for your feedback @vlasashk. To further investigate your issue in more detail, could you please provide the following information: What happens when you manually disconnect and reconnect during this state? -> Right-click on your cluster in the left-hand Navigator, click the corresponding entry in the context menu, and then click on the cluster again. I will pass your issue along with your log excerpts to the corresponding team. Looking forward to your response!

**Comment by vlasashk** [comment]
@clrothmann in this state it is not possible to disconnect since the "Disconnect" button is not present
![image](https://github.com/user-attachments/assets/0af4b89a-04cf-4b5d-9322-f3774f459610)
Another issue is that if any cluster is in this state is present - the app won't be able to close gracefully and it needs to terminated with SIGKILL
- normal termination log (no cluster in error state)
![image](https://github.com/user-attachments/assets/9759506e-68e0-48a2-a6f1-3654dc54ea8e)
- stuck termination log (with cluster error state)
![image](https://github.com/user-attachments/assets/81bb60fc-dc73-4eb9-979b-483a1a642cbd)

**Comment by NikPoliakov** [comment]
I am also facing this issue.

![Screenshot 2024-10-24 195030](https://github.com/user-attachments/assets/a09a69a6-023a-406e-9470-b73cc309addc)

Failed to refresh accessibility: RangeError: Maximum call stack size exceeded

It only happens with one cluster out of 24 I have in Lens.
kubectl and other tools like k9s and Headlamp work just fine.

is there any more information I can provide here ?

**Comment by dechegaray** [comment]
Several optimizations and performance improvements have been applied since this bug was reported (timeouts in cluster connections, memory leaks fixed, optimizations in the permission checks during cluster connections, etc etc). We suggest upgrading to our latest version `2025.2.141554-latest`, and let us know if the issue persist
