### ISSUE TITLE
Update button appears but throws an error when a user tries to update

### ISSUE THREAD

**Issue by iFabrycio** [lensapp/lens#8139]
**Describe the bug**
The bug consists in the update button appearing on top-left corner, but when i click on it and on relaunch, an error is thrown with a long stacktrace and a message 'Uncaught Exception: Error: Tried to install update but no update was discovered.'

**To Reproduce**
The update button must be available
1. Click on 'update'
2. Click on 'Relaunch to update Lens'
An error will be trown with the following stacktrace

```
Uncaught Exception:
Error: Tried to install update but no update was discovered.
at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/core-main/dist/index.js:7848:15
at IpcMainImpl.nativeOnCallback (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/messaging-for-main/dist/index.js:60:9)
at IpcMainImpl.emit (node:events:514:28)
at IpcMainImpl.emit (node:domain:489:12)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:79287)
at WebContents.emit (node:events:514:28)
at WebContents.emit (node:domain:489:12)
```

**Expected behavior**
I should update lens.

**Screenshots**
![Captura de Tela 2024-12-11 às 09 23 00](https://github.com/user-attachments/assets/db42a3d1-8cc1-4dee-a4bc-f0fb418df23c)

**Environment (please complete the following information):**
- Lens Version:
```
Lens: 2024.8.291605-latest
Extension API: 6.10.39
Electron: 27.3.11
Chrome: 118.0.5993.159
Node: 18.17.1
© 2023 Mirantis, Inc.
```
- OS: MacOs Sequoia M3 15.0.1 (24A348)

**Comment by Tixon123** [comment]
Hello iFabrycio,
 
 Thank you for reaching out to Lens support!

 Thank you for reporting a bug. 

 We are working on your issue. Stand by for further updates. 

Best Regards,
Tikhon Kudinov
Lens Support Engineer
Mirantis, Inc

**Comment by panuhorsmalahti** [comment]
What update channel is selected for you in the App Settings?

**Comment by iFabrycio** [comment]
Is the default one (STABLE)
