### ISSUE TITLE
App crash at open ingress in network

### ISSUE THREAD

**Issue by soufianez75** [lensapp/lens#895]
Error stack:

 
TypeError: Cannot read property 'length' of undefined
    at r.value (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:8204711)
    at r.value (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:8206631)
    at ve (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:33319)
    at http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:13199
    at ce (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:31425)
    at e.track (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:42789)
    at r.l [as render] (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:13147)
    at r.X (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:13294)
    at r.t.render (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:12570)
    at xo (http://6f76d512-0093-41e5-b88e-60a0fa7b6bb9.localhost:62013/build/Lens.js:2:4287558)

**Comment by soufianez75** [comment]
[`[](url)`](url)

**Comment by soufianez75** [comment]
<img width="1573" alt="Capture d’écran 2020-09-16 à 16 08 14" src="https://user-images.githubusercontent.com/15089638/93349160-6f27f200-f837-11ea-9af0-1bb282e55fe8.png">
