### ISSUE TITLE
can't launch lens within centos7

### ISSUE THREAD

**Issue by wplatform** [lensapp/lens#903]
**launch log**

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/index.js
- /var/lib/snapd/snap/kontena-lens/118/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/var/lib/snapd/snap/kontena-lens/118/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.1Xsd1i)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/lib/snapd/snap/kontena-lens/118/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

(kontena-lens:15793): GdkPixbuf-WARNING **: 14:45:08.678: Cannot open pixbuf loader module file '/home/cms/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/cms/snap/kontena-lens/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
GLib-GIO-Message: 14:45:09.179: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

**Comment by israelKusayev** [comment]
I get the exact same error on centos 7

**Comment by pmdawood** [comment]
Got the same error when i have tried to launch lens on centos 7.can you help on this?
./Lens-4.0.7.AppImage 
[13561:0124/165009.189457:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
[root@myuser]# ./Lens-4.0.7.AppImage --no-sandbox
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_Lens-4mB7YeF/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_Lens-4mB7YeF/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.YcSFH2)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_Lens-4mB7YeF/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
Aborted (core dumped)

**Comment by OttawaSquirrel** [comment]
I am also seeing the same error. Mint with a DEB install.
[error.log](https://github.com/lensapp/lens/files/6193242/error.log)

**Comment by Nokel81** [comment]
Seems to be the same issue as #1038 does the workaround there help?

**Comment by dawoodmohamed** [comment]
@Nokel81 i have tried the solution mentioned[#1038](https://github.com/lensapp/lens/issues/1038) but still i didn't work for me.please help us,all our machine are centos based , and we are completely struck here.

**Comment by Nokel81** [comment]
@Nachasic any ideas?

**Comment by savioteles** [comment]
Any ideas? We are facing the same problem here.

**Comment by sortel64** [comment]
No success building the latest release on CentOS 7 here.  We are completely stuck here too.  It seems that when Mirantis says Linux they really mean Ubuntu Linux.

Has anyone tried to run this in a Docker container?

**Comment by brcros** [comment]
Try to add these 2 libs into /opt/Lens :
- libstdc++.so.6
- libc.musl-x86_64.so.1

It works for me, using Lens 5.3.1.
The point is to find the good release. Lens will tell you if the version is not the one... 

Bruno

**Comment by sortel64** [comment]
Thanks for the hint!  May I ask where you found these?  A particular Linux (e.g. Ubuntu vX, or Fedora X, etc)?

Scott

**Comment by urlichLivonian** [comment]
I got the same error on Ubuntu 20.04. It seems that during the installation process the ASAR archive is not unpacked. I had to do it manually and it works!

For DEB install:

`npm install -g asar`
`cd /opt/Lens/resources`
`npx asar extract app.asar ./unpack`
`mv app.asar app.asar.orig`
`mv unpack app.asar`

**Comment by ymartineau** [comment]
here is the workaround I used to install and use k8s lens on centos 7 (and also without account):

```
$ wget https://api.k8slens.dev/binaries/Lens-5.5.4-latest.20220609.2.x86_64.rpm
$ sudo yum install Lens-5.5.4-latest.20220609.2.x86_64.rpm 
```

<same error message>

according to https://forums.centos.org/viewtopic.php?t=68062#p285777:

> CXXABI_1.3.9 is associated with gcc version 5.1. CentOS 7 has gcc 4.8.5.

install more recent gcc version to get a more recent libstdc++ version.

build gcc (following instructions from https://jdhao.github.io/2017/09/04/install-gcc-newer-version-on-centos/ with the latest current gcc version)

Other dependencies might be required (at least "Development Tools" group, etc.)

```
$ cd $HOME/programs
```

(you can use your local mirror https://gcc.gnu.org/mirrors.html)
```
$ wget https://ftp.lip6.fr/pub/gcc/releases/gcc-12.1.0/gcc-12.1.0.tar.gz
```

```
$ yum install gmp-devel mpfr-devel libmpc-devel
$ tar xzf gcc-12.1.0.tar.gz
$ mkdir gcc-12.1.0-build
$ mkdir gcc-12.1.0-local
$ cd gcc-12.1.0-build
$ ../gcc-12.1.0/configure --prefix=$HOME/programs/gcc-12.1.0-local/ --enable-languages=c,c++ --disable-multilib
$ make -j$(nproc) && make install
```

add symlink to this more recent libstdc++.so library:
```
$ cd /opt/Lens
$ sudo ln -s $HOME/programs/gcc-12.1.0-local/lib64/libstdc++.so.6
```

By default lens is asking for an account. https://twitter.com/k8slens/status/1529470612380344321?s=21&t=yvydstNYJkrBPcKI_PTrwQ
To avoid the use of this account and use it locally:

```
$ sudo vi /etc/hosts
```
add:
```
127.0.0.1 app.k8slens.dev
```

**Comment by Nokel81** [comment]
We have started building RPM packages on rocky Linux and now have a YUM repo so this should now be resolved.
