### ISSUE TITLE
Lens app crashed when displaying details for ingress rule

### ISSUE THREAD

**Issue by renaudhager** [lensapp/lens#924]
**Describe the bug**
App is crashing when I try to get the details of ingresses rule.

**To Reproduce**
1. Go to 'Network'
2. Select 'Ingresses'
3. Click on any rule 

**Expected behavior**
Details of the ingresses should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/12563305/93581510-29833a80-f999-11ea-95d5-a73274b2f391.png)

**Environment (please complete the following information):**
- Lens Version: 3.62 (present since 3.6.0)
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
TypeError: Cannot read property 'length' of undefined
    at r.value (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:8204700)
    at r.value (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:8206620)
    at ve (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:33319)
    at http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:13199
    at ce (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:31425)
    at e.track (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:42789)
    at r.l [as render] (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:13147)
    at r.X (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:13294)
    at r.t.render (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:12570)
    at xo (http://a7066035-d724-49b9-b36f-7c15670c7b24.localhost:55395/build/Lens.js:2:4287638)
```

**Comment by renaudhager** [comment]
Fix in 3.6.3.
